### ISSUE TITLE
Security Group Upsert - InvalidPermission.Duplicate

### ISSUE THREAD

**Issue by ndcampbell** [spinnaker/spinnaker#1020]
It looks like a bug was introduced in Clouddriver v1.231 which does not allow an AWS security group to be upserted if it already exists. 

Prior to Clouddriver v1.231, I was able to POST a task formatted as such:

```
{
    "application": "edgeforrest",
    "description": "Create Security Group: edgeforrest",
    "job": [
        {
            "credentials": "dev",
            "description": "something useful",
            "detail": "",
            "name": "edgeforrest",
            "regions": [
                "us-east-1"
            ],
            "securityGroupIngress": [

                {
                    "name": "apps_all",
                    "type": "tcp",
                    "startPort": 80,
                    "endPort": 80

                },

                {
                    "name": "apps_all",
                    "type": "tcp",
                    "startPort": 8080,
                    "endPort": 8080

                }

            ],
            "subnet": "none",
            "type": "upsertSecurityGroup",
            "user": "pipes-securitygroup",
            "vpcId": "vpc-id"
        }
    ]
}
```

This would upsert the security group and if nothing had changed, would still exist successfully.

On Clouddriver v1.231 and greater, this throw the following error if nothing is updated:
```
the specified rule "peer: sg-65bd2003, TCP, from port: 80, to port: 80, ALLOW" already exists (Service: AmazonEC2; Status Code: 400; Error Code: InvalidPermission.Duplicate; Request ID: 34b2db6e-6d22-4bf3-b8f7-cd1de0837408)
```

I would expect an upsert to be successful if nothing has changed. Is this a bug?

**Comment by ndcampbell** [comment]
I found this is due to lines 82-84 in https://github.com/spinnaker/clouddriver/blob/5f2fef9f6b8679b475e34eba93238e8f59b50b49/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy#L82

not sure what this block does

**Comment by anotherchrisberry** [comment]
Unfortunately, we ran into problems with this block of code:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy#L91-L92
We're using the Groovy shorthand `-` to remove items from the collection, which compares items in the two collections via their `equals` methods.

The original changes from 7/14 were put in place because we were seeing the same error message when editing security groups with cross-account rules via the UI (https://github.com/spinnaker/deck/pull/2448).

We might get around this by conditionally including the `vpcId` field from the UI only if it differs between the security group and the ingress rule.

If you'd like to test and verify that's the case, I'd be happy to work with you on a PR for Deck.

**Comment by ndcampbell** [comment]
@anotherchrisberry cool, thanks for the explanation. So you are thinking that the `vpcId` here https://github.com/spinnaker/deck/blob/master/app/scripts/modules/amazon/securityGroup/configure/EditSecurityGroupCtrl.js#L53 should ONLY be included if it is a cross-account rule?

Also, we are POSTing the JSON directly to Gate, would updating Deck (potentially) fix this or will there need to be a subsequent change in Gate?

**Comment by anotherchrisberry** [comment]
@ndcampbell yep, exactly.

I ran some tests locally where I only sent the VPC ID on the cross-account rules and it worked as expected with those two lines in Clouddriver commented out. Will get some PRs together shortly.

**Comment by ndcampbell** [comment]
Oh great! @anotherchrisberry, do you need me to do anything for this then or you just going to put in the PRs?

**Comment by anotherchrisberry** [comment]
Nope - I'll take care of it. Just running a few more tests...

**Comment by anotherchrisberry** [comment]
Resolved via referenced PRs
