### ISSUE TITLE
Orca Build error

### ISSUE THREAD

**Issue by veeresh1982** [spinnaker/spinnaker#1166]
Getting following error when building Orca [ java: 1.8.0_101, gradle:2.9 ]

/orca# gradle bootRun
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'services.fiat.baseUrl' in string value "${services.fiat.baseUrl}"

**Comment by duftler** [comment]
Have reproduced this. Looking now...

**Comment by duftler** [comment]
Ok, should be good to go now.

**Comment by ttomsu** [comment]
@duftler 's fix shouldn't be needed. Fiat isn't enabled yet, so nothing should be looking for that value. 

* Can you post the rest of the stack trace? 
* Are you running with the standard [spinnaker.yml](https://github.com/spinnaker/spinnaker/blob/master/config/spinnaker.yml) file? 
* What evironment are you running Spinnaker in? (VM on a (which?) cloud provider, Kubernetes, Docker compose)

**Comment by duftler** [comment]
Can be reproduced by running orca standalone via `./gradlew`.

**Comment by ttomsu** [comment]
@gregturn and I found the root cause of this issue. Specifically why this startup issue was happening in Orca but not Clouddriver, which has the same `fiat-api` module integrated. 

It turns out that Swagger (pulled in via `korkSwagger`) sets `ignoreUnresolvablePlaceholders` to true, which meant the `@Value("${services.fiat.baseUrl}")` annotation would resolve to a string literally containing "${services.fiat.baseUrl}". Orca, while it pulls in the Swagger library, does not have swagger enabled by default, which means it doesn't have anything to turn off the unresolvable placeholders, therefore throws the error you saw.

Working on a proper fix.
tag: https://github.com/spinnaker/fiat/issues/70
