### ISSUE TITLE
why spinnaker Application name  ignore case ?

### ISSUE THREAD

**Issue by wangchangjian** [spinnaker/spinnaker#1229]
when i input the name as  App1,  it is change to app1, is this reasonable?

**Comment by danielpeach** [comment]
The name of a Google Compute Engine managed instance group (which maps to a server group within Spinnaker) can't contain a capital letter. This is also true of other GCE resources. A server group name in Spinnaker always starts with the application's name, which is why an application name can't contain a capital letter.

**Comment by wangchangjian** [comment]
thanks a lot!

**Comment by wczqll** [comment]
When I scan pages by deck, sometimes page apperars http code named 429, causing e2e test failed by protractor. how can i avoid this case?
