### ISSUE TITLE
Deck's applications page display applications that are not created by spinnaker

### ISSUE THREAD

**Issue by donghui** [spinnaker/spinnaker#1260]
**Title**

In Spinnaker Deck's applications page it display applications that are not created by spinnaker

**Cloud Provider**

GCP+Kubernetes(GKE)

**Environment**

I am running Spinnaker using the Google images to deploy into GCP.

**Description**

In Spinnaker Deck's applications page it display applications like gke, heapster, kube, kubernetes, I7 that are not created by spinnaker as below image.

![capture](https://cloud.githubusercontent.com/assets/449127/19585779/f6ac4fe8-9781-11e6-8f12-9f387ead6cb2.JPG)

**Steps to Reproduce**

1, when i create a container environment in Google Cloud Platform, gke is displayed in application list.
2, after i follow [Kubernetes Source To Prod](http://www.spinnaker.io/docs/kubernetes-source-to-prod) to create serve application, heapster, kube, kubernetes, I7 are displayed in application list.

**Comment by tomaslin** [comment]
Spinnaker will try to index all server groups that are available in the provided environments. This is so if you were migrating from older platforms like Asgard, you still would see your ASGs. 

If you click on any of these applications, you should at least see an ASG in the clusters view. If you go to the configuration screen, you would see that the application doesn't really exist. 

This is really by design and not a bug.

**Comment by donghui** [comment]
But, sometimes, We don't want the applications not created by spinnaker are displayed in list. Customers will be wondering which applications need to be managed. It is possible that let customer to decide whether or not that applications be displayed. Like add a setting item in configuration file.

**Comment by tomaslin** [comment]
Functionality is as intended. If you wish to add a configuration flag, please submit a pull request. Code is here - https://github.com/spinnaker/gate/blob/master/gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
