### ISSUE TITLE
Missing cpu and memory requests and limits for Kubernetes deploys

### ISSUE THREAD

**Issue by olvesh** [spinnaker/spinnaker#1311]
I am evaluating Spinnaker for use in Kubernetes on AWS. To be able to run as a good citizen and make sure  components in our deploy cluster not interfere with each other it would be beneficial if the Kubernetes pod/container-specs had cpu/memory requests and limits.

It is hard for me on a new installation to have an opinion of the resource usage of these components.

**Comment by dforrest88** [comment]
+1

**Comment by wjoel** [comment]
Seems it can be set manually, https://www.spinnaker.io/reference/halyard/component-sizing/#cpu--memory-requestslimits but they really should be set to something that works for the initial deployment and a re-deploy with reasonable resource usage.

Currently re-deploying on a single node with 16 GBs of RAM fails miserably, even with zero Spinnaker deployments active, which seems unreasonable. It's making experimentation unnecessarily painful, since I have to delete the spinnaker namespace and do a full deploy from scratch if I need to change Spinnaker settings, and it's good practice to set limits in Kubernetes.
