### ISSUE TITLE
Make AWS default region configurable

### ISSUE THREAD

**Issue by eisig** [spinnaker/spinnaker#1357]
*Title*

Make AWS default region configurable
*Cloud Provider*

AWS

*Environment*

We are using spinnaker in AWS cn-north-1. The account of cn-north-1 can not be used in other regions.  
The ```AmazonHealthIndicator.checkHealth```   is hardcode to use ```us-east-1```, and 
```AmazonClientProvider.DEFAULT_REGION``` is null. We have to hardcode to `cn-north-1` to make it work.  
Would please make these values read from config files?

*Feature Area*

clouddriver

*Description*

*Steps to Reproduce*

*Additional Details*

**Comment by cfieber** [comment]
The amazonhealthindicator fix is an easy one.

I recently put in some other changes such that the standard ado options for selecting a region should work as expected (set AWS_REGION env var)

**Comment by cfieber** [comment]
clouddriver 1.483.0 has the health indicator fix in it.

can you confirm that you are all set otherwise for running in `cn-north-1` ? (ensure you have AWS_REGION=cn-north-1 set as an environment variable or 

```
[default]
region=cn-north-1
```
in ~/.aws/config

or that you are running on an EC2 instance in cn-north-1 with access to the instance metadata endpoint.
