### ISSUE TITLE
Not able to choose security group and network in spinnaker application

### ISSUE THREAD

**Issue by phanikumarp** [spinnaker/spinnaker#1403]
NOT able to Network   and select security groups while creating application in spinnaker
in pipeline or before pipeline configuration also.. even refreshing...
![spinaker issuesc](https://cloud.githubusercontent.com/assets/8611683/22593916/d1a984be-ea46-11e6-9279-f02ccd65f910.png)

**Comment by duftler** [comment]
The Add button is disabled because some options aren't populated. I can't see the Network control, but choosing a security group isn't required. Please check your browser console to see if there are any errors (incl. the network tab). There are also some details on refreshing your local cache on this page: http://www.spinnaker.io/docs/troubleshooting-guide

**Comment by duftler** [comment]
We believe this is the same issue described here: https://spinnakerteam.slack.com/archives/general/p1486308998004657
Fix is to upgrade to the latest services and to dump your redis cache.
