### ISSUE TITLE
Trigger does not start after update image in docker registry 

### ISSUE THREAD

**Issue by veniciobsb** [spinnaker/spinnaker#1424]
*Title*

Trigger does not start after update image in docker registry 

*Cloud Provider*

Kubernetes (local deployment)

*Environment*

Install spinnaker in local deployment for a cluster kubenetes. Tested in local registry and docker.io registry, with the same Behavior.

*Feature Area*

Pipelines, Triggers, Echo, Igor

*Description*

Trigger does not start after update image in docker registry. But the trigger works when the tag is created for firt time. The problem is when the image is updated

*Steps to Reproduce*

Create a docker registry trigger in pipeline, configure the cluster to deploy in kubenetes and update a image in docker registry.

*Additional Details*

- No errors in logs (igor, echo, clouddriver)
- The image tag changes, when travis build de application
- Tested in local regsitry e docker.io registry 
- Trigger with regex 
- Version
  - Clouddriver v1.491.0
  - Gateway v3.1.0
  - Igor  v1.61.0
  - Echo v1.127.0

**Comment by willgorman** [comment]
I've been seeing this as well.  Is this the intended behavior?

**Comment by johnmshields** [comment]
We are seeing the same issue. The problem appears to be that `clouddriver` does not return a `digest` property for images obtained from Google Container Registry.

Example output from clouddriver's `/dockerRegistry/images/find`:

```
  {
    "account": "example-acct",
    "artifact": {
      "metadata": {
        "registry": "us.gcr.io"
      },
      "name": "example-acct/example",
      "reference": "us.gcr.io/example-acct/example:999df7c1-d717-4ab4-97ca-5da0388f6c15",
      "type": "docker",
      "version": "999df7c1-d717-4ab4-97ca-5da0388f6c15"
    },
    "registry": "us.gcr.io",
    "repository": "example-acct/example",
    "tag": "999df7c1-d717-4ab4-97ca-5da0388f6c15"
  }
```
So then [this code](https://github.com/spinnaker/igor/blob/master/igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy#L113) from `DockerMonitor.groovy` skips the update since `lastDigest` is "~" and `image.digest` is null:

```
                        if (lastDigest != image.digest) {
                            log.info "Updated tagged image: ${image.account}: ${imageId}. Digest changed from [$lastDigest] -> [$image.digest]."
                            // If either is null, there was an error retrieving the manifest in this or the previous cache cycle.
                            updateCache = image.digest != null && lastDigest != null
                        }
```

**Comment by willgorman** [comment]
I think this related to the `trackDigests` property in the clouddriver Docker registry configuration, which is not enabled by default and appears to [not be recommended](https://github.com/spinnaker/clouddriver/blob/a49a00b74294a09cd3f21f6bc459f3d4f77b9830/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy#L46).

**Comment by johnmshields** [comment]
OK, I see what is happening in my case. I had originally ran Spinnaker with the `trackDigests` property set to false (default). In addition, it appears that at some point (maybe on a first run?) the clouddriver must have returned `null` for the image digests for all my images and tags. I verified this by looking in redis and seeing that they all had the digest value set to `~`.

The "fix" I used was to enable `trackDigests`, restart spinnaker, and then go into redis and manually delete all the cached entries (`redis-cli -a <pass> KEYS "igor:dockerRegistry:*" | xargs redis-cli -a <pass> DEL`). This caused all the entries to get recreated, this time with proper digests. Now when a tag moves it seems to be properly picking that up and triggering my pipeline.

I do think there is a slight bug (or at least documentation enhancement) here  as once the `~` gets into a digest entry you have to manually delete it out of redis to ever get it updated (as far as I can tell). This is because the `lastDigest` will always be `null` so the `updateCache` boolean will always be false.

I see the logic here but I think it should likely be more like:

```
if (image.digest != null && lastDigest != image.digest) {
    log.info "Updated tagged image: ${image.account}: ${imageId}. Digest changed from [$lastDigest] -> [$image.digest]."
    // If either is null, there was an error retrieving the manifest in this or the previous cache cycle.
    updateCache = true
} else {
    log.debug "Not updating tagged image: ${image.account}: ${imageId}. Last digest=[$lastDigest], current digest=[$image.digest]."
}
```

If the `clouddriver` returns an actual image digest then it doesn't matter if the old one was null. I still want this to update the cache if my settings have `trackDigests` enabled.

**Comment by lwander** [comment]
The fact that track digests is disabled is intentional - also - clearing your redis cache is generally good practice after changing clouddriver configuration.

**Comment by svachmic** [comment]
Hi, I see this issue is closed, however we are still experiencing it.

We have Spinnaker deployed from Google Cloud Launcher and we've configured our build pipeline starting by a trigger on push to Google Container Registry. When Google Container Builder finishes packaging our container to be deployed, pipeline is unfortunately not triggered.

We could not find any suitable solution, neither here, nor in [this StackOverflow issue](https://stackoverflow.com/questions/46532267/i-cant-get-the-images-from-us-gcr-io-in-spinnaker-pipeline-trigger-configuratio). Little difference here - instead of us.gcr.io, we have eu.gcr.io.

Any advice? Thanks a lot!

**Comment by veniciobsb** [comment]
Hi, Unfortunately not.

 I changed my deployment processo, It always change the release number and
push a New image.

Em 16 de out de 2017 13:01, "Michal Švácha" <notifications@github.com>
escreveu:

**Comment by mpagnucco** [comment]
Experiencing this event with Spinnaker 1.5.0 paired with an AWS ECR. I have increased cache interval and redeployed but still I see in igor logs that it is fetching every 30 seconds and it is doing so without any error:

`2017-11-28 17:07:09.340  INFO 25539 --- [readScheduler-1] c.n.spinnaker.igor.docker.DockerMonitor  : no discoveryClient, assuming InService
2017-11-28 17:07:09.340  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : ---> HTTP GET http://localhost:7002/credentials
2017-11-28 17:07:09.345  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : <--- HTTP 200 http://localhost:7002/credentials (5ms)
2017-11-28 17:07:09.345  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : ---> HTTP GET http://localhost:7002/credentials/my-docker-registry
2017-11-28 17:07:09.346  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : <--- HTTP 200 http://localhost:7002/credentials/my-docker-registry (1ms)
2017-11-28 17:07:09.346  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : ---> HTTP GET http://localhost:7002/dockerRegistry/images/find?account=my-docker-registry
2017-11-28 17:07:09.348  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : <--- HTTP 200 http://localhost:7002/dockerRegistry/images/find?account=my-docker-registry (1ms)
2017-11-28 17:07:39.340  INFO 25539 --- [readScheduler-1] c.n.spinnaker.igor.docker.DockerMonitor  : no discoveryClient, assuming InService
2017-11-28 17:07:39.340  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : ---> HTTP GET http://localhost:7002/credentials
2017-11-28 17:07:39.345  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : <--- HTTP 200 http://localhost:7002/credentials (4ms)
2017-11-28 17:07:39.345  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : ---> HTTP GET http://localhost:7002/credentials/my-docker-registry
2017-11-28 17:07:39.347  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : <--- HTTP 200 http://localhost:7002/credentials/my-docker-registry (1ms)
2017-11-28 17:07:39.347  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : ---> HTTP GET http://localhost:7002/dockerRegistry/images/find?account=my-docker-registry
2017-11-28 17:07:39.348  INFO 25539 --- [readScheduler-1] c.n.s.i.d.service.ClouddriverService     : <--- HTTP 200 http://localhost:7002/dockerRegistry/images/find?account=my-docker-registry (1ms)
`

Registry config:

`ubuntu@infra-ci:~$ hal config provider docker-registry 
+ Get current deployment
  Success
+ Get the dockerRegistry provider
  Success
+ Successfully got provider dockerRegistry.
Provider(enabled=true, accounts=[DockerRegistryAccount(address=https://XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com, username=AWS, password=null, email=fake.email@spinnaker.io, cacheIntervalSeconds=60, repositories=[XXXXX-api, XXXXX-frontend], passwordFile=/opt/ecr/passwords/my-registry.pass, dockerconfigFile=null)], primaryAccount=my-docker-registry)
`

**Comment by ehab180hb** [comment]
A whole year and multiple releases later, the issue still persists!

**Comment by mpagnucco** [comment]
I finally found out what was happening to me in particular. Maybe this will help others. I'm running spinnaker on an ec2 instance and configured a docker registry with hal:

```
hal config provider docker-registry account add my-docker-registry \
     --address XXXXX.dkr.ecr.us-east-1.amazonaws.com \
     --repositories XXXXX  \
     --username AWS \
     --password-file /opt/ecr/passwords/my-registry.pass
```

I use a docker container that runs in the background and refreshes the token every 30 minutes:

```
docker run --restart always -d -v /opt/ecr/passwords:/opt/passwords \
-v $(pwd)/ecr-config.yml:/opt/config/ecr-token-refresh/config.yaml \
quay.io/skuid/ecr-token-refresh:latest
```
The new token gets written every 30m to /opt/ecr/passwords/my-registry.pass and my spinnaker configuration points to this file. This should work, but after some hours I would have to run 'hal deploy apply' to have triggers running again, every time. Turns out that when 'hal deploy apply' runs it *creates a copy* of my password file and stores it on some subdirectory inside .hal, which I was able to find on /opt/spinnaker/config/clouddriver.yml

passwordFile: /home/ubuntu/.hal/default/staging/dependencies/1566732450-my-registry.pass

After replacing that file with a symlink to /opt/ecr/passwords/my-registry.pass this has finally gone away.

**Comment by ethanfrogers** [comment]
@mpagnucco nice find. i've also heard this from others who are using `ecr-token-refresh` which is unfortunate. it seems that a recent update with halyard broke the semantics of `passwordFile` for this use case specifically. i'm not entirely sure what the appropriate resolution is at this point though since some folks are probably relying on the _new_ behavior.

**Comment by angheladrianclaudiu** [comment]
Same behavior here.
I have to do a `hal deploy apply --service-names=clouddriver` in order to make it work again. So any workaround would be much appreciated.

**Comment by D-wenhao** [comment]
> Same behavior here.
> Also using ECR and ecr-token-refresh docker container to refresh the password file.
> I have to do a `hal deploy apply --service-names=clouddriver` in order to make it work again. So any workaround would be much appreciated.
@angheladrianclaudiu 
I also encountered a similar problem. The pipeline will work normally only after the clouddriver is restarted. The mirror trigger becomes normal. Is there any way to repair it
