### ISSUE TITLE
Can't deploy application with '-' in the name

### ISSUE THREAD

**Issue by ismith** [spinnaker/spinnaker#1438]
*Title*

Can't deploy application with '-' in the name

*Cloud Provider*

Kubernetes

*Environment*

I'm using spinnaker pipelines to deploy images into a k8s cluster on AWS.

*Feature Area*

Clouddriver

*Description*

I created a pipeline for my application, "foo-bar-2".  I can trigger the pipeline via a webhook, as expected, but it fails fast in the deploy, with the error "Exception ( Create Server Group )
deployKubernetesAtomicOperationDescription.application.invalid (Must match ^[a-z0-9]+$)"

Grepping suggests that this is a validation in clouddriver, and the application name must match StandardKubernetesAttributeValidator.prefixPattern?

Everything works if I modify the application name (in both the application and the pipeline).

*Steps to Reproduce*

*Additional Details*

**Comment by roykachouh** [comment]
It looks like the culprit is actually in the cloud driver kubernetes validator. Is this an actual restriction in k8's? if not, i can submit a PR with the fix:

https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/validators/StandardKubernetesAttributeValidator.groovy#L27

**Comment by tomaslin** [comment]
foo-bar-2 is not a valid application name.

**Comment by tomaslin** [comment]
we use frigga to validate server group names and it uses - as a separator

**Comment by lwander** [comment]
Due to frigga, this is working as intended
