### ISSUE TITLE
Kubernetes and Deck: Copy Server Group drops Container Fields

### ISSUE THREAD

**Issue by emjburns** [spinnaker/spinnaker#1557]
Within the kubernetes provider, I'm creating a new pipeline to upgrade Spinnaker. Deck is configured as follows:
![screen shot 2017-04-10 at 2 36 11 pm](https://cloud.githubusercontent.com/assets/8454927/24883891/c9b76fa8-1dfb-11e7-8b40-846486b82175.png)
I want to copy this cluster, so from within my pipeline I select deploy, then add server group:
![screen shot 2017-04-10 at 2 35 43 pm](https://cloud.githubusercontent.com/assets/8454927/24883901/dffb520c-1dfb-11e7-9ce3-2927054876e4.png)
I copy from the deck cluster that's running:
![screen shot 2017-04-10 at 2 35 55 pm](https://cloud.githubusercontent.com/assets/8454927/24883916/f046a38c-1dfb-11e7-87a8-d74516426a21.png)
The information in the first sections is copied successfully, including secrets (not shown in this picture): 
![screen shot 2017-04-10 at 2 36 43 pm](https://cloud.githubusercontent.com/assets/8454927/24883930/feae0dca-1dfb-11e7-80cf-7485d6f26503.png)

**But, the container section has reverted back to a port of 80** (should be 9000) **and no health probe**.
![screen shot 2017-04-10 at 2 37 05 pm](https://cloud.githubusercontent.com/assets/8454927/24883954/15f5a196-1dfc-11e7-99a0-371d64d26239.png)

This is the bug: I'd expect these container fields to be copied over to my new server group, because in the notes on "copy" it specifies that container configuration will be copied over.

**Comment by dmourati** [comment]
Not certain if related, but I am experiencing a similar problem in which my Spinnaker cluster running on k8s managing AWS drops data during a server group copy. In this case, the user data field gets lost.

**Comment by emjburns** [comment]
I think I've figured this out.

I’ve deployed spinnaker into k8 using the setup in spinnaker/experimental/kubernetes. Those containers deploy version “master”. But, I’ve hooked up spinnaker to my internal artifact server, which doesn’t have version “master”. When I hit ‘copy’ on a container that’s deployed with version “master”, my spinnaker can’t find it and therefore the container doesn’t show up in ‘basic settings’ and the configuration gets wiped. When I have a named version deployed that’s also in my internal artifactory, the settings copy over because it can find the container.

I'd like this case to be covered by the 'copy' function - something like, if the container can’t be found the ‘container’ section remembers the settings once you select a container. Or, an alert would be nice so that you understand that your settings haven't been copied over.

Thanks! Feel free to close this as it's not really a bug, just unexpected behavior. @dmourati not sure if this sheds any light on your problem, but I hope so.

**Comment by ryan-mf** [comment]
To add more data to this ticket, I just found similar to what @emjburns said. Specifically, when I tell Spinnaker to copy an existing "cluster" (Kube deployment service) as a template, if it's not able to locate all of the tagged images the cluster is using in configured and cached dockerRegistry accounts, it wipes *all* user data for *all* containers during the copy - this includes envvars, volume mounts, liveness/readiness checks, etc. In my example case, I had:

Our application in one container of the pod/deployment which was using an image path:tag that Spinnaker was able to find in a known dockerRegistry account.
A second container in the pod/deployment which was using an image path:tag that Spinnaker was *unable* to locate in a known dockerRegistry account.
Our application's container def in the pod config has 99% of the envvar, volume mount, and health checks configs, and the other container, which we're sourcing anonymously from g.gcr.io as a public image, only had a couple values.
The result of the copy is that, because it can't locate the second container (because we hadn't added that public b.gcr.io path as a dockerRegistry account), it loses *all* envvars, volume mounts, health checks, etc during the copy, even though it was able to locate our own application container path:tag just fine.

This morning, I fixed the dockerRegistry account for the public repo path for b.gcr.io, and now it copies over all user data just fine when source from an existing cluster (deployment) as a template.

**Comment by ethanfrogers** [comment]
@emjburns @danielpeach and I worked through this issue today as I was running into it as well. There have been a couple PR's merged (and 2 in review) that should fix the issue.

The two outstanding PRs are:
- https://github.com/spinnaker/deck/pull/3612
- https://github.com/spinnaker/clouddriver/pull/1613/files

They specifically handle images without a registry for cases where you have preexisting K8S manifests with images like `nginx:latest`. The following 2 PRs might have already solved your issue. Try updating Deck and giving it a shot!

- https://github.com/spinnaker/deck/pull/3610
- https://github.com/spinnaker/deck/pull/3602

**Comment by ryan-mf** [comment]
Hey guys, I'm seeing very weird (and impacting) UI behavior now with my pipeline stages that involve deployment of a cluster (Kube replicaset/deployment). 

I'm currently on spinnaker 0.80.0 and spinnaker-clouddriver 1.611.0.

My deployments are suddenly missing either all of my per-container envvars, my per-container volume mounts, or both. Obviously this breaks our stack pretty badly. We have 60+ env vars that are needed by our application and a handful of mounts, so when they're missing, well, nothing works.

I noticed this first in my dockerRegistry -> Deploy to Dev pipeline, where it deploys a new "server group" (Kube replicaset) when clouddriver notices a new image tag. All of my defined container envvars and volume mounts in the deploy stage are wiped out. I then went to re-populate it in because I didn't know what happened, and opened my "deploy to stage" pipeline to get all of the values (it's parameterized based on secrets stored in the environment's Kube cluster), and that stage has all envvars but is missing all of the volume mounts.

Also, if I restart my stack outside of Spinnaker, then go into Spinnaker and try to configure the pipeline's deployment stage and tell it to copy from an existing cluster that I've verified has all of the envvars and volume mounts defined properly, they're all lost when it copies the existing cluster as a template source.

**Comment by ryan-mf** [comment]
@ethanfrogers told me yesterday that this was a known bug introduced the day before and had been fixed. I just had to wait for the updated Deck package (2.1090.0) to be available in the apt repo.

It popped in this morning and I immediately updated, and my issues are resolved. Thanks all!

**Comment by lwander** [comment]
Looks like this is resolved? Feel free to reopen if that's not the case.
