### ISSUE TITLE
[Kubernetes]: Add support for Labels on Server Groups

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#1624]
*Title*

[Kubernetes]: Add support for configurable Labels on Server Groups

*Cloud Provider*

Kubernetes

*Environment*

Kubernetes on AWS

*Feature Area*

Server Groups (Kubernetes)

*Description*

I'm not sure if this is something that has been decided against already and I searched but haven't found anything. It would be awesome to have support for custom labels on Server Groups, especially for users coming from an pre-existing K8S cluster. Most Deployments/ReplicaSets are already exposed with some set of labels and deploying a new ServerGroup does not get these labels which is prevent already existing Load Balancers (Services) from exposing the new Pods.

Where this really becomes an issue is Load Balancer services that are already service traffic for a specific DNS zone. You become forced to create a new Load Balancer and have to update the DNS entry.

*Steps to Reproduce*

1) Create a Deployment/ReplicaSet and Service that can expose it based on a set of non-Spinnaker related labels. (We're using `app: ourapp` and `server: web` on both the Deployment and Service)
2) Deploy a new version of that Application without updating anything.
3) Observe that the labels that previously matched for the Service no longer match.

**Comment by semyonslepov** [comment]
It should be great to have an ability to configure Labels on LoadBalancers as well.
For example, we're planning to start using Prometheus for scraping metrics from our services and target discovery is based on Service's labels (if you are using ServiceMonitor from Prometheus Operator). Now is seems that LoadBalancers, which were created by Spinnaker, have no labels at all.

**Comment by Z3r0Sum** [comment]
We had a very interesting migration path as a direct result of this... We essentially had two ReplicaSets running (one Spinnaker and one Non-Spinnaker) and then cut-over the service to match Spinnaker's "cluster" matchSelector label, since it most closely resembled our naming scheme.  We were also using `app` and I have a feeling a lot of individuals might be as it's in the K8s example documentation.

**Comment by BrianBerzins** [comment]
Another use case that we ran into: any kubernetes controller that uses label selection for pods cannot function without that ability to define custom labels.

**Comment by ethanfrogers** [comment]
@lwander I noticed you added the `beginner friendly` & `help wanted` tags here. Is this something that we want to start supporting? I remember you mentioned that it's kind of hairy mixing labels managed by Spinnaker and labels managed by users.

**Comment by lwander** [comment]
Oh - the labels for the server group aren't used by Spinnaker - the labels on the pods are. Those (at least for now) follow a specific scheme to make Deployment updates as well as Service enable/disables possible. If all that's required is supplying labels to the server group (replicaset, replicationcontroller) object, this is pretty straightforward.

**Comment by ethanfrogers** [comment]
I think the reason I filed this issue originally was around Pods. When you bring Spinnaker up against a cluster with pre-existing resources, new Pods under Server Groups don't match pre-existing Load Balancers so you have to create new Load Balancers in Spinnaker or manually update your Services to include the labels on the new Pods. Perhaps this issue should be re-filed/classified to reflect support for applying them just to the ReplicaSet/Controller. 

It should be noted that I filed this before I was _super_ familiar with the way Spinnaker does things :)

**Comment by BrianBerzins** [comment]
Perhaps I jumped in on this without full understanding... 
What I was was looking for is something very similar to the "Pod Annotations" except with Labels instead of annotations. Namely just "Pod Labels". It actually seems really odd to me that annotations were included but labels were excluded.

**Comment by ethanfrogers** [comment]
@BrianBerzins The reason Labels were excluded is because Spinnaker uses a specific set of Labels to do stuff like Enable/Disable (which pulls pods in and out of the Load Balancer). @lwander told me that managing user supplied Labels with Spinnaker managed Labels was a bit challenging.

**Comment by BrianBerzins** [comment]
@lwander Any chance I could get more info on why this would be challenging? Is it just the risk of conflicting labels? It's VERY easy to avoid reserved labels, but not having labels at all really messes with the ability to run custom controllers that use label selection.

**Comment by jakeegan10** [comment]
@ethanfrogers any thoughts on @BrianBerzins comment?

**Comment by ethanfrogers** [comment]
@jakeegan10 I don't. I have some guesses as to why it might have been avoided but don't want to speak for @lwander.

**Comment by lwander** [comment]
The concern isn't with adding labels we know will break things, but instead adding labels for Services that would break the semantics of a lot of Spinnaker's deployment strategies. Right now, Spinnaker knows if you intend to attach a Server Group to a Load Balancer by supplying its name in the deployment description - if you add a label to a ReplicaSet for a Service that doesn't exist yet (no way to verify), you could break your deployments because Spinnaker won't know how to unassociate your pods from that unknown Service. 

The long term fix is likely something like annotating pods at runtime with any services they are attached to, and then use that info during a red/black, highlander, rolling red/black, etc... to correctly do a disable. This isn't a large amount of work but will take careful thinking through the consequences/configurable behavior to make it work correctly. For example, not everyone will want the new Spinnaker model to take control of all pod <-> service relationships. Furthermore, this has eventual consistency concerns as well since the k8s API is only eventually consistent, and there is also no way to guarantee atomic updates to all desired pods at once - these are two sources of potentially ugly data races that leave pods serving traffic that shouldn't be.

The short term fix I'm not opposed to would be to open up the ability to add custom pod labels, but heavily decorate this with warnings about attaching pods to services.

**Comment by ethanfrogers** [comment]
what he said ^^ ;)

**Comment by BrianBerzins** [comment]
I've been going back and forth with people considering about whether or not my use cases make reasonable sense. I think that we can reasonable do without the ability to add labels for the time being.

Has there been any thought to using domain-prefixed names for the labels that spinnaker uses? e.g. `spinnaker.io/<label>: <value>`. If we took this approach, it seems like it should be safe to use any user supplied labels that do not start with your prefix (perhaps filter as a validation step?). 

Maybe I'm still missing another piece?
Thoughts?

**Comment by mdirkse** [comment]
@semyonslepov the patch was just merged for labels on load balancer: https://github.com/spinnaker/spinnaker/issues/2035

**Comment by serialx** [comment]
We use k8s labels as our backbone of logging infrastructure. (eg. App: email-service, Role: mysql, Env: prod, etc) As we were migrating our k8s deployments using Spinnaker we've ran into this problem.

I think using domain-prefixed names would be a good solution. Any progress on this issue?

**Comment by lwander** [comment]
It's resolved in the v2 provider (alpha release this week). Check the spinnaker.io page for docs & guides when spinnaker 1.6. is out.

**Comment by lwander** [comment]
Made obsolete by v2
