### ISSUE TITLE
AWS instance health check can never report healthy

### ISSUE THREAD

**Issue by dgreene-r7** [spinnaker/spinnaker#1977]
See https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/InstanceCachingAgent.groovy#L195

Even if the EC2 health check reports an instance is up, `getAmazonHealth` will still return a `Map` where the state is `Unknown`. This is concerning for applications that keep hot spare instances and use ELB health checks to determine which instance is the primary node (see [HashiCorp Vault's method](https://www.vaultproject.io/api/system/health.html#standbycode) for putting a node into standby) or applications that don't use an ELB at all.

In Vault's case, Spinnaker will never see a standby node as healthy even if the EC2 instance health check returns `HealthState.Up`.

The result is that pipelines will never complete and instances never show as healthy.

**Comment by cfieber** [comment]
This is intentional - the EC2 instance healthcheck doesn't give you an indicator that you have functional code on your instance, just that you have a running instance.

There is an option in application configuration 'consider only platform health' that will allow this unknown state to be considered acceptable for a deployment to proceed:

![screenshot from 2017-09-20 11-08-55](https://user-images.githubusercontent.com/301292/30659916-22b56e84-9df4-11e7-9171-46b01d19d66b.png)

**Comment by dgreene-r7** [comment]
That checkbox doesn't actually do anything, though. Pipelines still run forever or, in Vault's case, fail because the ELB health check is considered more precedent than the instance health check.

**Comment by dgreene-r7** [comment]
I should add that the other checkbox doesn't seem to do anything either. During a pipeline run there's no option to override instance health anywhere.
