### ISSUE TITLE
Cannot install spinnaker using halyard

### ISSUE THREAD

**Issue by kiril-dayradzhiev** [spinnaker/spinnaker#2007]
*Cannot install spinnaker using halyard following you documentation -> https://www.spinnaker.io/setup/*

Cloud provider: *Openstack*

Environment: *debianlocal*

Storage: *Redis*

Description:
I cannot install Spinnaker using halyard on Ubuntu 17.04, Ubuntu 16.04 and on Mac OS.
Ubuntu 17.04 issue: E: Unable to locate package spinnaker-igor
root cause: Failed to fetch https://dl.bintray.com/spinnaker-releases/debians/dists/zesty/spinnaker/binary-amd64/Packages

Ubuntu 16.04 issue: E: Unable to locate package spinnaker-igor
root cause: Failed to fetch https://dl.bintray.com/spinnaker-releases/debians/dists/xenial/spinnaker/binary-amd64/Packages

Mac OS - you are claiming that halyard and spinnaker supports it, but during the installation of spinnaker using halyard this is what I got:
sudo hal deploy apply
Password:

Get current deployment
Success
^ Apply deployment
. Apply deployment
Apply deployment
Apply deployment
Success
Run hal deploy connect to connect to Spinnaker.
Not a supported operating system: Darwin
It's recommended you use Ubuntu 14.04 or higher

Also your troubleshooting link is broken -> http://www.spinnaker.io/docs/troubleshooting-guide

**Comment by kiril-dayradzhiev** [comment]
It was also tested with Ubuntu 15.04(vivid), still not working. 
It works only with Ubuntu 14.04(trusty). Requirements message could be changed from "It's recommended you use Ubuntu 14.04 or higher" to "It's recommended you use only Ubuntu 14.04".

**Comment by nikhilninawe** [comment]
@kiril-dayradzhiev : Are you able to solve this issue on mac?

**Comment by kiril-dayradzhiev** [comment]
Nope, and I didn’t try since the comment was posted.

**Comment by fr34k8** [comment]
dudes.. problem resides in /etc/apt/sources.list.d/halyard.list there is no release candidate for 17.xx or 15.xx ..

below could work or the installer needs to be changed.. https://raw.githubusercontent.com/spinnaker/halyard/master/install/debian/InstallHalyard.sh

`
/etc/apt/sources.list.d/halyard.list

deb https://dl.bintray.com/spinnaker-releases/debians xenial spinnaker
`

`
sudo dpkg -i spinnaker_0.82.0_all.deb
`

`
sudo apt --fix-broken install
`

**Comment by fr34k8** [comment]
@lwander is there a chance to get a working `InstallSpinnaker.sh` script to 16.04 ? 

`sudo /opt/spinnaker_upstream/InstallSpinnaker.sh
Not a supported version of Ubuntu
Version is 16.04 we require 14.04.x LT`

**Comment by lwander** [comment]
Unfortunately we stopped supporting that script a while ago (a little over a year). Where did you find a copy?

**Comment by fr34k8** [comment]
@lwander it's in the upstream repo root, as you can see in my tree.. please remove that if not supported! 

btw, as discussed here:
https://github.com/spinnaker/spinnaker/issues/1544

there are few install scripts for halyard!
this one:  `https://raw.githubusercontent.com/spinnaker/halyard/master/install/stable/InstallHalyard.sh`

which does not work afterwards because of the incomplete `/lib/systemd/system/halyard.service`

`halyard.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.`
inside the Debian package 

and this one:
`https://raw.githubusercontent.com/spinnaker/halyard/master/install/debian/InstallHalyard.sh`

which does not get `spinnaker` deb package and `spinnaker-halyard` package.. 

is there any consistent and reproducible way to get halyard to work ? 
my favorite would be to use the Debian packages from 
`https://dl.bintray.com/spinnaker-releases/debians/dists/`

oh and btw why is the following mirror still existent ? 
`https://dl.bintray.com/spinnaker/debians/dists/` 

I thought, last mirror would be the mirror of choice, but my team mate told me about the first mirror .. its confusing..

**Comment by lwander** [comment]
That's embarrasing -- thanks! https://github.com/spinnaker/spinnaker/pull/3084

I recommend going with:

> "debian/ ubuntu":
> https://raw.githubusercontent.com/spinnaker/halyard/master/install/debian/InstallHalyard.sh

> which does not get spinnaker deb package and spinnaker-halyard package..

It only fetches a JAR, puts in in your /opt directory, and writes a wrapper script when to start the daemon if it's not already running with calling `hal`.

**Comment by fr34k8** [comment]
@lwander that's cool 4 now! 😎 

could you tell us which wrapper it writes and where ?

**Comment by lwander** [comment]
It writes to /usr/local/bin/hal the contents of https://github.com/spinnaker/halyard/blob/master/startup/debian/hal
