### ISSUE TITLE
Cant access Spinnaker dashboard in 1.6.0

### ISSUE THREAD

**Issue by sunlove123** [spinnaker/spinnaker#2465]
An issue is not a place to ask questions. Please use [Slack](http://join.spinnaker.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/spinnaker). 

Before you open an issue, please check if a similar issue already exists or has been closed before.

Make sure you have followed the steps of the [Troubleshooting Guide](http://www.spinnaker.io/docs/troubleshooting-guide) to provide as much information as possible. 

Please provide:

*Title*

Cant access Spinnaker dashboard in 1.6.0

*Cloud Provider*

Not a cloud provider. Tried in Ubuntu 16.04 in desktop version.

*Environment*

Spinnaker with Kubernetes and Redis

*Feature Area*

UI

*Description*

After installing spinnaker 1.6.0 in Ubuntu 16.04, it installed all the dependencies and gets success with "hal deploy apply". Then I use "hal deploy connect" to make UI available as local host. After that when I hit on "curl localhost:9000" it gives the result "curl: (56) Recv failure: Connection reset by peer". Can you please help me to resolve this issue!!!!

*Steps to Reproduce*

General Steps for installation in Ubuntu 16.04

*Additional Details*

Additional information such as screenshots and exception logs.
![port 9000](https://user-images.githubusercontent.com/25791116/36655019-37eb9502-1ae6-11e8-9ee7-4caffcfffaf7.JPG)
![spinnaker ui](https://user-images.githubusercontent.com/25791116/36655020-383419bc-1ae6-11e8-9bb2-088e9dffb858.JPG)

**Comment by sbwsg** [comment]
Hey @sunlove123, `halyard deploy connect` doesn't do anything because you are running a local deployment.  The issue appears to be that some process has already taken port 9000 and therefore deck is unable to start.

Can you let me know the following:

1. Is yours a LocalGit, LocalDebian, or Docker deployment of Spinnaker?
2. What is the output of `docker ps`?

Please try stopping any process that is currently using port 9000 and run `hal deploy apply --service-names deck`.  After a few minutes re-attempt `curl localhost:9000`.

**Comment by sbwsg** [comment]
Closing this issue since it appears to be that the port is already taken by another process and doesn't seem to be spinnaker-specific.

**Comment by amitmindstix** [comment]
https://www.spinnaker.io/docs/troubleshooting-guide link result in 404
