### ISSUE TITLE
Produces Artifacts fails without Default

### ISSUE THREAD

**Issue by hodgesmr** [spinnaker/spinnaker#2469]
If I configure **Produces Artifacts** in a pipeline stage without checking and providing _Use Default Artifact_, the stage consistently fails to locate an artifact in GCS:

>**Exception ( Bind Produced Artifacts )**
>Unmatched expected artifact ExpectedArtifact(matchArtifact=Artifact(type=gcs/object, name=gs://my-bucket/path/matt_test_8.yaml, version=null, location=null, reference=null, metadata=null, artifactAccount=null, provenance=null, uuid=null), usePriorArtifact=false, useDefaultArtifact=false, defaultArtifact=Artifact(type=gcs/object, name=gs://my-bucket/path/matt_test_8.yaml, version=null, location=null, reference=gs://my-bucket/path/matt_test_8.yaml, metadata=null, artifactAccount=null, provenance=null, uuid=null), id=6db16b35-5b82-4442-a1a2-7a121ba0c6a3, boundArtifact=null) could not be resolved.

However, if I configure it with a Default Artifact and simply provide the same expression, it succeeds:

<img width="737" alt="screen shot 2018-02-26 at 2 25 22 pm" src="https://user-images.githubusercontent.com/1208575/36696485-8de35164-1b01-11e8-8ba3-a6ab505f2d9f.png">

**Comment by lwander** [comment]
This might be correct - does the stage emit that artifact into the stage outputs? If not, there is no way for the artifact to be matched. I'm guessing this is using the "RunJob" stage, which does not natively emit artifacts into the stage context.

**Comment by hodgesmr** [comment]
Yep, this is from a Run Job. So should I simply continue to put the expression in both fields?

**Comment by lwander** [comment]
Yup - or just leave the top artifact "unmatchable" so you always use the default artifact. I think some sort of "unmatchable" artifact kind for the match artifact would be helpful here, WDYT?

**Comment by Rigdon** [comment]
Thanks @lwander. I think in this case we expected the "produces artifact" section to inject it into the stage outputs. If that's not the case and we can use expressions in the default artifact then that would be fine. If that's the case then explicitly marking the artifact as unmatchable seems like a good idea.

**Comment by lwander** [comment]
That makes sense - the "produces artifact" does inject it, but only once the artifact is actually bound. Since the "run job" stage doesn't emit any artifacts, the "match artifact" in the expected artifact you declared doesn't have anything to bind to. Other stages (webhook/runjob) do actually emit an artifact that the "match artifact" can bind to. For example, when you deploy a manifest, the output kubernetes/object artifact type is emitted into the stage context.

Good point on making that the default here - I'm going to close this and file issues to make this clearer.
