### ISSUE TITLE
GCP: Orca-Clouddriver FindImage From Tags Timeout 

### ISSUE THREAD

**Issue by sweetib** [spinnaker/spinnaker#2585]
**Title**
Find Image From Tag Stage times out after 10 mins.

**Cloud Provider**
GCP

**Environment**
OS: Ubuntu Xenial 16.04
Version of Spinnaker sub-services used:
```
spinnaker                        0.83.0        
spinnaker-clouddriver            1.773.0       
spinnaker-deck                   2.1182.0     
spinnaker-echo                   1.543.0      
spinnaker-fiat                   0.39.0       
spinnaker-front50                1.120.0      
spinnaker-gate                   4.21.2   
spinnaker-igor                   1.87.7       
spinnaker-keel                   0.8.0        
spinnaker-monitoring-daemon      0.6.0        
spinnaker-monitoring-third-party 0.6.0
spinnaker-orca                   6.0.0        
spinnaker-quip                   0.52.0-3     
spinnaker-rosco                  0.103.0      
spinnaker-rush                   1.25.0-3
```

**Feature Area**
Spinnaker Orca and Clouddriver

**Description**
We have around 3000+ images in our build image project and we have 25+ gcp project integrated in Clouddriver. Under Find Image from Tags Configuration we have specified `package` as `${ trigger.properties['image_name'] }`

**Error in Find Image from Tag Stage**

```
Exception:
FindImageFromTagsTask of stage Image Location timed out after 10 minutes. pausedDuration: 0 seconds, throttleTime: 0 seconds, elapsedTime: 10 minutes,timeoutValue: 10 minutes
```

Is there a way to increase the findImage time out or better way to configure clouddriver/orca? Looking forward for fix for this issue.

**Comment by lwander** [comment]
Which registry do you use, GCR? Was this ever working? I think this stage wasn't ever implemented for registries other than ECR

**Comment by sweetib** [comment]
@lwander This is on GCE

**Comment by lwander** [comment]
Which registry are you using, and has this worked before?

**Comment by sweetib** [comment]
It works perfectly fine when we have less number of images in our image project. As soon as image count increases timeout error starts happening.

**Comment by lwander** [comment]
Ah for some reason I thought you were using Kubernetes with this stage -- sorry!

So this is using regular GCE VM images, deploying VMs using the google provider?

**Comment by ezimanyi** [comment]
Spent some time today working with @sweetib to understand the issue.

I tried editing the code to artificially return ~3000 images from the cache (by editing `GoogleNamedImageLookupController.groovy`) but saw no appreciable slowdown in lookup of images.  (The stage still took 1-2s.)   This leads me to suspect that the post-processing of images after we get them from the cache is not the issue, but that actually querying for the images in the cache may be the issue.

I spent some time looking at the code to grab images from the cache.  I don't have a full understanding yet, but I suspect this may be an issue where the code is `O(N * M^2)` where `N` is the number of images and `M` is the number of projects.  It looks like what's happening is:
-For each account, we're looking up the names for all images in the cache (including those in the `baseProject`); this leads to returning `O(N*M)` image names (ie, `N` base images repeated `M` times each, once per project)
-We also end up with `M` relationships in the cache (one per Google account); in addition to querying the key for each image, we also query an additional key per relationship.  So we end up querying the redis cache for `O(N*M^2)` keys.

I'm still figuring out exactly how cache relationships work, and if it makes sense that we need to query so many keys from the cache---but as an order of magnitude, with 25 projects and 3000 images in the base project, we'd be querying ~2 million keys in the cache.  With 25 projects (well, actually the same project configured 25 times) and 95 images, I was able to slow the image query down to ~12 seconds---so it's not hard to see how this could approach 10 minutes if we linearly scale up to ~3000 images.

It looks like there are some inefficiencies here than can be cleaned up, but I need to make sure I understand what the code is doing better before I'm fully sure.

**Comment by ezimanyi** [comment]
After profiling more closely today, I discovered a few more things:
-There is a 20s timeout for the Orca -> Clouddriver call; after that time, Orca will give up on the outstanding request to Clouddriver.  It will then re-send the request, which will probably also time out, and re-try sending requests until the 10 min Orca timeout.  I believe it's most likely that we're hitting this timeout, rather than directly hitting the 10 min Orca timeout.
-While it is inefficient to ask the redis cache for `O(N*M^2)` items, I actually think upon further profiling that it's the post-processing of the items returned from the cache that is the bottleneck here.

There are two things that we can do here (in order of how much I think they will help):
(1) Deduplicate the images across accounts, so that images in the base account only get processed once and not once per configured GCP account.  In this case of ~25 GCP accounts, this should reduce the clouddriver call time by a factor of ~25.
(2) Update the logic querying items from the cache to no longer look for relationships (which are not needed in this case), which would reduce the number of items returned from `O(N*M^2)` to `O(N*M)`.  This doesn't seem to be the bottleneck now, but is still a reasonable optimization.

**Comment by sweetib** [comment]
@ezimanyi Thanks for the update.  For now the only way forward for us is the first approach you stated. But still wanted to know, Is there any ETA that we can expect on when we can have the optimisation done?

**Comment by ezimanyi** [comment]
@sweetib : I'm looking now at seeing whether I can get solution (1) above implemented in the next few days.  (Of course it would not show up in an official Spinnaker release until some time later.)

Basically, this would make Spinnaker more intelligently handle the case that you're experiencing---rather than continuously processing the same images when you have multiple accounts configured, it would only process each image once.  This should significantly speed up image search, enough to stop this stage from timing out for you.

**Comment by sweetib** [comment]
Thanks a lot @ezimanyi. Will be waiting for the fix to be rolled out :) 👍

**Comment by ezimanyi** [comment]
Status on this:
* I've done some more detailed profiling and for parameters similar to this bug report (~3000 base images and ~25 projects) the change merged in https://github.com/spinnaker/clouddriver/pull/2502 should increase the image fetch time by a factor of ~4-5x.  (From ~15s to ~3s)
* I've made a second pull request https://github.com/spinnaker/clouddriver/pull/2513 to do some further optimization on that code; my profiling shows this should gain an additional ~5-10% speedup.

The net total is that these two changes should speed up "Find Image By Tags" under these conditions by ~5x; so lookups with ~3000 images should be no problem (but things might start to time out again around ~15000 images).

For now I think these improvements should be sufficient to solve the issue here, though just for reference there are a few further improvements that I would consider next steps that I'll put in another comment.

**Comment by ezimanyi** [comment]
Notes from my investigation:
* It's pretty inefficient that `/gce/images/find` returns every base image for every account, rather than just returning each base image once along with an array of accounts that have access.  Changing this, however, would change the contract of that endpoint...deck in particular expects this particular response and would need to be changed to handle the new format.
* I did look into whether we should just cache the base images a single time (rather than once per account), but unless we make the change in the above point it's not saving us much/any time as we'd still need to cross base images with accounts in Java before sending the response.

Idea for next steps (if necessary):
* Update the `/gce/images/find` endpoint (or add a new one so we're backwards-compatible) that returns each image a single time along with a set of accounts that have access.  As a first step, we could deduplicate images when fetching from the cache, but ideally we'd also change the caching structure to only cache each image once (rather than once per account).

As noted above, though, I think that the 5x improvement already attained with the existing PRs should be sufficient and this idea is more a note for future work if we run into scaling problems with this feature in the future.

**Comment by skim1420** [comment]
FYI, [this improvement](https://github.com/spinnaker/clouddriver/commit/acdb6b6e7ad49ad949bfdd1470cfa5f50b4b1378) was released as a part of the [1.7 release](https://www.spinnaker.io/community/releases/versions/1-7-0-changelog). @sweetib, can you please verify whether this has helped your situation?

**Comment by sweetib** [comment]
@skim1420 and @ezimanyi we have deployed `1.7.2` into our setup yesterday itself, as we have already cleanup lots of images in past week before the update was done. We are yet to reach the state where we might start seeing the significant difference. For now time for image search is between `0.01` and `0.02` in comparison to our old timings which was between `0.06` and `0.10` for image count less than 1K. For now everything looks good so far 👍 . We have stop cleaning our images and letting them pile up to see when hits the bottleneck again. We will keep you updated. Thanks

**Comment by skim1420** [comment]
Closing for now, please let us know if you experience further issues. Thanks.

**Comment by clanesf** [comment]
I wanted to chime in because we seem to be experiencing something similar. We have 20 GCP accounts registered with 1500 images and we are routinely seeing timeouts from the `/gce/images/find` route, resulting in failed pipelines. 

Is there any way to increase the timeout of the calls between orca->clouddriver through the yaml configuration files?
