### ISSUE TITLE
Igor fails to become healthy with K8s V2 Provider

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#2688]
Seems to be returning a 503

```
$ kubectl exec -it spin-igor-589db64748-7z6cl --namespace spinnaker -- bash
bash-4.4$ 
bash-4.4$ 
bash-4.4$ wget localhost:8088/health
Connecting to localhost:8088 (127.0.0.1:8088)
wget: server returned error: HTTP/1.1 503 
```

cc @lwander @sbwsg

**Comment by brunsgaard** [comment]
Which image of igor do your deployment use? I have seen the same issue, but not with newer versions of hal 1.1.0. Also if you are running an old version of hal, please update hal and `hal deploy apply` again.

It is worth to note that that even if the health check fail it works fine (at least if it is the same thing I was seeing before version 0.49.0.

**Comment by lwander** [comment]
The root of the issue is that Igor (in the default deployment) has no trigger sources to poll unless you enable Jenkins, Travis CI, or a Docker registry. W/o those Igor has no work to do, and comes up as unhealthy. Halyard should just be smart enough to know that it doesn't have to deploy Igor in that case.
