### ISSUE TITLE
Halyard installation ends with "bash: /usr/local/bin/hal: Permission denied"

### ISSUE THREAD

**Issue by usrleon** [spinnaker/spinnaker#2904]
## Issue Summary:
Follow this guide: https://www.spinnaker.io/setup/install/halyard/#install-on-ubuntu-14041604
After you run "sudo bash InstallHalyard.sh"
at the last stage you get an error "bash: /usr/local/bin/hal: Permission denied"
Thats because access rights on this file lack of x for others and it doesn't belong to any real users:
-rwxr-xr-- 1 2038 2038 1380 May  9 15:35 /usr/local/bin/hal

**Comment by ezimanyi** [comment]
Looks like there are a few things going on here:
* `InstallHalyard.sh` does do `chmod +x /usr/local/bin/hal`; when not specifying whether the operation affects user/group/others/all, the default for `chmod` is to apply the permission to all users *except* that it will ignore any bits set in the `umask`.  My guess here is that you've got a non-standard `umask` that resulted in only the user execute bit being set.  I'm not sure we'd want to change this behavior, as someone with such a nonstandard `umask` likely wants file to be only executable by their owner unless specifically changed.
* The fact that `hal` is owned by a non-existent user is because `tar` by default preserves owner information when extracting as the root user, which does not make sense when the archive was created on another system with different users.  We should pass `----no-same-owner` to the `tar` command so that these files are owned by root.

**Comment by ezimanyi** [comment]
https://github.com/spinnaker/halyard/pull/971/

**Comment by usrleon** [comment]
You right umask is 0027 (I wasn't aware), but if owner will be correct the issue will never happen.
However why don't just set permissions as 0755?

**Comment by ezimanyi** [comment]
That seems reasonable---there are a few other places where we need to be more explicit about permissions to ensure that halyard works with a restrictive umask.  I've made those changes on https://github.com/spinnaker/halyard/pull/973/ and tested that it works with umask `027` without needing to take any manual steps.

`/usr/local/bin/hal` will be owned by root but will have `o+x` permissions so that other users can execute it.  (In general we're following the paradigm where root owns the binaries for haylard, and the account running halyard only has read+execute on these.)

**Comment by ezimanyi** [comment]
Addressed by https://github.com/spinnaker/halyard/pull/977
