### ISSUE TITLE
deploy stage will fail when application name contains - dashes

### ISSUE THREAD

**Issue by wuzhihui1123** [spinnaker/spinnaker#2946]
### Issue Summary:
if my application name contains ```-``` dashes,  when i execute pileline that has ```Deploy``` stage,  it will fail,  

 - **if my app name is ```fs-bfm-biz```,  will shown below**  

![image](https://user-images.githubusercontent.com/4246626/41838496-2472e420-7893-11e8-88cd-2f6270f0ca1d.png)

- **if my all name is ```fsbfmbiz```, will shown below**   
![image](https://user-images.githubusercontent.com/4246626/41838965-7a7baa7c-7894-11e8-92a3-5d633b1eadf6.png)

### Cloud Provider(s):
     kubernetes 1.10.0

### Environment:
   Spinnaker Version: 1.8.0
   Kubernetes Version: 1.10.0

### Additional Details:

---

**Comment by brandonnelson3** [comment]
This is expected behavior assuming you are using the kubernetes v1 provider. The issue is actually with the application name here not the cluster name, if you look at the error it says "deployKubernetesAtomicOperationDescription.application is invalid". The v2 provider removes this restriction. I would suggest you to try out the v2 provider if you want these hyphens in your application name. 

If you happen to not actually be using the v1 provider please let me know as I have clearly misdiagnosed this issue.

**Comment by wuzhihui1123** [comment]
@brandonnelson3  yes, i use v1 provider.  i will try v2 provider, thank
