### ISSUE TITLE
Feature Request: Service Now Trigger

### ISSUE THREAD

**Issue by mnalsup** [spinnaker/spinnaker#3115]
### Issue Summary:
I would like to propose and contribute a feature to have spinnaker pipelines trigger off of Service-Now changes. 

### Feature Area: 
Triggers

### Description:
I would like to be able to specify a serviceNow instance (probably via a preconfigured service now in a profile with an account linked) and an identifier for a Change in Service-Now. I plan to have Echo monitor events based off of the approval status and time window of a change. Igor will be in charge of polling and generating these events. And then a simple UI piece along with the other triggers. It will have a service account attached in a similar fashion as Jenkins integration.

**Comment by ezimanyi** [comment]
Do you think this is something that could be achieved by using the Spinnaker Webhook trigger type, and having Service Now send a webhook upon the appropriate events?

In general, there's some interest in trying to move more integrations to Webhooks rather than adding to Igor---as we try to support more and more integrations, adding these all individually to Igor won't scale well.  If there are reasons why this would not work with a webhook, I'd be interested in discussing them to see if we can close those gaps.

**Comment by mnalsup** [comment]
Yes, it probably can be accomplished using webhooks. Looking at Igor I could see how another monitor would be cumbersome. The main goal was ease of use and a lower bar of entry into using Spinnaker at my workplace. I'll try to get something together externally for the time being. Thanks for the feedback!

**Comment by sbwsg** [comment]
I'm going to close this issue out in favor of the webhook approach then. @mnalsup Feel free to re-open if you reach a point where you believe the feature can only be implemented with a new trigger type.
