### ISSUE TITLE
Deck errors out on Create New Server Group

### ISSUE THREAD

**Issue by edwinavalos** [spinnaker/spinnaker#3224]
### Issue Summary:
On latest unvalidated version, and in 1.9.0 I click to open a Create Server Group dialogue for the AWS provider and I am met with errors in the Chrome console, and the Create Server Group dialogue never completely opens.

### Cloud Provider(s):
provider/aws, k8s is the only other one I can check and it is fine.

### Environment:
Seen in two envs:
Running halyard latest unvalidated on EKS
Running halyard v1.9.0 on EKS

### Feature Area: 
Deck's create server dialogue from the Servers view, works fine when creating a server group in a pipeline

### Description:
Error log at the bottom

### Steps to Reproduce:
1. Launch spinnaker in browser with AWS provider configured
2. Create a new app
3. Navigate to cluster tab view under infrastructure
4. Click Create Server Group, dialogue never finishes loading and closes out.

### Additional Details:

```
react-dom.production.min.js:151 TypeError: Cannot read property 'map' of undefined
    at new ServerGroupBasicSettingsImpl (ServerGroupBasicSettings.tsx:59)
    at constructClassInstance (react-dom.production.min.js:111)
    at beginWork (react-dom.production.min.js:138)
    at e (react-dom.production.min.js:176)
    at f (react-dom.production.min.js:176)
    at G (react-dom.production.min.js:182)
    at x (react-dom.production.min.js:181)
    at n (react-dom.production.min.js:181)
    at B (react-dom.production.min.js:180)
    at v (react-dom.production.min.js:179)
cf @ react-dom.production.min.js:151
commitErrorLogging @ react-dom.production.min.js:161
R @ react-dom.production.min.js:185
G @ react-dom.production.min.js:182
x @ react-dom.production.min.js:181
n @ react-dom.production.min.js:181
B @ react-dom.production.min.js:180
v @ react-dom.production.min.js:179
enqueueSetState @ react-dom.production.min.js:110
push.E.setState @ react.production.min.js:12
reactShims_1.AwsReactInjector.awsServerGroupConfigurationService.configureCommand.then @ AmazonCloneServerGroupModal.tsx:165
processQueue @ angular.js:16832
(anonymous) @ angular.js:16876
$digest @ angular.js:17971
$apply @ angular.js:18269
done @ angular.js:12387
completeRequest @ angular.js:12613
requestLoaded @ angular.js:12541
load (async)
(anonymous) @ angular.js:12524
sendReq @ angular.js:12332
serverRequest @ angular.js:12084
processQueue @ angular.js:16832
(anonymous) @ angular.js:16876
$digest @ angular.js:17971
(anonymous) @ angular.js:18200
completeOutstandingRequest @ angular.js:6274
(anonymous) @ angular.js:6554
setTimeout (async)
Browser.self.defer @ angular.js:6552
$evalAsync @ angular.js:18198
(anonymous) @ angular.js:16704
scheduleProcessQueue @ angular.js:16876
$$resolve @ angular.js:16903
doResolve @ angular.js:16912
Promise.then (async)
$$resolve @ angular.js:16899
resolvePromise @ angular.js:16887
when @ angular.js:17032
listAllAccounts @ AccountService.ts:176
getAllAccountDetailsForProvider @ AccountService.ts:116
selectSkin @ skinSelection.service.ts:14
(anonymous) @ allClusters.controller.js:107
processQueue @ angular.js:16832
(anonymous) @ angular.js:16876
$digest @ angular.js:17971
$apply @ angular.js:18269
(anonymous) @ angular.js:26999
dispatch @ jquery.js:5183
elemData.handle @ jquery.js:4991
angular.js:14525 TypeError: Cannot read property 'map' of undefined
    at new ServerGroupBasicSettingsImpl (ServerGroupBasicSettings.tsx:59)
    at constructClassInstance (react-dom.production.min.js:111)
    at beginWork (react-dom.production.min.js:138)
    at e (react-dom.production.min.js:176)
    at f (react-dom.production.min.js:176)
    at G (react-dom.production.min.js:182)
    at x (react-dom.production.min.js:181)
    at n (react-dom.production.min.js:181)
    at B (react-dom.production.min.js:180)
    at v (react-dom.production.min.js:179) "Possibly unhandled rejection: {}"
```

**Comment by slupers** [comment]
We also noticed an issue with creating/modifying server groups for apps. We can't create/edit server groups even in the Deploy stages of pipelines. The dialogue to create/edit comes up but we can never save the server group (for existing and new pipelines) because Spinnaker thinks the 'Basic Settings' section is not filled out, saying "Image required." when hovering over the Basic Settings section. Not sure what image it is talking about. There's no such field in the GUI and don't see one in the JSON either.

The cloud provider is also AWS, Spinnaker 1.9.0 installed via hal. The versions of various Spinnaker components are: 

ii  spinnaker-clouddriver            3.4.0-20180814155153                       all          spinnaker-clouddriver
ii  spinnaker-deck                   2.4.0-20180814164527                       all          spinnaker-deck
ii  spinnaker-echo                   2.0.0-20180807022809                       all          spinnaker-echo
ii  spinnaker-front50                0.12.0-20180802022808                      all          spinnaker-front50
ii  spinnaker-gate                   1.1.0-20180803022808                       all          spinnaker-gate
ii  spinnaker-igor                   0.12.0-20180726022808                      all          spinnaker-igor
ii  spinnaker-kayenta                0.3.0-20180724022806                       all          spinnaker-kayenta
ii  spinnaker-monitoring-daemon      0.8.0-20180803022808                       all          spinnaker-monitoring-daemon
ii  spinnaker-orca                   1.0.0-20180814155153                       all          spinnaker-orca
ii  spinnaker-rosco                  0.7.2-20180706145819                       all          spinnaker-rosco

**Comment by sbwsg** [comment]
Tagging @jrsquared here since the aws ServerGroupBasicSettings.tsx is from a recent react rewrite.

**Comment by edwinavalos** [comment]
I think he might be our best bet on this issue, I'm massively out of my depth on web development :)

**Comment by costimuraru** [comment]
We're having a related issue after upgrading to Spinnaker 1.9.0

Getting the following UI error - we have both AWS and Kubernetes providers, but only AWS is used for this app.

<img width="813" alt="screenshot 2018-08-23 18 53 56" src="https://user-images.githubusercontent.com/952836/44537108-a97d3e80-a706-11e8-8ba5-7f5ca5a39956.png">

**Comment by slupers** [comment]
@costimuraru that's exactly what we're seeing, too

**Comment by edwinavalos** [comment]
1.9.3 removed this specific issue.
