### ISSUE TITLE
Orca acquires unfair lock when multi orca instances poll message from redis Queue

### ISSUE THREAD

**Issue by lord-i-will** [spinnaker/spinnaker#3275]
### Issue Summary:
IM in charge of ORCA's performance optimization.
Now orca polls message every 10ms, when orca is deployed in multi instances, one or two orca instances are very busy, but others are very freeeee.,...How do u solve this "unfair lock" problem to give full play to all these orca instances?

### Cloud Provider(s):
kubernetes

### Environment:
services:
  clouddriver:
    version: 0.5.0-72
    commit: 2855e9941a97b1c3897ee8378e001ad546d5b715
  orca:
    version: 0.5.0-72
    commit: d6f3ad00845d539c404d6a7fabcf8511fcb468e7

### Feature Area: 
RedisQueue, Message Polling

### Steps to Reproduce:
Deploy multi orca instances.
Push 1000 messages to redis-queue.
Watch orca log.

### Additional Details:

---

**Comment by robzienert** [comment]
The version of Spinnaker you're running is **super old** and there's been quite a lot of changes from the Orca of over a year ago and today, especially around the work queue and its performance characteristics.

One such change was rewriting the lock behavior to [read multiple messages off the queue until it can acquire a lock](https://github.com/spinnaker/keiko/blob/master/keiko-redis/src/main/kotlin/com/netflix/spinnaker/q/redis/RedisQueue.kt#L502-L503). This will help solve the fairness problem when there's actually multiple ready messages to be processed.

Here's a snapshot of one of our worker pools:

<img width="1135" alt="screen shot 2018-08-29 at 10 29 35 pm" src="https://user-images.githubusercontent.com/108741/44831386-29aa1500-abdb-11e8-9d1f-a365d3d8dae2.png">

There are indeed hotspots, which I can attribute to two things:

1. The "hot" nodes are ones that share the same AZ as the Redis instance, so they'll be more likely to acquire.
1. We run a setting [`fillExecutorEachCycle `](https://github.com/spinnaker/keiko/blob/master/keiko-spring/src/main/kotlin/com/netflix/spinnaker/config/QueueProperties.kt#L27) which will make unfairness even more pronounced (and is a setting we use in production). This setting optimizes Orca to process messages as quickly as possible under heavy load rather than processing messages fairly, as we're mostly concerned about not having a backlog of `ready` messages. `fillExecutorEachCycle` is disabled by default.

I'd be interested to see what you're seeing after upgrading to something more recent. If there's still issues, you can increase the delay between poll cycles, although I wouldn't recommend anything higher than 50ms.

**Comment by robzienert** [comment]
Closing. Feel free to reopen after upgrading and if you're continuing to experience problems.

**Comment by lord-i-will** [comment]
@robzienert 
very thx...u r so nice and has showed me so many details, i will check it out.
The reason why im not ready to upgrade is that i made some performance optimization and these changes are difficult to merge and pull request because the OLD VERSION problem.
For example, look at the following two code pieces:
![image](https://user-images.githubusercontent.com/14847104/44834955-2bb8b600-ac65-11e8-852e-6a6f2e4311d9.png)
![image](https://user-images.githubusercontent.com/14847104/44835004-573ba080-ac65-11e8-8704-3ad82c56c1e0.png)
Every time task message was polled and handled, it will load the total Execution object to memory. This has no problems when pipeline stages are little, but when one pipeline has 500, 1000 stages, and every stage has 10~20 tasks, this "total load execution" behavior will always leads to OOM. Every 10ms the message is polled and the "total load execution" occurs, the GC will be busssssy.......

**Comment by robzienert** [comment]
I'll take a look at this in more detail in the morning. 1000s of stages in a single pipeline is quite extreme (would love more context about your use cases there?). That's good info, we know orca is inefficient with data loading, but haven't had the chance to fix it yet.

I'd encourage you still to try to upgrade, and stay up to date, becsuse you obviously have the desire and capability of improving Spinnaker -- would love to see you upstreaming fixes and moving the whole community forward! :)
