### ISSUE TITLE
Content-type check in Deck ApiService.getData should log and/or provide failure message

### ISSUE THREAD

**Issue by eaceaser** [spinnaker/spinnaker#3277]
### Issue Summary:
The content-type check in the `getData` method is coarse and brittle: https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/api/ApiService.ts#L30-L38 

If this check fails, API request promises will fail with no logging or debug information whatsoever. This makes it extremely difficult to figure out what the root cause of the issue is. Furthermore, the error displayed to the user if the request fails is also devoid of information.

### Cloud Provider(s):
Any

### Environment:
* Spinnaker 1.9.2 and below

### Feature Area: 
* UI

### Description:
I don't really know what the rationale for this check is. In a perfect world Gate wouldn't be returning `200`s with no body and no content-type for some of its API endpoints -- it should actually return some content for all endpoints, or it should returning `204`s, and the content-type would be ignored in that case because there is no content. However, that is a bigger fix. If I had to guess, I'd imagine that this check is there to identify the "correct" no-content `200`s vs ones that indicate a failure. Maybe someone can provide some context on this check?

So where this ends up being a problem is in the situation where spinnaker is fronted by another reverse proxy. In the case of `nginx`, there's some very common config snippets that end up being used that include `default_type application/octet-stream`. This causes a problem for Spinnaker, because Deck is expecting that API requests to gate w/ no response body either not have a content type, or have a content type set to `application/json`, `text/html`, or `text/plain`. Since Deck doesn't set a content type for some of its API endpoints, any reverse proxy that has a default content type set has the chance to set it to something that will break this check.  

Although this comes up due to the interaction between Spinnaker and an external proxy, when this content-type check does fail it is extremely difficult to diagnose what is going on. Most of the time this will result in a spurious error message being displayed to the user, because the underlying API request ends up succeeding anyways. But since there is no logging and no error message, it's very difficult to figure out why these requests are succeeding, but the promises are silently failing.

### Steps to Reproduce:
* Front gate with an nginx reverse proxy with a configuration that sets `default_type application/octet-stream`.
* Attempt to perform an API operation that expects an empty response.

### Additional Details:
Here's what the user sees in this scenario when trying to update a pipeline: 
![2018-08-30_17-37](https://user-images.githubusercontent.com/157866/44886530-8f4dde00-ac7b-11e8-8f50-6974d61953e0.png)

and when trying to create a pipeline:

![2018-08-30_17-38](https://user-images.githubusercontent.com/157866/44886532-9379fb80-ac7b-11e8-84bc-41e34dfd2bcf.png)

**Comment by sbwsg** [comment]
Thanks for the issue report; I went back a ways in the git history for ApiService.ts and then api.service.ts to see if I could answer any of your questions but it looks like the function you're discussing here has been around for a while with most changes due to refactors. I lost the trail when a refactoring happened in 2016 and I guess the function was split, renamed, or merged into a single module. There isn't much discussion of the whys or hows for the service in the log output. I expect this is an artifact of a workaround to deal with unpleasant server responses but I don't know which server or why it needed working around.

I'll create a PR to log when this happens. At the very least it should more quickly direct users to a file & line number in the code when they're debugging.
