### ISSUE TITLE
Kayenta: Add NewRelic Insights connector as METRIC_STORE

### ISSUE THREAD

**Issue by MichaelManz** [spinnaker/spinnaker#3464]
### Issue Summary:
To be able to leverage [NewRelic (Insights)](https://newrelic.com/products/insights) for automated canary analysis we would like to contribute a NewRelic connector for Kayenta. A first version is already finished and is used on our Spinnaker deployment.

### Feature Area: 
Kayenta

### Description:
To be able to leverage [NewRelic (Insights)](https://newrelic.com/products/insights) for automated canary analysis we implemented a METRIC_STORE that calls the NewRelic Insights REST Api to pull configured metrics. These metrics could be e.g.: response time, error rates, Apdex. 

The reason why we use the Insights Api is that only with Insights it is possible to query specific build versions of a service. This is the recommended way by the NewRelic support.

### Additional Details:
Note that this contribution is not connected to the commercially available version of the NewRelic connector at https://docs.armory.io/admin-guides/kayenta/

For an example canary config + adhoc request for NewRelic could look like this:
```
{
  "canaryConfig": {
    "name": "MySampleNewrelicCanaryConfig",
    "description": "Example Kayenta Configuration using Newrelic",
    "configVersion": "1.0",
    "applications": [
      "kayentatest"
    ],
    "judge": {
      "name": "NetflixACAJudge-v1.0",
      "judgeConfigurations": { }
    },
    "metrics": [
      {
        "name": "Error Rate",
        "query": {
          "type": "newrelic",
          "select": "percentage(count(*), WHERE httpResponseCode >= '500')"
        },
        "groups": ["err"],
        "analysisConfigurations": { },
        "scopeName": "default"
      },
      {
        "name": "Response time",
        "query": {
          "type": "newrelic",
          "select": "average(totalTime*1000)"
        },
        "groups": ["app"],
        "analysisConfigurations": { },
        "scopeName": "default"
      }
    ],
    "classifier": {
      "groupWeights": {
        "err": 70.0,
        "app": 30.0
      }
    }
  },
  "executionRequest": {
    "scopes": {
      "default": {
        "controlScope": {
          "type": "node",
          "scope": "appName = 'myapp - prod' and deployment_version = '1234'",
          "start": "1537783860000",
          "end": "1537785660000",
          "step": "10"
        },
        "experimentScope": {
          "type": "node",
          "scope": "appName = 'myapp - prod' and deployment_version = '5678'",
          "start": "1537783860000",
          "end": "1537785660000",
          "step": "10"
        }
      }
    },
    "thresholds": {
      "pass": 95.0,
      "marginal": 75.0
    }

  }
}
```
And example Kayenta Configuration for NewRelic could look like this:
```
kayenta:
  newrelic:
    enabled: true
    accounts:
      - name: NewRelic
        apiKey: "01234567890abcdef"
        accountId: 12345678
        supportedTypes:
          - METRICS_STORE
        endpoint:
           baseUrl:  https://insights-api.newrelic.com
```

**Comment by ehmke** [comment]
Example PR: https://github.com/spinnaker/kayenta/pull/412

**Comment by duftler** [comment]
Any particular reason the linked pr is marked as an 'example'? Is it not ready for review?

Took a quick look, and it looks promising.

I would have expected the class names to use `NewRelic...` instead of `Newrelic...`, but I lack insight into how it's normally referred to, so maybe that's the norm.

Also think I noticed some 4-space indentation in there; we've been using 2-space indentation. When in doubt, just take a look at some neighboring files to see what they look like and try to be similar.

Lastly, please take a look at the recently-added `MetricsService.buildQuery`: https://github.com/spinnaker/kayenta/pull/405/files#diff-3e903177bee256d49d2404ef93065d80R70 (you'll see similar recent PR's for the other integrations as well)

While not strictly required, if you move your query composition logic into that method, you'll be all set to take advantage of the soon-to-be improved editing experience (we want to make it possible from the Spinnaker Canary Config UI to see expanded queries without having to wire up and execute full pipelines).

Please let us know when you're ready to have your PR reviewed.

Thanks for the contribution.

**Comment by duftler** [comment]
Btw, the dryRun bit works from the api/swagger as well.

**Comment by MichaelManz** [comment]
Oh, because the contribution guidelines say something about discussing a "design doc" first before starting the implementation. But great, if the change looks generally fine we will integrate your feedback and prep a review-ready version.

**Comment by duftler** [comment]
Good point about the design doc. In the case of adding additional metric service integrations to Kayenta, there is a fairly well-paved road to follow, and the changes are well contained, so I don't think it's necessary (unless there was some significant deviation from what other contributors have done).

**Comment by duftler** [comment]
If New Relic supports querying for active metrics, could also add the support for type-ahead of metric names: https://github.com/spinnaker/kayenta/pull/406

**Comment by MichaelManz** [comment]
Done
