### ISSUE TITLE
no session affinity option for GCP Network LB

### ISSUE THREAD

**Issue by BIGPHATTOBY** [spinnaker/spinnaker#3521]
### Issue Summary:
session affinity feature is not present when creating a network load-balancer with gcp provider.

### Cloud Provider(s):
Google Cloud Provider

### Environment:
Version 1.10 hosted on Kubernetes
Configured providers:
GCE, Azure, Kubernetes

### Steps to Reproduce:
Create application, select GCE as provider, create load balancer, type: Network

### Additional Details:
As per official documentation and testing via API the above should be possible from googles side, to which I don't know if this is not implemented or if the option not showing up is a bug.
source: https://cloud.google.com/load-balancing/docs/network/#session-affinity

**Comment by aleksandrov** [comment]
@spinnakerbot remove-label stale

This is still valid question for us.

**Comment by lwander** [comment]
@jtk54 can provide some insight

**Comment by jtk54** [comment]
This should be pretty manageable if one of you would like to contribute, would one of you care to take a shot at it?

Essentially all that is required is to add the session affinity to the target pool following the pattern [here](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/ops/loadbalancer/UpsertGoogleLoadBalancerAtomicOperation.groovy#L130).

[Example PR adding for L7](https://github.com/spinnaker/clouddriver/pull/1054).

The other requirement would be to add the corresponding frontend change in the network LB wizard similarly to [the L7 session affinity](https://github.com/spinnaker/deck/blob/0e984db58d5d41ca67f7b8ca98d6972977a021d2/app/scripts/modules/google/src/loadBalancer/configure/http/backendService/backendService.component.html#L90), though belonging to the target pool instead of the backend service.

Willing to help and give more pointers if one of you decides to contribute.

**Comment by aleksandrov** [comment]
will look what I can do (next Friday)

**Comment by jtk54** [comment]
It's this one: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleLoadBalancerAtomicOperationConverter.groovy. Network was the first one we added so the names are a bit confusing.

**Comment by aleksandrov** [comment]
@jtk54 This is still not a full PR, but I need you suggesstion.  https://github.com/aleksandrov/clouddriver/commit/cea1e0a13ebaab1c500e6bccda700015897894b0 adds support of Session Affinity for new Target Pool, but updating existing one looks cumbersome - looks like I need to recreate whole target pool (Google REST API does not have methods to modify Session Affinity).  Is it OK or maybe I overlooked something?

**Comment by jtk54** [comment]
It does appear that the only way to update the target pool is to destroy and recreate it with the new attributes. It seems like there would necessarily be downtime in serving traffic if there were any attached instances. Perhaps we should disallow this while there are instances load balanced by the target pool?

**Comment by aleksandrov** [comment]
Ok, thanks for information. As far as I see I need to implement following to have consistent UI:

1. Modificate Clouddriver API GET /applications/{application}/loadBalancers to return Session Affinity information (no Session Affinity information in thre response at the moment).
1. Make "Session Affinity" drop-down read-only when editing LB with existing instances.

Also `UpsertGoogleLoadBalancerAtomicOperation` should re-create Target Pool with new Session Affinity if there are no instances in it. 

@jtk54 Am I on right way?

**Comment by jtk54** [comment]
Yes, that sounds like the right direction.

For (1), this should be a simple change to the Google LB caching agent. For (2), consider also checking and explicitly failing in Clouddriver if a request tries to change session affinity while there are connected instances. Thanks for tackling this.
