### ISSUE TITLE
ECS scaling policies don't work after first deployment

### ISSUE THREAD

**Issue by clareliguori** [spinnaker/spinnaker#3733]
In attempting to fix #3184, I discovered that scaling policies won't be copied to the newly deployed ECS service starting with the second deployment in a pipeline after configuring autoscaling policies for the server group.

### Steps to Reproduce:

1. Deploy an ECS server group in Spinnaker, which will create ECS service "v0001".
1. Manually attach a scaling policy to the ECS service "v0001" outside of Spinnaker, for example step scaling on ECS service CPU utilization.  This creates a "v0001-policy" scaling policy and a "v0001-cpu" alarm on the v0001 service CPU metrics, with the alarm action targeting the v0001 scaling policy.
1. In Spinnaker, add the "v0001-cpu" alarm to the server group "autoscaling policies" configuration.  Start a deployment.  Spinnaker creates a new ECS service "v0002".
1. During the deployment, Spinnaker fetches the current action associated with the v0001-cpu alarm, which is currently "v0001-policy".  It copies that policy to a new policy "v0002-policy", and creates a new v0002-cpu alarm targeting v0002-policy (#3184 references the fact that this new v0002-cpu alarm still uses the v0001 service metrics for its thresholds).
1. As part of scaling down v0001 service, Spinnaker deregisters v0001 service as a scalable target, which deletes v0001-policy.  After this, v0001-alarm has no associated actions.
1. After the first deployment completes, start a second deployment.  Spinnaker creates v0003 service.
1. During the deployment, Spinnaker fetches the current action associated with the v0001-cpu alarm, because that alarm is in the server group configuration (not v0002-cpu alarm).  This alarm no longer has actions associated with it, because v0001 service was deregistered as a scalable target.
1. Spinnaker creates v0003-cpu alarm, but the v0003 service will not have any scaling policies and v0003-cpu alarm will not have any associated actions.

**Comment by clareliguori** [comment]
cc @dkirillov and @BrunoCarrier I'm curious if you see the same behavior, or if you have a workaround?

**Comment by anotherchrisberry** [comment]
If I'm reading this correctly, the AWS provider tracks more closely with what's described in **Option 2**. 

On any deployment, unless the user explicitly sets a `copySourceScalingPoliciesAndActions` flag to `false`, Clouddriver will always [copy over scheduled actions and scaling policies](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy#L421) from the ancestor ASG. The new [alarm](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/scalingpolicy/DefaultScalingPolicyCopier.groovy#L154) and [policy](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/scalingpolicy/DefaultScalingPolicyCopier.groovy#L67) names are autogenerated based on the new server group name.

I'm not sure what's being done right now to determine the "previous" service, but, in the scenario you describe above, it sounds like Clouddriver does know what it is, since it's setting the version of the new service to `v0003`.

**Option 1** seems not great for the reasons you've called out. Handling rollbacks could be very tricky, too.

Does **Option 3** mean no automatic copying of policies by Spinnaker? Right now, there is no way to configure AWS scaling policies as part of a pipeline (unless that changed in the past six months and I missed it). Are ECS policies configurable via pipelines?

We haven't provided any way to define scaling policies in pipeline cluster configuration for AWS, since you typically want a live service to understand how to set up scaling policies for it.

(Sorry if this comment is just noise and not helpful)

**Comment by clareliguori** [comment]
This is helpful, thanks @anotherchrisberry!

re: Option 3, I might have misinterpreted how [UpsertScalingPolicyAtomicOperation](https://github.com/spinnaker/clouddriver/blob/29c5c1435ab0c750c4b491208f600647a3e98901/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/UpsertScalingPolicyAtomicOperation.groovy) is used (I am not super familar with the AWS provider), will that run in a pipeline or is it only used in creating/updating the server group outside of a pipeline?

**Comment by anotherchrisberry** [comment]
UpsertScalingPolicyAtomicOperation _could_ run in a pipeline, but there is no UI built for it - it's only used in creating/updating the server group outside of a pipeline.

**Comment by clareliguori** [comment]
Got it, agreed then, Option 2 is the best option here

**Comment by vide** [comment]
Sorry for bringing up an old issue but I don't see Option 2 as being actually used by Spinnaker (I'm using 1.17.1).
Basically what I want to achieve is having everything defined as code and since Spinnaker pipelines + spin don't support setting the ASG rule, I use good ol' Terraaform to set this on one pristine ASG. But when a new ASG is created by Spinnaker during a deploy, it creates a brand new named rule, copying the same values as the old one. That breaks completely Terraform for me. Any idea @clareliguori  @anotherchrisberry  ? Should I open a new ticket?
