### ISSUE TITLE
Expected Artifacts aren't displayed when pipline is created by using pipeline.libsonnet

### ISSUE THREAD

**Issue by Mahito** [spinnaker/spinnaker#3740]
### Issue Summary:

Expected Artifacts aren't displayed when pipline is created by using pipeline.libsonnet

### Cloud Provider(s):

kubernetes

### Environment:
I am running Spinnaker v1.11.0 on GKE

### Feature Area: 

pipeline.libsonnet

### Description:

I expected that the pipeline was made correctly, but expected Artifacts aren't displayed when pipline is created by using pipeline.libsonnet.

### Steps to Reproduce:

See Sponnet demo 
https://github.com/spinnaker/spinnaker/blob/master/sponnet/demo/README.md

1. `git clone https://github.com/spinnaker/spinnaker.git`
2. `cd spinnaker/sponnet/demo`
3. To install jsonnet
3. To build the demo application
`jsonnet demo-app.jsonnet > demo-app.json && spin application save --file demo-app.json`
4. To build the demo pipeline
`jsonnet demo-pipeline.jsonnet > demo-pipeline.json && spin pipeline save --file demo-pipeline.json`
5. Go to pipeline page on Deck

### Additional Details:

<img width="595" alt="2018-12-17 17 24 08" src="https://user-images.githubusercontent.com/210692/50075066-35205b00-0221-11e9-824a-9fa47b686581.png">

**Comment by kskewes** [comment]
The `kind` attribute was removed from sponnet here: https://github.com/spinnaker/spinnaker/pull/3472/commits/73e3a6e6683fe129261c854c2c42cf6208f703b7

`kind` is not required to save pipelines or for pipelines to correctly operate so I think the idea is that Deck should infer kind and present appropriately (see referenced Deck PR in above sponnet PR).
For now, as you discovered Deck does still need `kind` for presenting the artifacts correctly.
So I agree that `kind` is useful and have been maintaining the kind patch from my PR above in our local version of sponnet. 

I wonder if I we should add it back in, either with your PR or mine. Or there is something else we can do with Deck to complete the empty boxes.
@lwander thoughts?

**Comment by lwander** [comment]
I think when discussed, we figured this is best handled in Deck, rather than require all other clients to meet Deck's requirements. @sbwsg how feasible is it to remove the requirement to have (or infer) `kind`?

**Comment by sbwsg** [comment]
Deck is correctly inferring the type and displaying the edit UI for it. Notice that Deck shows the docker image inputs and the git file inputs, and they're populated with values from the sponnet file.

I don't think anything is broken though someone please correct me if that's wrong. I assume that the actual issue here is those red outlines on the form fields?

Correcting those is surprisingly awkward because of they way they're hooked up to the pipeline model via angular's two-way data binding. I had a go at fixing that before settling on https://github.com/spinnaker/deck/pull/5879 as a "good-enough" solution. Fixing those red outlines means either:

1. Migrating the data inside Deck to backfill the kind field. This results in an odd UX where the pipeline data is updated by simply opening the pipeline, prompting the user to save despite them not having modified anything.

2. Rewriting `core/pipeline/config/triggers/artifacts/artifact.component.ts` to no longer use two-way data binding. This is a surprisingly non-trivial thing to do but I'd love to see someone contribute it.

**Comment by kskewes** [comment]
Yes just a display issue from memory. @Mahito?
Bummer about changes required, don't think I'm the right person for that one.
Thanks for details.

**Comment by lwander** [comment]
Yeah -- based on that I'd say maybe pipeline.libsonnet is the right place to host these requirements, at least for now :)

**Comment by Mahito** [comment]
Thank you for replies.
I understood the reason of this issue and I agree to correspond at pipeline.libsonnet.
