### ISSUE TITLE
Does spinnaker support pub/sub as trigger in version release-1.7.x ?

### ISSUE THREAD

**Issue by tingzhang-ming** [spinnaker/spinnaker#3759]

**Comment by lwander** [comment]
It looks like the pubsub trigger type was made available before that release: https://github.com/spinnaker/deck/commit/b04f25fd5040cfa875bd32d4ee9e622625caeef0#diff-7a96434a7dcdc316a33ad4a5b0323f64, but a number of fixes/improvements have been made to that trigger type since 1.7 (released about 9 months ago), which won't necessarily be in release-1.7.x.
