### ISSUE TITLE
Add instructions on how to limit custom metrics sent to Datadog

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#3868]
### Issue Summary:

By default - when Datadog-monitoring for Spinnaker is enabled (in a distributed setup) - a huge number of custom metrics is sent to Datadog.

### Cloud Provider(s):

Any.

### Environment:

Spinnaker version 1.10.1 running on GKE in GCP - but probably applies any Spinnaker version - at least in distributed setup (maybe others too?).

### Feature Area: 

Monitoring

### Description:

I'd expect some documentation on limiting what to send to Datadog - otherwise your Datadog invoice can be a crazy lot.

### Steps to Reproduce:

1. install Spinnaker using the distributed setup
2. enable Spinnaker's Datadog monitor

### Additional Details:

I'd recommend adding instructions on how to filter what to send in here:

https://www.spinnaker.io/setup/monitoring/datadog/

I got the instructions in Slack once but ofc forgot them. :)

**Comment by ewiseblatt** [comment]
The current production way is documented here: https://www.spinnaker.io/setup/monitoring/#configuring-metric-filters

However I am proposing moving in a new direction, which is proposed here:
https://docs.google.com/document/d/1iuhO4HEVkKsKyhb-EKGxYziTNcb2ZZBhCZINLaQCQnk
with support in a github branch in my repo for the time being. My branch is just configuration files and dashboards all of which work with the off the shelf 1.11 release. I did not construct datadog dashboards so you would just need the metrics specification file https://github.com/ewiseblatt/spinnaker-monitoring/blob/experimental_transform/spinnaker-monitoring-daemon/experimental/metric_filters/default.yml, which you would give to halyard the same was as the old-style filtering documented in spinnaker.github.io reference above, and also add to spinnaker-monitoring-local.yml an entry:
   spectator:
       inject_service_tag: true

The inject_service_tag completeness the new metrics by adding a tag "spin_service" to each metric, rather than creating service-specific metrics. This can significantly cut down on the number of metrics you need (but not necessarily time series streams) on top of filtering.

Also, FYI you might want to add
   datadog:
      use_types: true
which was a fix in 1.11 so that counter metrics are reported as counters. Previously this was not provided so datadog treated everything as a gauge.


My suggestion to you is to use the metric filtering in the short term because it wont impact your operations (alerts and dashboards are the same because the metrics are the same) but please look at the new model and try it out if you can and provide feedback on it.

**Comment by iniinikoski** [comment]
@ewiseblatt huge thanks! I'll try all of these. Where should I define the ```use_types: true```? If I try to do that in Halyard - I get an error:

```halyard@halyard:~$ hal deploy apply
- Get current deployment
  Failure
Problems in Global:
! ERROR Could not translate your halconfig: Unrecognized field
  "use_types" (class
  com.netflix.spinnaker.halyard.config.model.v1.metricStores.datadog.DatadogStore),
  not marked as ignorable (4 known properties: "enabled", "api_key", "app_key",
  "tags"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["deploymentConfigurations"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["metricStores"]->com.netflix.spinnaker.halyard.config.model.v1.node.MetricStores["datadog"]->com.netflix.spinnaker.halyard.config.model.v1.metricStores.datadog.DatadogStore["use_types"])```

**Comment by ewiseblatt** [comment]
Ideally in spinnaker-monitoring-local.yml under "datadog"

datadog:
  use_types: true

However there was a bug in how spinnaker-monitoring-local.yml was resolved which I coincidentally fixed yesterday in master so that wont work in 1.12 unless you can put spinnaker-monitoring-local.yml in /opt/spinnaker-monitoring/config or /opt/spinnaker-monitoring (and spinnaker-monitoring.yml needs to be there too). Again, that is fixed in master if you want to try with that daemon.

I requested a cherry pick into 1.12 so we might be able to put a patch release out next week.

**Comment by iniinikoski** [comment]
Ok thanks for the update. I'll wait for the patch release.

@ewiseblatt you mentioned above that "I did not construct datadog dashboards so you would just need the metrics specification file" - does this mean I can use this same default.yml you've created...?

**Comment by iniinikoski** [comment]
Some updates here: good news - we number of custom metrics has dropped from about 30k to 2,5k - which is ok-ish! :) The bad news is - most of the Spinnaker dashboards have no data - so the filtering is too strong :D But - when I have time - I'll find out what's happening and I can submit a PR @ewiseblatt. IMO we can close the ticket - and your documentation is also superb - did not find anything to change at least yet.

**Comment by joaquinclearmetal** [comment]
I am running into this issue, that has broken installs through stable/spinnaker chart.  I cannot even `helm delete` because of this.
