### ISSUE TITLE
[Feature] New Stage Type "Check a Metric"

### ISSUE THREAD

**Issue by perek** [spinnaker/spinnaker#3910]
### Issue Summary:
Currently the only way to due a metric based test is via Kayenta. While Kayenta is great for monitoring the effect of a new change on your services internal metrics, it falls flat when considering SOA side effects. For instance your canary might look great internally but what happens if it breaks a wire protocol for one of the 100's of services that depend on your service. There is no way in Kayenta to model this properly as the failure metrics it might cause would bubble up in another applications metrics.

### Feature Area: 
Orca/Stages
Kayenta

### Description:
What I propose to fix this issue is a new stage type "Check a Metric". This stage would allow you to specify metric name(s) from known Kayenta sources and compare it using arithmetic operators to either a window or an absolute value. It would behave much like the webhook stage, it would be a simple pass or fail. Where it is unclear to me is if Kayenta can be harnessed to do the aggregation for us (i think it can)

Example config:
Metrics Sleep Time: 1m
Source: Graphite
Provider: my-graphite-server
Metrics to Check:
SUM servicea.errors.500s < 100
AND
SUM serviceb.errors.500s < 200
AND
AVG api.errors.500s < 5

**Comment by duftler** [comment]
@ezimanyi and I chatted about this a bit and it seems like a reasonable proposal.

Based on the issue summary, one implementation option would be to support this type of analysis directly within Kayenta itself. That is, allow for a canary analysis that takes just one scope and a canary config that has an alternative scoring scheme.

There have been quite a few conversations around generalizing Kayenta to be more of a general-purpose analysis engine and not apply it just to the canary problem space. It seems logical since it already knows how to query multiple telemetry stores using templated configs.

Getting back to your proposed approach, I think what would be required is:
1) Support for defining canary configs that do not have a scoring section (in the kayenta canary config model and in the ui).
2) A new entry point (i.e. controller) on kayenta that would support a canary request that has only one scope (that is, instead of control & experiment scopes, just one 'subject' scope). It would return (I think) metric set lists.
3) The new orca stage you described. A proper ui wouldn't need to be developed yet as the pipeline editor will render an 'unrecognized' stage with a text box containing the stage json.

I don't see any reason why we couldn't also start by doing this with your suggested approach and then eventually add more first-class support directly into kayenta if there is demand.

The work would be fairly straightforward and in keeping with the intent of kayenta, so I don't see any real issues.

If one were to try to exploit the new entry-point to, say, populate health in a dashboard or something like that, then I would see real issues.

@skandragon @csanden What do you guys think?

**Comment by perek** [comment]
@duftler I am going to take a stab at this, this week. 

![bitmoji](https://render.bitstrips.com/v2/cpanel/d3d1b666-e8c2-4e7a-9009-b64d665f96f4-df97c301-c0c5-46c6-88f9-ef3baa0669d0-v1.png?transparent=1&palette=1&width=246)

**Comment by plumpy** [comment]
This RFC is very old. The old RFC process has been superseded by a new one. If you still care about this RFC and would like feedback, please move it over to [the new RFC process](https://www.spinnaker.io/community/contributing/submitting/#before-you-begin). Thanks.
