### ISSUE TITLE
Jenkins Git Plugin not returning hudson.plugins.git.util.BuildData anymore

### ISSUE THREAD

**Issue by ismailsalloo** [spinnaker/spinnaker#3927]
The latest version of the [Jenkins git-plugin](https://github.com/jenkinsci/git-plugin) has updated the way Git Build Data is displayed in the XML API of a build. A new [BuildDetails](https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/hudson/plugins/git/util/BuildDetails.java) model is now being used instead of the [BuildData](https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/hudson/plugins/git/util/BuildData.java) model previously used. The repercussions of this change causes the Spinnaker Igor to not provide the SCM info of a Jenkins Build (that is using GIT). We unfortunately require the SHA1 id to be passed into downstream pipelines which unfortunately fails.

**Comment by dorbin** [comment]
Transferring this issue to spinnaker/spinnaker. If it turns out to be a doc issue, or solvable solely through docs, feel free to transfer it back.

**Comment by ismailsalloo** [comment]
> Transferring this issue to spinnaker/spinnaker. If it turns out to be a doc issue, or solvable solely through docs, feel free to transfer it back.

Sorry @dorbin, my bad. Thought I was in the correct repo

**Comment by dorbin** [comment]
@ismailsalloo , no problem! Cheers

**Comment by ezimanyi** [comment]
@ismailsalloo : Currently the fix is only in the master branch; I was waiting to see if there would be any changes on the jenkins-git plugin side before pulling it into the 1.12 branch (and releasing it in 1.12.2).

It looks like what actually happened is jenkins-git [accidentally pushed](https://issues.jenkins-ci.org/browse/JENKINS-55939?focusedCommentId=359885&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-359885) 4.0.0-rc as a stable release; they didn't actually intend to release the change removing `BuildDetails` to the stable channel.

As this change is still in an alpha release on the jenkins-git side, and there are a number of issues open against it in the `jenkins-git` JIRA project, I'm reluctant to pull our change into the stable 1.12.x branch for now in case there are further changes we need to react to.

My suggestion for anyone running into this would be to roll back the "Git plugin" and "Git client" plugin back to stable versions on your Jenkins installation.  (They have fixed the issue pushing the release candidate to the sable branch, so once you downgrade, you won't get prompted to upgrade to the release candidate again.)

I'll leave this change in our master branch for now, and will follow the changes on the Jenkins side as they work through the open bugs on their release candidate.  If they do push the change to stable, I'll release patch releases to the recent Spinnaker releases so Spinnaker works with it.

**Comment by ismailsalloo** [comment]
> @ismailsalloo : Currently the fix is only in the master branch; I was waiting to see if there would be any changes on the jenkins-git plugin side before pulling it into the 1.12 branch (and releasing it in 1.12.2).
> 
> It looks like what actually happened is jenkins-git [accidentally pushed](https://issues.jenkins-ci.org/browse/JENKINS-55939?focusedCommentId=359885&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-359885) 4.0.0-rc as a stable release; they didn't actually intend to release the change removing `BuildDetails` to the stable channel.
> 
> As this change is still in an alpha release on the jenkins-git side, and there are a number of issues open against it in the `jenkins-git` JIRA project, I'm reluctant to pull our change into the stable 1.12.x branch for now in case there are further changes we need to react to.
> 
> My suggestion for anyone running into this would be to roll back the "Git plugin" and "Git client" plugin back to stable versions on your Jenkins installation. (They have fixed the issue pushing the release candidate to the sable branch, so once you downgrade, you won't get prompted to upgrade to the release candidate again.)
> 
> I'll leave this change in our master branch for now, and will follow the changes on the Jenkins side as they work through the open bugs on their release candidate. If they do push the change to stable, I'll release patch releases to the recent Spinnaker releases so Spinnaker works with it.

@ezimanyi, thanks for the reply, it makes perfect sense.
