### ISSUE TITLE
CF - investigate possible case sensitive issue when deploying an application

### ISSUE THREAD

**Issue by Jammy-Louie** [spinnaker/spinnaker#3974]
### Issue Summary:
There has been reports that pipeline stages fail to deploy SG when org and spaces contain uppercase characters in CF.

### Cloud Provider(s):
CF

### Environment:
Deck, Clouddriver

### Steps to Reproduce:
1. Create an org and space with mixed case
1. Create a Deploy pipeline to the new org and space
1. Check if success or failure

**Comment by Jammy-Louie** [comment]
@spinnakerbot add-label provider/cf

**Comment by jmelchio** [comment]
After investigation we found that this issue is caused by the fact that there is a difference in how Spinnaker and CF treat case names of Orgs and Spaces:

* For CF case of names is insignificant so to the Foundation `some-org` is equivalent to `SOME-ORG`
* Foundations do not change the case of Org or Space names when storing the Org and Space information
* When querying the Foundation it will return the names as they are stored
* When Spinnaker caches objects the region names that are used as a key ie. `org-name > space-NAME` will have the same case as stored in the CF Foundation
* When doing lookups in the Spinnaker cache these lookups are case sensitive so looking up `org-name > space-name` is will not return something that is stored as `ORG-NAME > SPACE-NAME`
* When creating pipelines in raw JSON it is possible to enter the names of Orgs and Spaces in a different case than they are stored in the CF Foundation
* When these names with different case are used in the pipeline any required lookups in the cache will fail resulting in pipeline stage failures or timeouts; we have seen concrete examples of this with `Deploy Server Group` not being able to verify instances are up and running

At this point we are leaning towards a solution that involves improving the validation of the pipeline on the server side so that we prevent storing pipeline configurations that mismatch the case of the names of orgs and spaces.

**Comment by jmelchio** [comment]
Investigation result is that we open a new issue to enhance validation on the back-end: #4015
