### ISSUE TITLE
ECS Proposal: Retrieve task definition from artifact

### ISSUE THREAD

**Issue by clareliguori** [spinnaker/spinnaker#4070]
### Problem:

The ECS provider currently [models individual attributes](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/description/CreateServerGroupDescription.java) of the [ECS task definition format](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html), like container image, cpu, and memory, and exposes them as server group configuration in Deck.  It models a small percentage (~25%) of the ~100 possible attributes of the task definition.  There are multiple issues open now to support more task definition attributes, like https://github.com/spinnaker/spinnaker/issues/4018, https://github.com/spinnaker/spinnaker/issues/3341, and https://github.com/spinnaker/spinnaker/issues/3340.  Modeling all of the task definition attributes in Spinnaker would lead to a very complex configuration UI, and would always be behind as ECS continues to add new features to the task definition format.

### Proposed Solution:

I propose adding support in the ECS provider for storing the task definition contents as a JSON file Spinnaker artifact, for example in a git repository.

The JSON file format will match the request syntax of the [ECS RegisterTaskDefinition API](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RegisterTaskDefinition.html).  The ECS provider will download the artifact and parse/validate it using ObjectMapper and the [RegisterTaskDefinitionRequest class](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ecs/model/RegisterTaskDefinitionRequest.html) from the AWS Java SDK.  Then the task definition will be registered with ECS as it is today for the server group.

We will maintain support for the individual task def parameters currently modeled as server group attributes.  These can either be used standalone for an on-the-fly task definition (i.e. the current behavior), or be used as overrides for the artifact.  For example, overriding the Secret Manager secret used for registry credentials.  Overrides will be set on the parsed RegisterTaskDefinitionRequest object after parsing it from the task definition artifact contents.

This work will enable Spinnaker support for all current ECS task definition parameters, including those asked for in https://github.com/spinnaker/spinnaker/issues/4018, https://github.com/spinnaker/spinnaker/issues/3341, and https://github.com/spinnaker/spinnaker/issues/3340.  Supporting future task definition parameters when they are released becomes significantly easier.  It only requires [bumping the aws-java-sdk version](https://github.com/spinnaker/spinnaker-dependencies/blob/26c225f1791c217913415e077fecf597e3f0a961/src/spinnaker-dependencies.yml#L13) in spinnaker-dependencies and letting autobump happen in clouddriver.

### Out of Scope

This proposal doesn't address some of the Spinnaker gaps for configuring ECS service definition attributes, like placement constraints, service discovery, and daemon scheduling.  The list of missing service attributes is much smaller than the task def list, so I think it's more manageable to add support for configuring those attributes directly in Spinnaker.

**Comment by clareliguori** [comment]
@spinnakerbot add-label provider/ecs

**Comment by clareliguori** [comment]
@spinnakerbot add-label proposal

**Comment by ethanfrogers** [comment]
@spinnakerbot add-label no-lifecycle

**Comment by jkschneider** [comment]
If you want to support defining images as an input artifact as well, you'll want to add ECS as a provider to this new artifact type in Clouddriver so it shows up in Deck: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/docker/DockerArtifactConfiguration.java#L30

**Comment by ttomsu** [comment]
fyi/cc @ezimanyi

**Comment by allisaurus** [comment]
@ttomsu @jkschneider Here's an update on how we're thinking support for this may look. Please let us know if this would satisfy your use case(s) or if we missed anything!
(CC: @clareliguori )

# Proposed new workflow
Since we expect the task definition to be a JSON file, we can consume it from existing artifact types which provide files, such as Github files, Gitlab files, Bitbucket files, S3 objects, or HTTP files. Once the task definition is configured within one of these artifacts, it can be added to a pipeline as an expected artifact and provided as an input to the ECS Server Group at the “Deploy” stage.

## Configuration steps
1) A task definition JSON file in a Git repository is configured as an artifact (name: “myapp/taskdef.json”) within Spinnaker, and the repository is configured to update Spinnaker via webhook when updated.

2) “myapp/taskdef.json” is configured as an [Expected Artifact](https://www.spinnaker.io/reference/artifacts/in-pipelines/#expected-artifacts) within a pipeline. 

3) Add or update the ECS “Deploy” stage in the pipeline by selecting the expected 'Task Definition Source' (NEW FIELD) as “Artifact”, and selecting the previously configured “myapp/taskdef.json” artifact.

*Example UX (draft):*

![proposed_ui_2](https://user-images.githubusercontent.com/34254888/56912389-01bdca80-6a64-11e9-8354-9f4139b21362.png)


4) For each container in the task definition (artifact) you want to deploy to, enter the container name and select a docker image from within the pipeline that should be used (containers present in the task definition but not specified here will be registered as-is).

*Example UX (draft):*

![container selection](https://user-images.githubusercontent.com/34254888/56912404-0c785f80-6a64-11e9-94c6-da84230b4407.png)


5) (Optional) A subset of existing container/task definition fields would remain visible for each container to allow for server group-specific overrides. (*Aside from Environment Variables, what container-level settings make sense to allow overrides on?*)

## Triggering the pipeline
To kick off the pipeline on `taskdef.json` updates, add an automated trigger to the pipeline of type “Git” w/ the relevant repository configured.

## Task Definition registration & clean up
The ECS provider would continue to register a new task definition named after the server group on each deployment, and deregister it when the server group is destroyed. 

This maintains existing behavior and eliminates the risk of de-registering a task definition not created by Spinnaker (and which may be in use elsewhere). NOTE: This means any “family” value present in the task definition artifact would be overwritten before a new task definition is registered.

# Out of scope
The following items would be out of scope for initial artifact support but could be considered later depending on community needs.
1. Additional support for S3 Object & HTTP File pipeline triggers.
2. Specifying the task definition as static text directly in the ECS Server Group.

**Comment by jkschneider** [comment]
@allisaurus Looks great! Please note the new artifact UI which is currently hidden behind the `artifactsRewrite` feature flag in 1.13. In the screenshot below, you see two artifacts being bound. One is through selecting an expected artifact defined as a trigger artifact constraint or on a "Produces Artifact" on a prior stage. The other one is defined inline in this stage, potentially with the help of SpEL evaluation of the parts of the artifact definition:

![image](https://user-images.githubusercontent.com/1697736/56915066-3c7f2d00-6a7b-11e9-86a0-d3368735c76c.png)

You can also see that we've arrived at a similar conclusion, selecting direct input or an artifact via a radio button for our manifest selection use case.

At some point, users may ask for that JSON artifact to contain SpEL expressions so that the same artifact can be used in different environments with some stage evaluation context. Google ran into some trouble with this with k8s manifests that had text that was being accidentally evaluated because of the same delimiter `${}`, so have an option to either always evaluate or never evaluate for a particular manifest. For the Cloud Foundry provider, the subject of parameterizable manifests keeps coming up, so we may wind up doing some sort of "select the delimiter you want to use in the expression evaluation" configuration. Not sure yet.

**Comment by allisaurus** [comment]
@jkschneider thanks for the additional context! Sounds like if the artifact is already defined, then we could skip asking for an account. And good point re: anticipating how users may want to parameterize task defs - would the decision to "always" or "never" evaluate expressions in the artifact text be something we'd want to (eventually) set within the server group?

**Comment by kaitea** [comment]
Is there any ETA on when this will be released in production?

**Comment by allisaurus** [comment]
@kaitea Our goal is to have this included in the 1.15 release (Window [opens on 7/8](https://www.spinnaker.io/community/releases/release-cadence/#upcoming-release-windows)), however I'll leave it to a core maintainer to officially confirm/deny that :)

**Comment by ethanfrogers** [comment]
Yep, AFAIK we're still targeting 7/8 for the 1.15 release window!

**Comment by clareliguori** [comment]
These changes are now all merged, and will be included in the 1.15 release.
