### ISSUE TITLE
[GCE] Distributed instances are incorrectly assigned

### ISSUE THREAD

**Issue by seanpeters86** [spinnaker/spinnaker#4071]
### Issue Summary:
When creating a cluster, available zones are not shown as zones that will be deployed to if "Distribute instances across multiple zones" is selected. 

### Cloud Provider(s):
Google/GCE

### Environment:
Spinnaker 1.12.4 deployed with google providers.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
@spinnaker/ui-ux-team

### Description:
We have a project setup that has access to 4 particular zones in `us-central1`:

```
$ gcloud compute regions describe us-central1 --project=PROJECTNAME

zones:
- https://www.googleapis.com/compute/v1/projects/PROJECTNAME/zones/us-central1-a
- https://www.googleapis.com/compute/v1/projects/PROJECTNAME/zones/us-central1-b
- https://www.googleapis.com/compute/v1/projects/PROJECTNAME/zones/us-central1-c
- https://www.googleapis.com/compute/v1/projects/PROJECTNAME/zones/us-central1-f
```

This is confirmed via the cluster-creation screen within Spinnaker as well:
<img width="649" alt="screen shot 2019-03-05 at 12 47 08 pm" src="https://user-images.githubusercontent.com/10604059/53829297-746b6780-3f45-11e9-829e-0353f486540b.png">

However, if you select `Distribute instances across multiple zones` checkbox, it only displays b, c, and f zones:
<img width="646" alt="screen shot 2019-03-05 at 12 47 16 pm" src="https://user-images.githubusercontent.com/10604059/53829360-96fd8080-3f45-11e9-9aaa-e8bb445cff3b.png">

Even stranger, you are able to `Select zones explicitly` and input all 4 available zones:
<img width="649" alt="screen shot 2019-03-05 at 12 47 30 pm" src="https://user-images.githubusercontent.com/10604059/53829405-ada3d780-3f45-11e9-9d61-09f3f4be5081.png">

If you only select `Distribute instances across multiple zones` without manually inputting your zones, Spinnaker only deploys to zones b, c, and f and no instances will ever come up on a.

I can only confirm this with `us-central`, our other region we use...`us-east1` only has 3 available zones and does not showcase this problem.

### Steps to Reproduce:
1. Create a GCP Project connected to `us-central1` with 4 available zones
2. Create a cluster 
3. Deploy 4 instances with `Distribute instances across multiple zones` checked
4. Verify that you cannot see `us-central1-a` or that any instance will come up on `us-central1-a`
5. Create a 2nd cluster, this time with `Distribute instances across multiple zones` checked and `Select zones explicitly` where you select all 4 zones.
6. Verify that the 2nd cluster is created with all 4 zones this time.

### Additional Details:
First server group created with only `Distribute instances across multiple zones` checked
<img width="317" alt="screen shot 2019-03-05 at 1 02 27 pm" src="https://user-images.githubusercontent.com/10604059/53830011-1fc8ec00-3f47-11e9-8190-2a3ae58ef9c7.png">

Second server group created with both `Distribute instances across multiple zones` checked and `Select zones explicitly` checked with all 4 zones selected:
<img width="317" alt="screen shot 2019-03-05 at 1 03 12 pm" src="https://user-images.githubusercontent.com/10604059/53830054-38390680-3f47-11e9-86e7-84ecddd86aec.png">

Note: we had a report of this happening ~5 months ago when we were on version 1.8.X, so this has likely been around for quite some time.

**Comment by sbwsg** [comment]
The logic at the moment simply takes the 3 "right-most" entries in the array of available zones, hence central1-b, c, and f.  I'll update this so that it selects all of them by default.

**Comment by sbwsg** [comment]
This will be out in the next patch release of the 1.13 and 1.12 releases: 1.13.1 and 1.12.8.

**Comment by sbwsg** [comment]
1.12.8 has been released with this fix.

**Comment by seanpeters86** [comment]
@sbwsg just deployed with 1.13.1 and noticed that we are still not deploying to us-central1-a, the UI does show all four regions when I select the box in the cluster create screen, but only comes up in 3/4 zones.

**Comment by sbwsg** [comment]
So, taking a deeper look at this, when I create several regional Managed Instance Groups in GCP's UI instead of Spinnaker I get the exact same behaviour - the instances in my MIGs are always load balanced across -b, -c, and -f.  Also, [looking at the docs](https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups):

> For regions that contain more than three zones, the regional managed instance group will choose three zones to create instances in.

It appears that regional MIGs in us-central1 will always balance across -b, -c, and -f although I can't find any official GCP documentation this evening explicitly calling that particular behaviour out.

Given that Spinnaker is fronting GCP's APIs here, I'd argue that we were actually doing the right thing before I made my change - the user chooses to go with the platform's selection of zones and the platform is always choosing -b, -c, and -f. However if the user explicitly wants to override the platform's zone selection then they can manually add all 4 zones to the distribution policy as you indicated in your original issue report.

I think my next step will be to back-out my change for this and return the behaviour to the way it was.
