### ISSUE TITLE
Chaos Monkey enabled by default when creating a new Application

### ISSUE THREAD

**Issue by seanpeters86** [spinnaker/spinnaker#4095]
### Issue Summary:
When creating a new application within Spinnaker most options are NOT checked by default, except for Chaos Monkey. This field should default to not being checked, as an opt-in mode only. That way if someone wants to use it they need to explicitly turn this on.

### Cloud Provider(s):
Google/GCE

### Environment:
1.12.4

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
@spinnaker/ui-ux-team

### Description:
When creating a new Application, Chaos Monkey is enabled/checked by default. This should be changed to be unchecked by default. 

If these settings could even be tweaked inside of Deck's settings.js as "newApplication.defaults" that would be even better.

### Steps to Reproduce:
1. Login to Spinnaker
2. Actions -> Create Application
3. Chaos Monkey will be default checked.

### Additional Details:
<img width="612" alt="Screen Shot 2019-03-10 at 12 31 07 AM" src="https://user-images.githubusercontent.com/10604059/54081539-d290a580-42cb-11e9-8583-92c37897c857.png">

**Comment by seanpeters86** [comment]
This is still happening on 1.13.0

**Comment by maggieneterval** [comment]
Hey @seanpeters86, apologies for the delayed followup here. The current expected behavior is that if you've enabled the Chaos Monkey feature flag in Deck's settings.js, it will default to enabled for any new applications you create (per this logic [here](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/chaosMonkey/chaosMonkeyNewApplicationConfig.component.ts#L10)). Looping in @anotherchrisberry who I believe worked on this feature -- any thoughts on changing this from opt-out to opt-in for new applications?

I think we'll have to give more thought to adding configurable defaults for new applications, but that's a really interesting idea! I supposed the trade-off here falls into the complexity vs. configurability bucket. Definitely keep me posted on other situations that come up where you feel it would have been useful to have configurable defaults for new applications.

**Comment by anotherchrisberry** [comment]
It makes sense to me to make this configurable. We made it opt-out because we're maybe a little zealous about chaos engineering at Netflix, and we want people to have to decide to not use it for new applications.

For organizations that are trying out Chaos Monkey, or are not as enthusiastic about it, they should be able to make it opt-in.

This would be a pretty simple change, and we'd be really happy for a PR for this feature!

**Comment by maggieneterval** [comment]
Nothing wrong with zealotry for chaos engineering! But I'm happy to make the change, will put in a PR later.

**Comment by seanpeters86** [comment]
I'll echo what was said above, we are adopting the chaos mentality across the organization, but having it opt-in but available makes it a great feature that is easily available if an application team wants to try it out.
