### ISSUE TITLE
Add Jenkins Artifact support

### ISSUE THREAD

**Issue by Jammy-Louie** [spinnaker/spinnaker#4101]
### Issue Summary:
Currently there is no Jenkins Artifact support.

We want to be able to get the file from a Jenkins trigger without having to specify a fully qualified http url.

A user should be able to specify the following

1. desired file name
1. the version
1. the job name

and we should be able to match that artifact from the Jenkins Trigger

### Cloud Provider(s):
Core

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
DECK, IGOR, ORCA and CLOUDDRIVER

**Comment by Jammy-Louie** [comment]
@spinnakerbot add-label provider/cf

**Comment by ezimanyi** [comment]
We chatted a bit about this, but just adding a couple of links to some existing work on this that might be useful:
* [Inflating artifacts from build triggers](https://www.spinnaker.io/reference/artifacts/from-build-triggers/): This allows the user to use a Jinja template to extract artifacts from a Jenkins build.  This is primarily useful when the artifact is stored in some repository outside of Jenkins and you want to construct a reference to that artifact from the output of the Jenkins job.
* [Artifact Decorator](https://github.com/spinnaker/igor/blob/master/igor-web/src/main/groovy/com/netflix/spinnaker/igor/service/ArtifactDecorator.groovy): This is functionality to add details to the artifacts Jenkins archives to make them more compatible with Spinnaker artifacts.

From our discussion, I think you're interested more in the second case, where you'd like Spinnaker to be able to read artifacts that live directly in Jenkins, but you'd like to more generally create an HTTP artifact (regardless of the particular type of the file).  There may be a way to add a new artifact decorator to do this.

**Comment by jkschneider** [comment]
@ezimanyi We looked into `ArtifactDecorator` a bit and won't be using it because it decorates `GenericArtifact` which is not the type that Jenkins uses (Travis and Wercker and more recently Concourse do). Even in these cases, where we eventually circle back and enhance Travis and Wercker to generate proper artifacts, we won't interface with `ArtifactDecorator`. The potential overlap is with `ConfigurableArtifactDecorator` which simply mutates state on the artifact, and so would effectively overwrite anything we do (making them compatible). We should ultimately deprecate and remove `ArtifactDecorator` because the artifact type, version, reference, name, etc are well-known by each trigger type.

>  but you'd like to more generally create an HTTP artifact

We have added a Jenkins artifact type, and be using that instead. 

* A Jenkins match artifact has a `reference` to the relative path of the archived artifact in Jenkins and `metadata.version` == build number and `metadata.job` == job name.
* A Jenkins default artifact is the same, but `metadata.version` can have the special value `lastSuccessfulBuild`.

`JenkinsArtifactCredentials` needs to be aware that the base path of an archived artifact is different for the special case of `lastSuccessfulBuild` than a particular build number.

Much of this work is done. You'll be able to see it all shortly.

**Comment by Jammy-Louie** [comment]
Default artifacts screen shot:

![Screen Shot 2019-03-14 at 1 07 46 PM](https://user-images.githubusercontent.com/8474965/54376819-3fa09400-465a-11e9-9bb0-9c80211e98dd.png)

Expected artifacts screen shot:
![Screen Shot 2019-03-14 at 1 08 00 PM](https://user-images.githubusercontent.com/8474965/54376842-4a5b2900-465a-11e9-8b87-702c2c43404c.png)

**Comment by battlecow** [comment]
Any chance this feature might make it into a release soon?  Would be pretty helpful for my purposes.

**Comment by bobthebuilderberlin** [comment]
Same for me, would be really helpful.

**Comment by vstrizaks** [comment]
Hello. Any chance this feature might make it into a release soon? Would be pretty helpful for my purposes.

**Comment by jacogreyling** [comment]
Guys I see this has been closed, but I don't see it in the official documentation. Is it available? Do I need to 'enable' it via hal explicitly?
