### ISSUE TITLE
RFC: Remove OpenStack Cloud Provider

### ISSUE THREAD

**Issue by emjburns** [spinnaker/spinnaker#4316]
The OpenStack cloud provider is not usable in the current state. I'd like to remove it. If in the future someone wants to add it back I'm happy to advise on that effort.

**Comment by seanpeters86** [comment]
Agree with the idea for removing the OpenStack provider. There are two main points as to why I think this needs to happen:
1. If a new user of Spinnaker installs a stable version of Spinnaker and tries to add the OpenStack provider, they will be littered with problems (details below), so leaving the provider as active with documentation up is a bit missleading.
2. Any users (like myself) that are currently using this provider cannot do so on a current version, so this would have no impact on those users who might still be using this on a deprecated version of Spinnaker.

### Current known issues with the OpenStack provider on latest stable (1.13.4):
- Editing Pipelines to destroy or bake to openstack (only way around this is to edit the pipeline JSON directly)
- Create/Destroy Server Group
- Create/Destroy Load Balancer
- Create/Destroy Firewall Rule
- Error messages frequently in the UI and error logs

Most of the above issues have been broken starting with 1.9.X release. 1.8.X works okay...but has some performance problems to say the least.

#### Relevant Spinnaker Issues

All openstack issues have either gone stale or been closed due to lack of support from folks contributing to these problems. This in general leads to a poor user experience, listing some relevant issues here:
- #4111 Cannot Create or edit deploy stage in pipelines
- #3706
- #3692 Create server group fail 
- #3343 Bake stage failed
- [Others here](https://github.com/spinnaker/spinnaker/issues?q=is%3Aissue+label%3Aprovider%2Fopenstack+is%3Aclosed)

**Comment by robzienert** [comment]
Unanimous TOC approval. 🥇

**Comment by emjburns** [comment]
Done.

**Comment by dihedron** [comment]
> The OpenStack cloud provider is not usable in the current state. I'd like to remove it. If in the future someone wants to add it back I'm happy to advise on that effort.

Hallo,
I'm evaluating the effort required to bring the OpenStack provider up to date, or at least address a number of issues (among the ~170 I count in the repo) in order to make it usable. 

I have limited exposure to the product internals so far, but that's not a problem per se, even less so if you can help me get up to speed quickly and maybe help me sort the outstanding issues.

Please let me know, thank you.

**Comment by asher** [comment]
@dihedron Since this RFC is closed and completed, I suggest you create a new RFC regarding OpenStack support. Just as important as fixing major issues with the old implementation is having a story around ongoing maintenance to ensure compatibility with future OpenStack releases. It would be a shame to fix the old integration only to be back to where this RFC started in 6-12. A new RFC could help establish whether there's a community willing and able to invest in that ongoing support.

**Comment by sagayd** [comment]
Any new RFC opened for Openstack support? I would like to adapt Spinnaker for Openstack deployment

**Comment by emjburns** [comment]
None opened yet. [Here](https://github.com/spinnaker/community/blob/master/cloud-provider-requirements.md) are the new cloud provider guidelines.

**Comment by sagayd** [comment]
The referenced guideline is for a new new Cloud provider inclusion. Is there a way I can activate Openstack cloud provider once was active now removed? If so, let me know how - please

**Comment by emjburns** [comment]
Nope, as Asher pointed out we need information regarding a long-term plan (ongoing maintenance, upgrades, etc) before we will accept a new cloud provider (even if the "new" provider is an old one that was removed).
