### ISSUE TITLE
Deploy Manifest capture output

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4606]
### Issue Summary:

The Run Job stage allows for [capturing output](https://www.spinnaker.io/guides/user/kubernetes-v2/run-job-manifest/#capturing-output), but it doesn't allow you to deploy multiple jobs via an artifact, like you can with the Deploy Manifest stage. So it would be great if the Deploy Manifest stage could capture output to be used in the future as well, if you're using this stage to deploy a K8s job.

### Cloud Provider(s):

GKE

### Environment:

Spinnaker 1.14.8

### Feature Area:

Spinnaker K8s

**Comment by milesmatthias** [comment]
Related to #4605.

**Comment by ezimanyi** [comment]
If we implemented #4605 to allow deploying multiple manifests as part of a Run Job stage, would that eliminate the need for this particular enhancement?  I'm asking because it seems like the issue is that Run Job and Deploy Manifest each have ~80% of the functionality you need for your use case, and it feels like Run Job is the right stage to use.

**Comment by milesmatthias** [comment]
Yup, you're right, this could be de-prioritized if that ticket is easier to implement.
