### ISSUE TITLE
helm charts: manual execution vs. triggers

### ISSUE THREAD

**Issue by dbyron0** [spinnaker/spinnaker#4628]
### Issue Summary:
Manual execution doesn't provide 'real' helm chart artifacts, which makes for a painful choice between functional manual execution and working triggers.

### Cloud Provider(s):
kubernetes v2

### Description:
Many of the pipelines I work with deal with docker images, helm charts, and files from github (e.g. values files).  At the moment (1.14.x and 1.15.x), I have a pipeline parameter for each helm chart's version and configure the helm chart artifacts with a default that uses the version parameter.  This makes manual execution work just fine.

The struggle comes when I want to trigger the pipeline on arrival of a new docker image or git commit.  If a docker image triggers the pipeline, there's the question of what helm chart to use.  I'm not aware of the notion of a default/latest/master version for helm charts, so the pipeline needs some way to choose one.  Enabling `Use Prior Execution` solves that in a good way.  The trouble is, it breaks manual execution since `Use Prior Execution` takes precedence over `Use Default Artifact`.  What's worse, is that manual execution still appears to work.  The dialog box to specify the helm chart version is still there, but the pipeline execution ignores it and grabs the helm chart from the previous execution.

There's potentially an argument for changing precedence rules, but that would almost certainly break pipelines that depend on it.  It also feels like a bit of a bandaid.  If manual execution provided helm chart artifacts, I wouldn't need a default at all, and I could enable triggers to my heart's content.

@maggieneterval Thanks so much for your help here :)

**Comment by maggieneterval** [comment]
Hey David! Let me summarize your workflow just to make sure I 100% understand:
- You need your bake/deploy pipelines to trigger on changes to the following artifacts: 1) images, 2) helm charts, 3) override files.
- When a pipeline trigger includes a helm artifact, use that helm artifact.
- When a pipeline triggers does not include a helm artifact, use the helm artifact from the most recent execution.
- When a pipeline is run manually, you _don't_ always want the most recent execution's artifacts to be used, you want to be able to enter some version string as a version parameter, and have this hydrate a default artifact. I'd love to learn more about the use case here since it's one I haven't heard before: when do you want to manually trigger a pipeline but not use the most recent execution's artifacts?

I agree that we probably can't change the precedence rules, and I'm also a little hesitant to introduce any helm-specific functionality, but maybe we can find some way to add an artifact selector to the manual execution modal for each expected artifact, allowing you to select from some list of previously supplied artifacts. Or at least allowing you to select from either 1) use prior artifact or 2) use default artifact. Let me know your thoughts on either solution or whether you had other solutions in mind!

**Comment by dbyron0** [comment]
Your summary is right on, and shows that I left some important stuff out.

* At the moment, we don't have any triggers set up when we publish a new helm artifact.  I'm still not sure what mechanism is bet there -- webhook, jenkins trigger, or maybe artifactory trigger.  So for now I'l really only concerned with triggers that don't include the helm artifact

* If manual execution for helm charts ends up working like it does for docker images, I won't need a version param for the helm chart anymore.  You're right though that when executing manually, I want to be able to specify the helm chart version.  I don't want the most recent execution's helm chart artifact.  Or really anything having to do with the most recent execution.  When executing manually, I want to specify all the things.

A solution that works for all kind of artifacts would be lovely.  Then I could get rid of my git branch parameter and defaults for github artifacts too (I think https://github.com/spinnaker/spinnaker/issues/4589 is about this).

But if there's a dropdown, I'd like the choices to be all the available helm chart versions, as grabbed from the helm chart repo, sort of like the way choosing a docker images works...I'd rather not be limited to previously supplied artifacts.

**Comment by dbyron0** [comment]
I feel like I've been holding out on you on one important thing.  Currently, I'm not using helm chart artifacts at all.  I'm using custom + http/file objects, and planning to switch to helm chart artifacts along with this change.  I think the reasons for using http/file are that I can access helm chart from anywhere -- not just where I happen to have a helm account defined in spinnaker...and that helm chart artifacts were just coming into being as I was developing the pipelines.

Anyway, an element of a pipeline's expectedArtifacts array looks like this:
```
    {
      "defaultArtifact": {
        "kind": "custom",
        "name": "foo",
        "reference": "https://blah.com//foo-${ parameters.foo_version }.tgz",
        "type": "http/file"
      },
      "displayName": "foo",
      "id": "891b5ad1-9110-4941-934d-f0057e2d3f1c",
      "matchArtifact": {
        "kind": "custom",
        "name": "foo",
        "reference": "https://blah.com/foo/charts/foo-.*.tgz",
        "type": "http/file"
      },
      "useDefaultArtifact": true,
      "usePriorExecution": false
    },
```

I defined a similar helm chart artifact through the 1.13.10 UI and it looks like this:
```
    {
      "defaultArtifact": {
        "customKind": true,
        "id": "05cb6638-85d1-421e-b7e1-02d1087736e1"
      },
      "displayName": "foo",
      "id": "bfbd8ecf-4936-4f51-bc9d-584c685f3a89",
      "matchArtifact": {
        "artifactAccount": "my-helm-account",
        "name": "foo",
        "reference": "my-helm-account",
        "type": "helm/chart",
        "version": "0.1"
      },
      "useDefaultArtifact": false,
      "usePriorExecution": false
    },
```

Not sure why there's a defaultArtifact there, but otherwise this looks great, except for maybe one other thing -- the version.  Through the UI I only get to choose from a dropdown of actual versions (which is what I'm hoping for in the manual execution dialog box), but what I really want here is any version at all.  Not sure if I do that by leaving the version out of the json entirely, or setting it to `".*"` or maybe I'm thinking about this all wrong.

Sorry if this is a curveball from what I wrote above.

**Comment by maggieneterval** [comment]
Thanks for the additional information, @dbyron0! It sounds like you might be using default artifacts + parameters in kind of an unusual way to work around some issues with Spinnaker, so I'd like to get to the root of those before we land on a good solution to the manual execution problem.

> At the moment, we don't have any triggers set up when we publish a new helm artifact

I think one recommended approach here is to store your helm chart in source control, and then use a git trigger to run your pipeline upon changes to the chart. But I'm guessing you would have to use a default git artifact until [this issue](https://github.com/spinnaker/spinnaker/issues/4589) is solved since you use github enterprise?

> When executing manually, I want to specify all the things.

Would love to hear more about the user story here -- are you using manual execution as sort of a test / dry run? I think the reason manual execution wasn't built to specify all the things is to guide users toward a more automated workflow. Would love @ethanfrogers' thoughts on the best path forward here, since he knows a lot more about the recommended helm/Spinnaker workflow!

**Comment by dbyron0** [comment]
Well, we store the source for our charts in git (i.e. Chart.yaml, the templates directory, etc.) but we're currently publishing them to an s3 bucket in a jenkins job.  Are you suggesting that we publish the charts (i.e. the tgz files) by committing them to git too?

It's true that we mostly use triggers, but there are times when people need to execute pipelines with a specific docker tag, helm chart version, or values from a branch in git and we'd like that to work.

We also have pipelines that we run manually that use find artifacts from resource to 'promote' an artifact from a dev environment towards prod.  Those don't need triggers though.  It's really the dev environments where this is an issue.  I could see this disappearing as an issue with blue/green deployments in istio, but that seems pretty far off.

**Comment by dbyron0** [comment]
Yeah, when I finally get around to figuring out triggering based on helm chart publishing, I'm planning to send a real artifact somehow, and not depend on the parametrized default...but I think this may be off topic/scope creep for my primary issue, which is triggering based on git/docker changes, and having manual execution work as well.

It's optimistic of me that Istio and blue/green deployment could help.  I'm thinking it may reduce people's desire to run pipelines manually if there's enough automation around pull requests.

And yes, I will happily screenshare at the next kubernetes sig.  Somehow I thought this was a straightforward thing of treating helm charts in manual execution the way we treat docker images, but apparently not :)

**Comment by maggieneterval** [comment]
No you're totally right, I'm getting distracted trying to solve all the problems and I should probably just do whatever we're doing for Docker images for helm -- how can I get the UI you're talking about to show up in the manual execution modal for docker images? Do I need to do anything special besides set a docker image trigger/expected artifact?

**Comment by maggieneterval** [comment]
Also I was wrong about the [manual execution react conversion](https://github.com/spinnaker/deck/pull/7075) already being merged, must have seen something similar float through email...sorry I'm disappointing you on all fronts this week @dbyron0 :sob:

**Comment by dbyron0** [comment]
I made a brand new pipeline in 1.13.x with a docker image expected artifact.  That by itself isn't enough to show the docker details in the manual execution modal (separate bug?).  Turns out that defining a docker trigger all by itself (no expected artifact) is enough to bring up the modal.

**Comment by dbyron0** [comment]
So, this is enough:
```
{
  "expectedArtifacts": [],
  "keepWaitingPipelines": false,
  "lastModifiedBy": "david.byron@avast.com",
  "limitConcurrent": true,
  "stages": [],
  "triggers": [
    {
      "account": "my-docker-account",
      "enabled": true,
      "organization": "my-org",
      "registry": "registry.mydomain.com",
      "repository": "foo/bar",
      "type": "docker"
    }
  ],
  "updateTs": "1563481498000"
}
```

**Comment by maggieneterval** [comment]
Thanks David! While looking into this I found (& [hopefully fixed](https://github.com/spinnaker/deck/pull/7241)) another bug with triggers on master :face_with_head_bandage: , so thanks for helping surface that. I do now see the pretty docker image dropdown and finally grok what you are requesting for helm! We should definitely wait til the big react PR is merged, just waiting on Netflix's final approval on that one and then *hopefully* won't be terrible to implement. Thanks for answering my many questions!! :question: :smile:

**Comment by dbyron0** [comment]
This is all so exciting!!

**Comment by maggieneterval** [comment]
Sorry for being so slow! This look good to you?

![6afce7a8-367d-4eaf-9c02-4818774b49b3](https://user-images.githubusercontent.com/15936279/62727783-2f61ca80-b9e8-11e9-85af-fd35bd51662d.gif)

**Comment by dbyron0** [comment]
I'm having a hard time containing myself :)

I'm curious why there's a checkbox for override....and I guess why it's called `Helm override` instead of `Helm`.  For manual execution, don't people need to provide the version all the time?

**Comment by maggieneterval** [comment]
I hid it behind a checkbox so people wouldn't shoot themselves in the foot and use this instead of the existing behavior (which is just using a default artifact), and I called it an override because you're overriding the default artifact, but I'm open to suggestions! @ethanfrogers any thoughts here?
