### ISSUE TITLE
conflict with embedded spring config and swagger

### ISSUE THREAD

**Issue by claymccoy** [spinnaker/spinnaker#4662]
### Issue Summary:
After the refactoring to move spring config code out to kork (https://github.com/spinnaker/clouddriver/pull/3850), I see problems starting clouddriver when spring config server is configured.

### Environment:
I'm running this locally with a spinnakerconfig.yml that points to a local git repo for config.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
config

### Description:
Spinnaker fails to fully initialize due to this error on startup:
`Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.IllegalArgumentException: Multiple entries with same key: springfox.documentation.spring.web.plugins.PathAndParametersEquivalence`

### Steps to Reproduce:
Start Spinnaker with cloud config server configured.

### Additional Details:
You can work around this by disabling swagger in clouddriver-wb/config/clouddriver.yml.
When debugging into this I see a key collision for urls when generating the swagger docs. I believe this is a config server url (GET /{name}/{profile}/**). Attached is a screenshot of the debugger right before the exception is thrown. I'm wondering if this endpoint could be customized to have a static portion that would avoid the collision or it could be blacklisted from swagger. This didn't happen until after the refactoring with kork, which is odd because it didn't look that moving the code would change the behavior.

![Screen Shot 2019-07-21 at 10 46 50 PM](https://user-images.githubusercontent.com/2743/61726016-84d68000-ad36-11e9-8b1a-ab989573f242.png)

**Comment by claymccoy** [comment]
@scottfrederick

**Comment by ethanfrogers** [comment]
+1 I saw this a lot recently, however, I was even seeing this before it was moved over to Kork.

**Comment by scottfrederick** [comment]
@claymccoy @ethanfrogers This is apparently an incompatibility between Spring Cloud Config and the `2.7.0` version of Swagger that's currently being used. Swagger has problems with any app that has multiple endpoints (e.g. `@RequestMapping`s) that use the same path and request parameters but differ by `produces` (see https://github.com/springfox/springfox/issues/2039). Config Server defines multiple endpoints in this way.  

The problem is intermittent, and apparently comes and goes based on project re-builds. 

I'm looking into upgrading Swagger to `2.9.0` or later.
