### ISSUE TITLE
Clean up the Oracle API jars

### ISSUE THREAD

**Issue by plumpy** [spinnaker/spinnaker#4740]
cc @clareliguori @andrewbackes 

I'd like to merge spinnaker/clouddriver#3695 (which was rolled back) because it should fix #4731, but I need help from Amazon figuring out why it's causing problems for Armory with Lambdas.

Here's some background:

The Oracle Cloud libraries weren't in Maven until recently. So we have gradle download the jars from Github and put them into the build. This causes a number of problems (e.g. sometimes Github is unreachable) and, frankly, is just weird. Fortunately, they started publishing their libraries to Maven, so we can integrate them into the build in a more normal way. That's what the PR above does.

When we download the Oracle jars from Github, it includes a copy of Apache's httpclient 4.5.0. We also get httpclient 4.5.9 from Maven, but 4.5.0 ends up on the classpath _before_ 4.5.9. I believe that's the cause of #4731, where the AWS libraries complain that we're using a too-old version of httpclient.

My PR fixes this issue so there's only a single copy of httpclient on the classpath. Essentially this means we're upgrading httpclient from 4.5.0 to 4.5.9, since 4.5.0 gets removed. Rather than making the world a better place :peace_symbol:, however, it somehow causes #4484 :boom:.

Since I don't know how to reproduce Armory's issue, I'm hoping someone from either Amazon or Armory could look into this and figure out what's happening. At this point, between #4731 and #4484, we're kinda damned-if-we-do-damned-if-we-don't. But we can't be stuck on httpclient 4.5.0 forever, so fixing the latter issue is really the better way forward for the project.

Thanks for the help and let me know if there's any assistance I can provide :cactus: :dango:

**Comment by clareliguori** [comment]
Ok, here's my theory. TLDR: I think it's safe to re-merge, because we're bringing in httpclient 4.5.9 and have already upgraded aws-sdk to a fixed version.

Looking at [this issue](https://github.com/spinnaker/spinnaker/issues/4484#issuecomment-500045241), httpclient 4.5.8 is called out as the version that was introduced by spinnaker/clouddriver#3695, and seemed to cause the error "The request signature we calculated does not match the signature you provided" when calling Lambda ListVersionsByFunction API.

A couple aws-sdk users also [reported that error](https://github.com/aws/aws-sdk-java/issues/1919#issuecomment-471451804) for S3 requests, when their URL had special characters.  I *think* this is because the non-normalized URL is fed into the signature calculation on the client side.  After httpclient normalizes the URL, the signature then calculated on the server-side doesn't match because it's using a different string than what the client used to calculate the signature.

Lambda uses REST APIs, so under the hood, a ListVersionsByFunction API call looks like `https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/my-function-name/versions?Marker=randoma+c`.  If the marker (i.e. pagination token) contains special characters (it almost always does), I think it would have been incorrectly normalized by httpclient 4.5.8, but not by httpclient 4.5.9 + aws sdk 1.11.596+.

**Comment by plumpy** [comment]
Awesome, Clare, thanks so much for looking into this so thoroughly and quickly! I really appreciate it. :fireworks: 

I'm not sure I have the authority to bestow the prestigious Spinfluencer of the Week award, but I'm going to check the rule book and find out because you definitely deserve it  :1st_place_medal:

**Comment by maggieneterval** [comment]
I checked the rule book and Clare is #spinfluencer of the week! Thanks Clare! :boat: :calendar: :1st_place_medal:
