### ISSUE TITLE
Filtering by stack or detail in project dashboards doesn't work

### ISSUE THREAD

**Issue by gnarea** [spinnaker/spinnaker#4880]
### Issue Summary:

If I set the stack or detail fields to something valid, other than `*`, the project dashboard fails to list anything from the selected clusters.

### Cloud Provider(s):

GCP

### Environment:

We're using the solution provided by Google: https://cloud.google.com/docs/ci-cd/spinnaker/spinnaker-for-gcp?hl=en_GB

We're also using Spinnaker 1.16 with the Kubernetes provider v2.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Deck

### Description:

I'm trying to create a project dashboard that pulls data from two applications, two pipelines in those applications and one Kubernetes cluster.

There are a few namespaces in that cluster, but I only want to see one in the dashboard. In fact, I only want to see Spinnaker-managed resources that match a specific Spinnaker stack (and potentially detail too) in that namespace.

If I use the default value for the stack and detail fields, `*`, I get everything across all namespaces. But if I replace the `*` with the right stack or detail, I don't get anything. In fact, I understand an empty string would return resources without a Spinnaker stack/detail, but even that returns nothing even though most resources in those namespaces don't have any stack/detail.

### Steps to Reproduce:

1. Create a Deploy Manifest stage with some Moniker labels; e.g.:
   ```json
    {
      "account": "the-account",
      "cloudProvider": "kubernetes",
      "manifestArtifactAccount": "gcs-install-account",
      "manifestArtifactId": "the-manifest",
      "moniker": {
        "app": "foo",
        "detail": "the_detail",
        "stack": "the_stack"
      },
      "name": "Apply resources",
      "overrideTimeout": true,
      "refId": "Apply resources",
      "requiredArtifactIds": [
        "the-docker-image"
      ],
      "requisiteStageRefIds": [],
      "source": "artifact",
      "stageTimeoutMs": 600000,
      "type": "deployManifest"
    }
   ```
1. Execute the pipeline.
1. Check that the resources were created with the appropriate Kubernetes annotations; e.g.:
   ```yaml
    moniker.spinnaker.io/application: foo
    moniker.spinnaker.io/cluster: deployment cluster1
    moniker.spinnaker.io/detail: the_detail
    moniker.spinnaker.io/stack: the_stack
   ```
1. Create a new project dashboard that pulls data from `cluster1` with stack set to `the_stack` and/or detail set to `the_detail`.

**Comment by maggieneterval** [comment]
Hi @gnarea, thanks for taking the time to open this issue! Unfortunately this is a known issue with the Kubernetes V2 Provider (see this similar [issue](https://github.com/spinnaker/spinnaker/issues/3490)). Only filtering by `*` for stack and detail will return any clusters. This is because unlike with the other VM-based providers, an application cluster itself is not associated with a single stack/detail, and each of its workloads can be associated with different stacks/details depending on the moniker annotations added to each manifest. This violates some assumptions in the Clouddriver logic shared by all providers and would be non-trivial to fix, so I'll confer with the Spinnaker Kubernetes SIG leads on if/how we should address this at our next issue triage meeting.
