### ISSUE TITLE
Execution Parameters does not display label

### ISSUE THREAD

**Issue by wuzhihui1123** [spinnaker/spinnaker#4890]
### Issue Summary:
**When the pipeline is executed, the label of the parameter is not displayed.**

![image](https://user-images.githubusercontent.com/4246626/64931964-612f4200-d86e-11e9-976a-81774ca9855b.png)
![image](https://user-images.githubusercontent.com/4246626/64931989-89b73c00-d86e-11e9-960b-be7148f9742a.png)

### Environment:
  spinnaker version: 1.16.0

**Comment by maggieneterval** [comment]
Hi @wuzhihui1123, thanks taking the time to open this issue and apologies for the delayed response; we're still working on the Spinnaker SIG-managed issue triage process 😄 

I think this would be a great beginner-friendly issue and am happy to help someone submit their first PR to fix this -- please feel free to reach out if you are interested!

**Comment by sgarlick987** [comment]
If I understand correctly, if there is a label set on a parameter, it should use that instead of the parameter name when displayed in the manual execution gui. 

That looks to be handled by

https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/pipeline/manualExecution/Parameters.tsx#L52

I tested changing that to `label: parameter.label || parameter.name,`

Config - one with and one without a label

![image](https://user-images.githubusercontent.com/5222700/71494767-978a3f00-2817-11ea-83a5-1cb016e8a71a.png)

Manual Execution Parameters - label is showed for parameter with and name for one without

![image](https://user-images.githubusercontent.com/5222700/71494791-e89a3300-2817-11ea-8ae5-2ef069408b86.png)

Execution Parameters 

![image](https://user-images.githubusercontent.com/5222700/71494815-1e3f1c00-2818-11ea-9d90-555bd21eb96b.png)

In that last image of the run execution, it shows the parameter name still instead of a label. Does that make sense to leave that way? or should that also show the label instead?

**Comment by maggieneterval** [comment]
Appreciate you looking into this, @sgarlick987!

> I tested changing that to label: parameter.label || parameter.name

Your proposed change makes sense to me! In fact, it looks like this is the [logic that existed before](https://github.com/spinnaker/deck/pull/4912/files) this component was converted from Angular to React.

> In that last image of the run execution, it shows the parameter name still instead of a label. Does that make sense to leave that way? or should that also show the label instead?

I think it makes sense to also display the label (if it is defined) in the execution details. Currently, the help text when configuring a label reads `(Optional): a label to display when users are triggering the pipeline manually`. Perhaps we could update that to make it clear that this label will also be displayed in the execution details?

**Comment by maggieneterval** [comment]
Looks like this issue did not automatically close, but huge thanks to @sgarlick987 for the PR! This fix is in Spinnaker 1.19.
