### ISSUE TITLE
Unable to input anythings in image id textfield with Docker Registry trigger pipeline

### ISSUE THREAD

**Issue by hobit1111** [spinnaker/spinnaker#4929]
### Issue Summary:
image ID text field can not input anything when manually specifying image id for trigger of docker_registry

### Cloud Provider(s):
Kubernetes v2（private）

### Environment:
1.15.*

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
UI（deck）

@spinnaker/ui-ux-team

### Description:
Click the text field in Image Id and try to input the number or strings but nothings is shown in
the text filed ;
the image id text field is in the application -> pipeline -> automated triggers -> image id

Probably the reason is that imageId always be null so the input textfiled value always been shown as null .

```
if (defineManually) {
      return (
        <div className="sp-formGroup">
          {manualInputToggle}
          <div className="sp-formItem">
            <div className="sp-formItem__left">
              <div className="sp-formLabel">Image ID</div>
              <div className="sp-formActions sp-formActions--mobile">
                <span className="action" />
              </div>
            </div>
            <div className="sp-formItem__right">
              <div className="sp-form">
                <span className="field">
                  <input
                    className="form-control input-sm"
                    value={imageId || ''}
                    onChange={e => this.valueChanged('imageId', e.target.value)}
                  />
                </span>
              </div>
            </div>
          </div>
          {warning}
        </div>
      );
    }
```

I think "imageId"  need to be set in "valueChanged" function but "imageFields" list hasn't the "imageId" element so the change will never happened.

```
const imageFields = ['organization', 'repository', 'tag', 'digest' ];

 private valueChanged(name: string, value: string) {
    const changes = { [name]: value };
    if (imageFields.some(n => n === name)) {
      // values are parts of the image
      const { organization, repository, tag, digest } = this.props;
      const imageParts = { ...{ organization, repository, tag, digest }, ...changes };
      const imageId = DockerImageUtils.generateImageId(imageParts);
      changes.imageId = imageId;
    }
    this.props.onChange && this.props.onChange(changes);
  }
```

### Steps to Reproduce:
1.click the applications and click the pipelines
2. click the pipeline configure 
3. click the automated triggers
4. switch the type to docker registry
5. switch the define image id to manually
6. try to input strings in image ID

### Additional Details:
![image](https://user-images.githubusercontent.com/39323470/65209609-51f90000-dacb-11e9-8700-f432c24288f4.png)

**Comment by maggieneterval** [comment]
Thank you so much for opening this detailed issue! Would you be interested in making a pull request to address this? We would be happy to provide code review and guidance.

**Comment by hobit1111** [comment]
> Thank you so much for opening this detailed issue! Would you be interested in making a pull request to address this? We would be happy to provide code review and guidance.

Sorry to reply so late cause by the holiday and we are interested in making a pull request to this.

**Comment by maggieneterval** [comment]
@hobit1111 I'm so happy to hear that you are interesting in making a pull request to resolve this issue! Please feel free to reach out here if I can help in any way.

**Comment by maggieneterval** [comment]
Hi @hobit1111, hope all is well. As the release window for Spinnaker 1.17 approaches next week, I just wanted to check in to see whether you were still interested in submitting a fix for this issue. Totally fine if not, just let me know because in that case I'll submit a fix myself. Thanks so much!

**Comment by hobit1111** [comment]
@maggieneterval i am still interested in spinnaker and likely to submit the issue future, but i am so sorry to miss the release windows cause i am not so good at coding typescript to fix this bug, so the bug fix is now base on you. Thanks you very much!

**Comment by maggieneterval** [comment]
Sounds good, thanks for letting me know @hobit1111!

It appears that the `DockerImageAndTagSelector` component is broken only when rendered by the `DockerTriggerConfig` (in the Automated Triggers section of a pipeline config). This is because [we are not persisting a manually defined `imageId` on the trigger](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerConfig.tsx#L17), and never passing any `imageId` prop from `DockerTriggerConfig`. On the other hand, in `TitusRunJobStageConfig` and `TitusServerGroupBasicSettings`, we are persisting the `imageId` and passing it back to `DockerImageAndTagSelector` as a prop.

`DockerImageAndTagSelector` only renders the "define image ID manually" textbox if it has `props.imageId` _and_ `props.imageId` contains SpEL. Since we rely on a fully-resolved Docker image repository name to hydrate the Docker manual execution component, I'm leaning toward a solution that disallows defining an image ID manually when configuring a Docker trigger. If someone really needed to use SpEL, they could edit the pipeline trigger JSON directly. It appears that the manual textbox never worked, so I don't think removing it will be too painful for users. @louisjimenez @christopherthielen @erikmunson @Jammy-Louie any opposition to this solution?

**Comment by erikmunson** [comment]
oh yeah, this is a bug/oversight. that selector was never intended to allow manual entry of images when it's being used for triggering a pipeline. I think we may have noticed this a while ago internally too and never got around to fixing. Thanks for the summary @maggieneterval 🙏

**Comment by louisjimenez** [comment]
Using the edit JSON directly seems reasonable given the manual textbox wasn't functional prior. Thanks!
