### ISSUE TITLE
Patch Manifest seems broken in 1.16.1 with bound docker artifacts

### ISSUE THREAD

**Issue by perek** [spinnaker/spinnaker#4956]
### Issue Summary:
We seems to be unable to use the docker artifact binding in the patch manifest stage in 1.16.1

### Cloud Provider(s):
k8s docker

### Environment:
1.16.1

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
ui? probable problem is due to artifacts rewrite

### Steps to Reproduce:
1.) make a docker trigger with expected docker artifact
2.) make a patch manifest with this image in the manifest
3.) bind the expected artifact
4.) trigger pipeline, will get error for unbound artifact on the patch stage

### Additional Details:
Here are some actual errors:
```
The following required artifacts could not be bound: '[Artifact(type=docker/image, customKind=false, name=123456789.dkr.ecr.us-east-1.amazonaws.com/delivery, version=staging-abc123, location=null, reference=123456789.dkr.ecr.us-east-1.amazonaws.com/delivery:staging-abc123, metadata=null, artifactAccount=docker-registry, provenance=null, uuid=null)]'.Check that the Docker image name above matches the name used in the image field of your manifest.Failing the stage as this is likely a configuration error.
```

here is the manifest of the stage throwing the error:
```
spec:
  template:
    spec:
      containers:
        - image: 123456789.dkr.ecr.us-east-1.amazonaws.com/delivery
          name: delivery

```

The name and the image tag match, this should be resolved.

**Comment by perek** [comment]
@maggieneterval I found the issue

It seems in 1.16 a new field `artifactAccount` is written to the match artifact, this is passed to the artifact resolver and breaks resolution for some reason:
Broken:
```
"matchArtifact": {
        "artifactAccount": "docker-registry",
        "id": "825ebfa6-56b3-47f1-9c5c-ad4bc2867a31",
        "name": "1234567890.dkr.ecr.us-east-1.amazonaws.com/olympus/scripts",
        "type": "docker/image"
      },
```
Works:
```
"matchArtifact": {
        "id": "825ebfa6-56b3-47f1-9c5c-ad4bc2867a31",
        "name": "1234567890.dkr.ecr.us-east-1.amazonaws.com/olympus/scripts",
        "type": "docker/image"
      },
```

**Comment by ezimanyi** [comment]
@perek : I just tried to reproduce this, and was able to get this to work.  In my case, the artifact account was indeed present in the `matchArtifact` just as in your case but it did work.  (I also looked at the artifact matching logic and it doesn't look at the account on the artifact.)

There's obviously something different between your pipeline and my test case---are you observing this across different pipelines that use the 'Patch manifest' stage, or is this one particular pipeline?  Also, what particular resource type is this patching (ie, is it a `ReplicaSet` or a `Deployment`) to make sure that I'm trying exactly the same thing?

**Comment by maggieneterval** [comment]
I'm also wondering if the image reference from your error, `123456789.dkr.ecr.us-east-1.amazonaws.com/delivery`, is missing a part (at least according to Spinnaker)? I think Spinnaker's parsing logic expects an image artifact reference to have three `/`-separated parts: `{registry}/{project}/{image}`.

**Comment by perek** [comment]
hmm @maggieneterval  that may be right? the weird thing is that removing that field fixed the pipeline

**Comment by ezimanyi** [comment]
I did some more testing today and was able to reproduce the exact issue.  As @perek said, it is indeed the new `artifactAccount` that is breaking things.  When we replace the artifacts in the manifest, we are not considering the `artifactAccount` field; but then when we make sure that we did replace the expected artifacts we're comparing what we replaced against artifacts that do have the `artifactAccount` field filled out.

The reason I wasn't able to reproduce this before is because I was using a default artifact, and it had the `artifactAccount` filled out.  But if I remove that field from the default artifact (but leave it in the `matchArtifact`) I get the exact error above.  This simulates what would happen if you tried to trigger a pipeline with either a webhook or with a docker trigger but didn't update the trigger to pass in the new `artifactAccount` field (which you probably shouldn't need to do anyway).

I should be able to make a quick change here to consistently use (or not) the `artifactAccount` field when replacing artifacts.
