### ISSUE TITLE
Support get CRD Kinds manifest status as automatically stable in Kubernetes v2 provider

### ISSUE THREAD

**Issue by joariasl** [spinnaker/spinnaker#5039]
### Issue Summary:

clouddriver can't get manifest stability for `customresourcedefinition` `kind` like `ServiceMonitor` created by Prometheus Operator

### Cloud Provider(s):

Kubernetes

### Environment:

All

### Feature Area:

Pipelines, Kubernetes v2 Deploy

### Description:

clouddriver returns `Exception ( Wait For Manifest To Stabilize )` result if Spinnaker deploys a `customresourcedefinition` `kind` like a `ServiceMonitor` of Prometheus Operator after 30 minutes like is described in the documentation https://www.spinnaker.io/reference/providers/kubernetes-v2/#accommodating-level-based-deployments

This is apparently caused by it's needed a specific Kubernetes CRD Extensions to obtain the status of the specific Kind like is documented in https://www.spinnaker.io/guides/developer/crd-extensions/

The Kubernetes v2 documentation (https://www.spinnaker.io/reference/providers/kubernetes-v2/#workloads) specify each stability method used by each Kind like `Ingress` using the `status.loadBalancer` field or the `ConfigMap` with a `Automatically stable` considered (https://github.com/spinnaker/clouddriver/blob/079ee0afb9e7d77335f11b077a77742879464f44/clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesConfigMapHandler.java#L56).

Maybe a solution is to consider the manifest status OK to all custom Kind if the specific `KubernetesHandler` does not exist or create a reserved annotation to specify to not check the status result or select the manifest method usage only.

### Steps to Reproduce:

1. Setup a `customresourcedefinition` (CRD) like a `servicemonitor` created by Prometheus Operator.
2. Deploy a Kubernetes manifest using the Kind of the CRD.
3. Notice the returned error `Exception ( Wait For Manifest To Stabilize )`

### Additional Details:

Error returned
<img width="750" alt="image" src="https://user-images.githubusercontent.com/8829064/67042453-4ca8c880-f0fe-11e9-9862-4345cc8a3720.png">

**Comment by ezimanyi** [comment]
@joariasl : This should be working without customizing clouddriver, as CRDs without a custom handler fall back on the [KubernetesUnregisteredCustomResourceHandler](https://github.com/spinnaker/clouddriver/blob/7bf90828c7da8dd4c9e2007f8d9c08fa0d755a92/clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesUnregisteredCustomResourceHandler.java#L57) which always considers the manifest stable.

I suspect what might be happening here is that clouddriver is not caching your kind at all, perhaps due to permission issues.  Do you see any log entries referring to `servicemonitor` in your clouddriver logs?  In particular, do you see any entries saying that the CRD is not readable and won't be cached?

Another thing to check is if clouddriver has permission to list the CRDs in the cluster; it will only be able to enumerate the existing CRDs and cache them if it has the required permissions.  If this is not the case, you'll likely see an error around startup that CRDs aren't readable.

**Comment by ezimanyi** [comment]
Closing this for now per the above explanation, please feel free to re-open if you're still running into issues.  Thanks!

**Comment by Derenge** [comment]
Hi! I'm running into this exact same issue with a GKE `ManagedCertificate` manifest.

I can see that the caching agent is starting, but no errors about CRD not being readable or won't be cached.

```

2020-03-10 12:57:56.560 CST
2020-03-10 18:57:56.560 INFO 1 --- [ecutionAction-9] k.v.c.a.KubernetesV2OnDemandCachingAgent : spinnaker/KubernetesUnregisteredCustomResourceCachingAgent[1/1]: agent is starting
```
```
I 2020-03-10T18:57:34.831354286Z 2020-03-10 18:57:34.831  INFO 1 --- [tionProcessor-2] c.n.s.c.data.task.jedis.JedisTask        : [DEPLOY_KUBERNETES_MANIFEST] Swapping out artifacts in ManagedCertificate.networking.gke.io graphql-gateway from context...
 
I 2020-03-10T18:57:34.817596204Z 2020-03-10 18:57:34.817  INFO 1 --- [tionProcessor-2] c.n.s.c.data.task.jedis.JedisTask        : [DEPLOY_KUBERNETES_MANIFEST] Finding deployer for ManagedCertificate.networking.gke.io...

```

**Comment by patoarvizu** [comment]
Just to add here that I ran into the same issue but in addition to adding the permissions for `customresourcedefinitions`, I also had to restart the `spin-clouddriver` pods to get it to cache CRDs.

**Comment by ezimanyi** [comment]
@patoarvizu : Yes, that's a good point, thanks for writing that here.  To avoid continuously checking the permissions over and over again, Clouddriver caches which Kubernetes kinds it is able to read for the lifetime of the process, so it would need to be restarted to discover any such changes.
