### ISSUE TITLE
Feature Request (CloudBuild) : Ability to invoke pre-configured GCB triggers

### ISSUE THREAD

**Issue by afcastano** [spinnaker/spinnaker#5076]
### Issue Summary:
Currently there is no way of invoking [pre-configured GCB triggers](https://cloud.google.com/cloud-build/docs/running-builds/create-manage-triggers) as part of a pipeline.  

### Cloud Provider(s):
GCP

### Feature Area:
Google Cloud Build

### Description:
The idea is to add this capability to the [Google Cloud Build](https://www.spinnaker.io/setup/ci/gcb/) step, so that users can select what pre configured trigger to invoke and potentially pass what commit/trigger/branch they would like to run.

### Additional Details:
One way this could look like for the user is to present another option in cloud build step alongside the two existing ones. The new option will allow using pre-configured triggers.

When the option is selected, a drop down will be shown with the list of triggers available for the google account.

There could be three optional fields more for the commit, branch and tag we want to use to invoke the pre-configured trigger.

**Comment by afcastano** [comment]
Hello @ezimanyi 
We briefly discuss about this in slack a while ago and I would like to help implementing this. Again, and hint would be very helpful and I assume this could touch multiple services and moving parts.

**Comment by ajordens** [comment]
Thoughts on this @ezimanyi / @ttomsu?

**Comment by ezimanyi** [comment]
@afcastano : Thanks for opening the issue!

I think this sounds like a great idea!  Regarding the user experience, I could see a couple of options:
* A new stage type that is specifically for triggering an existing GCB trigger
* Adding an option to the existing stage to use an existing trigger instead of invoking a new build.   
 Maybe this could be just added to the existing Text/Artifact choice:
![image](https://user-images.githubusercontent.com/1391982/68058473-959c7780-fccf-11e9-8556-71ea2594de8d.png)
The reason I suggest that is because this does seem to be a third place your build could be: (1) Directly on the stage (Text) (2) As an artifact (Artifact) or (3) Stored in GCB and run by reference (Trigger).  But I could also see it being confusing to have the user selecting both both whether to run an existing trigger or provide new build, as well as where the artifact comes from as part of a single radio button, so we should think a bit more about this.

As for how to implement this, I think a rough outline of the igor support would be:
* Update `GoogleCloudBuildClient` to support `projects.triggers.list` and `projects.triggers.run` operations.  (Maybe we'd also need `projects.triggers.get`, not sure about that.)
* Add methods on `GoogleCloudBuildAccount` to support listing and running builds (calling into the methods added above).  The call to run a trigger will return an `Operation` so we'll probably want to extract from that generic `Operation` something useful to return to the caller.  (See for example what `createBuild` does to extract the actual build object.)  Ideally the response would contain a `Build` object for the build that was started and we can just return a `Build` but there may be another level of indirection there...I haven't tested myself to see what it returns.  We'll need to return the id of the started build somehow, as that's how the caller will know what to poll on to know when the build has completed.  (Which also means that we should be able to just re-use all the same logic we already have for tracking build status, as we already expose an endpoint from igor to ask for the status of a build by id.)
* Add endpoints to `GoogleCloudBuildController` to support listing triggers and running triggers (calling into the account methods added above).
* There are some pretty robust Spring integration tests on the entire GCB functionality, so (in addition to the usual unit test coverage) it would be great to see tests on the new endpoints in `GoogleCloudBuildTest`.

Then in orca, the rough outline would be:
* Add the igor endpoint to run a trigger to `IgorService` so orca can run triggers
* Either update `GoogleCloudBuildStageDefinition` with new fields (if we re-use the same stage) or make a new class if we make a new stage.  (If we re-use the existing definition it will need to be backwards-compatible so existing pipelines still work.)  Maybe the change could be allowing `buildDefinitionSource` to also be `trigger` and then having an optional field `triggerId`...or something similar.  (This might also be informed by how we decide to make the UI look.)
* You can see the rough outline of how the stage works in `GoogleCloudBuildStage`; the only difference here would be that we'd be doing something different for `StartGoogleCloudBuildTask`.  (So again, either we'd make a new stage that has all the same tasks except a different task to start the build, or update the `StartGoogleCloudBuildTask` to know how to start a build via trigger if the stage values indicate it should.)  As long as the "start" task puts the build it started into `buildInfo` in the context, the downstream `MonitorGoogleCloudBuildTask` and `GetGoogleCloudBuildArtifactsTask` stages will automatically work by looking up the id and calling the existing endpoints in igor.

You'll need to make one small change to gate:
* If the UI is going to present the user a list of triggers, there will need to be an endpoint in gate that can return those.
* In `IgorService` you can add a call to the endpoint you added in igor, then you'll need to expose that.  You can see what we do for Jenkins jobs, and probably do something similar: add a call to `BuildService` then expose that in `BuildController`.

Then you'll need to add UI support in `deck` for configuring the stage:
* The existing stage is in `GoogleCloudBuildStageForm.tsx`.
* This might involve something like adding a new option to "Build Definition Source" and if "Trigger" is selected, showing a drop-down that shows the list of existing triggers (by calling the endpoint you added to gate), as well as fields for setting repo/commit fields (or anything else configurable).

I think that's roughly the broad overview---obviously there are complications/details that I've omitted/forgotten here but that should be broadly what it looks like.  I'm definitely happy to look at small PRs as you start implementing this (and in fact it's probably best to send things in small pieces as they are ready).  I'd recommend doing things in the order above, so starting with the `igor` changes alone (which you can then test by `curl`ing igor even before adding other support) then working outwards until there's full UI support.  We can talk in more detail about open questions/issues with each part as you get through it.

**Comment by afcastano** [comment]
Thanks again for the detailed explanation. I will start working on the `igor` changes and let you know.
Cheers.

**Comment by afcastano** [comment]
@ezimanyi I will focus now on the `orca` and `gate` changes.

Being myself a user of CloudBuild stage in spinnaker, I wouldn't mind adding a third option to the **Build Definition Source** field. For me, it solves the question: Where is your build definition configured?
1. Here in the spinnaker pipeline
2. I have an artifact with the config
3. I have a trigger with the config

Also, If we add another stage type, then I would have two `CloudBuild` stage types that do similar things. It could be confusing as well.

I will go ahead and start enhancing the current stage in `orca` but happy to roll back the changes if we decide to go the other way.

cheers,

**Comment by ezimanyi** [comment]
Sounds good, @afcastano !  I do also think that adding a third option to the dropdown would make sense as a place to put this in the UI, but would also be interested in what @maggieneterval (who wrote the UI for this stage) thinks!

**Comment by maggieneterval** [comment]
+1 to adding a third radio button option to the existing GCB stage. @afcastano, I think you should only have to make changes to the [`GoogleCloudBuildStageForm`](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildStageForm.tsx) component. Let me know if you need any help on the implementation front (Deck is confusing), and feel free to tag me on the PR!

**Comment by afcastano** [comment]
Will be released in 1.18

**Comment by afcastano** [comment]
@jonathanheaden @mafrosis ☝️
