### ISSUE TITLE
Provide ability to force Spinnaker to wait for the "OnDelete" update strategy

### ISSUE THREAD

**Issue by agoyal-sfdc** [spinnaker/spinnaker#5154]
### Issue Summary:
When using the `OnDelete` update strategy for StatefulSets, Spinnaker does not wait for all the pods to be updated since the manifest is considered to be immediately stable.

### Cloud Provider(s):
Kubernetes V2

### Feature Area:
Deploy Manifest

### Description:
We have StatefulSets of pretty large size (50-100 pods), and in this scenario, the `RollingUpdate` strategy does not work for us simply because it would take too long. We need to do batch upgrades instead, so we use the `OnDelete` update strategy. To achieve this, we have built a controller that complements the native StatefulSet controller, and deletes pods in batches of pre-defined size, and waits for each batch of pods to be ready before deleting the next batch of pods. We'd like to have an annotation (or whatever way seems best), to tell Spinnaker to wait while these off-band deletes happen, and keep polling the StatefulSet to see if all the (desired number of) replicas are updated _and_ ready. Currently, to work around this issue, we are using a sort of a hack, in which we attach a Job alongside each StatefulSet (that uses `OnDelete`) which only completes when all the pods are updated and ready.

### Steps to Reproduce:
1) Create a StatefulSet with the `OnDelete` update strategy
2) Try to deploy it via Spinnaker
3) The pipeline will complete nearly instantly

### Additional Details:
Related issue: #4571

**Comment by ezimanyi** [comment]
I can see the desire to have the Spinnaker pipeline wait until the rollout has happened, but I'm a bit on the fence about how much logic we should pull into Spinnaker to handle this.  Since spinnaker/clouddriver#2515, Spinnaker will consider a stateful set rollout immediately stable if it uses the `OnDelete` strategy; this makes sense because without some out-of-band process, it would never become stable.  Of course in this case where you have written an out-of-band process it would be reasonable to wait until these have completed, but I'm not sure how general of a use case this is.

Maybe an annotation would be a reasonable compromise, but I'm also wary about making this too complex/configurable.  In this case it seems like you've effectively built a "StatefulSet that rolls out in batches" CRD so I wonder if a better solution would be to actually make that a CRD and write a custom handler that looks at the status of the CRD.  Definitely interested in what others think about this idea and if others are running into this.

**Comment by agoyal-sfdc** [comment]
@ezimanyi Thanks for the response! I actually think that Spinnaker _should_ timeout if there are no off-band deletes happening. I think it's a reasonable assumption to make that if I as a user want to control the deletes, I will do something to make that happen and would want Spinnaker to wait while I perform those deletes by default. `OnDelete` is a native Kubernetes feature and it seems like Spinnaker is lacking support for it. Having said that, I do agree with you that an annotation would certainly be a good compromise since I can see the desire to not inflate Spinnaker with such logic by default, but it will provide a way to support this Kubernetes feature for users who do want to make use of it.

We did consider a CRD, but to us, the approach we ended up taking seemed like a much easier way to do things than that.

**Comment by ezimanyi** [comment]
Let me add this to the agenda for our next [Kubernetes V2 SIG](https://github.com/spinnaker/community/tree/master/sig-kubernetes).  If you're able to attend, that would be great, but even if not I'll share the discussion on this issue and see if anyone has any concerns with changing the behavior here (either by default or behind an annotation/flag).  Thanks!

**Comment by agoyal-sfdc** [comment]
Thanks @ezimanyi! I think I will be able to join.

**Comment by ezimanyi** [comment]
We discussed this at the Spinnaker Kubernetes SIG on Dec. 3rd.

The consensus in that meeting was that this would better be handled by a CRD wrapping the StatefulSet, where the controller handles doing the deletes as noted in the issue but also updates the status of the CRD to indicate when it has been fully updated.  Given that we'd encourage future use cases to use that paradigm, and that there is a workaround for this particular case (running a job to wait for the update), there wasn't a strong desire from the SIG to implement this feature.  Based on that feedback, closing the issue.  Thanks again for bringing this up!  I think that it does highlight that we need to think a bit more about how to handle updates of stateful services in Spinnaker.
