### ISSUE TITLE
Request: Warn when docker-image tag regex does not match any existing tags

### ISSUE THREAD

**Issue by bgehman** [spinnaker/spinnaker#5233]
### Feature Summary:
Kinda got bit by #3011 :
> If a user enters a normal string, it must match exactly for the artifact to match (b/c the back-end is effectively treating the `inputstring` as the regex `^inputstring$`)

It would be handy if the GUI checks the regex, and warns if there are no tags that matches the user's supplied regex.  Maybe even go so far as to not allow a regex that is not matching any tags at all, as it is clearing a misconfiguration issue and triggers will never activate.

* Example tag: `master-10` (ie, `master` branch, build `10`).
* User gives a tag specification of `master`, unknowingly that it is internally treated as `^master$`.  

User left scratching their head trying to figure out why the trigger doesn't fire.  If the UI could warn that there are no matching tags, it would impressively increase usability.  Many thanks!

**Comment by maggieneterval** [comment]
@bgehman thank you so much for taking the time to write up this issue. These are exactly the types of pain points that it's super helpful to report about Spinnaker, since countless other people were probably confused by this but never reported it as a problem. I've updated our match artifact docs to clarify the regular expression behavior (https://github.com/spinnaker/spinnaker.github.io/pull/1672), and we'll link to the updated docs from the tooltip beside the Match Artifacts section in Deck (https://github.com/spinnaker/deck/pull/7792). The Kubernetes SIG leads discussed the possibility of querying for matching Docker tags while configuring a pipeline, but determined that we won't be adding that functionality at this time (often, there won't yet be matches to a given regex at configuration time.)

Thanks again for surfacing a confusing user experience; have a great weekend!

**Comment by bgehman** [comment]
@maggieneterval Thanks for considering the proposal, and updating the docs.  👍
