### ISSUE TITLE
Unable to fetch secrets with "Find artifacts from resource" stage

### ISSUE THREAD

**Issue by musabmirza** [spinnaker/spinnaker#5273]
**The tragedy**

I am unable to fetch secret values using **Find Artifacts From Resource (Manifest) ** stage in spinnaker

**Nitty gritty**

I have a secret `global-secrets` deployed in my `cicd` namespace with key `foo` and value `bar`. So running:

`kubectl get secrets -n cicd global-secrets -o jsonpath="{.data['foo']}" | base64 --decode`

outputs

`bar`

Great.

In spinnaker, I have a **Find Artifacts From Resource (Manifest)** stage named `mysecrets` that fetches the above secret:

![image](https://user-images.githubusercontent.com/8170066/71697116-f9512880-2d84-11ea-8e92-8cabd5e006e6.png)

In the stages coming after, when I try to get the value for the secret name like this:

`${#stage('mysecrets')['outputs']['manifest']['metadata']['name']}`

It works.

However, when I try to get the value of the `foo` key in that secret like this:

`${#stage('mysecrets')['outputs']['manifest']['data']['foo']}`

It doesn't work, and simply spells out the expression:

![image](https://user-images.githubusercontent.com/8170066/71697336-adeb4a00-2d85-11ea-8a85-3873098d2fdb.png)

So then I went into the source json and looked at the `output` part of the `mysecrets` stage:

![image](https://user-images.githubusercontent.com/8170066/71697429-f9055d00-2d85-11ea-8f37-6d27331b79a4.png)

And I notice that the **data** part from the manifest is missing :(

I tried the same with `ConfigMap` and it works, but with secret, spinnaker is not able to load the `data`. 

Any ideas on how to resolve this?

**Comment by maggieneterval** [comment]
Hey @musabmirza, thanks for taking the time to open this issue! The omission of the secret's data from the manifest as cached by Spinnaker is actually intentional in order to ensure the secrecy of your secrets. Each Kubernetes kind handler can specify a list of sensitive keys that Clouddriver will not cache for resources of that kind (see [`KubernetesSecretHandler`](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesSecretHandler.java#L48)).

If there's some problem you're trying to solve by accessing the secret's data from within your Spinnaker pipelines that you'd like to brainstorm other workarounds for, we'd love to have you attend the Kubernetes SIG ([meeting details](https://github.com/spinnaker/governance/blob/master/sig-kubernetes/README.md))! Alternately, the #sig-kubernetes Slack channel is another great resource.

**Comment by musabmirza** [comment]
Hi @maggieneterval , thanks for the explanation. Makes sense. I know Spinnaker integrates with Vault and Spring Cloud to fetch its own service configs, but it is possible to integrate with them to fetch custom application level configuration? In short, how do you externalize pipeline dynamic parameters in spinnaker? Is there some documentation?

**Comment by maggieneterval** [comment]
Great question, @musabmirza, I'm not sure if/now other Spinnaker/Kubernetes operators are hydrating parameters in Spinnaker pipelines with sensitive configuration -- would definitely be a great discussion for the SIG if you'd like to join!
