### ISSUE TITLE
Kubernetes V1 vs V2 feature parity: Red/black strategy for replicasets

### ISSUE THREAD

**Issue by emptywee** [spinnaker/spinnaker#5312]
### Issue Summary:
@maggieneterval asked me to open this as a github issue after discussing it on Slack. Here it goes...

In order to smoothly migrate from Kubernetes V1 to Kubernetes V2 it would be nice to have a way to mimic the behavior that was possible with V1. In particular, this:

![image](https://user-images.githubusercontent.com/4997180/72358892-ec043a00-36b2-11ea-9999-7dea800335ce.png)

### Cloud Provider(s):
Kubernetes V2

### Environment:
Spinnaker 1.16.5 on self-hosted on-prem Kubernetes cluster.

### Feature Area:
Pipelines, orca.

### Description:

I wasn't able to find any way to make V2 do the same thing as V1 does. There's a "Scale (Manifest)" stage for this, but it doesn't have the option to scale all disabled or all old server groups.

![image](https://user-images.githubusercontent.com/4997180/72359563-1acee000-36b4-11ea-9c31-a0ca9e1b0313.png)

What V1 does, if that checkbox is ticked as shown in the very first screenshot, is: it scales down all server groups other than the newly deployed, regardless whether they are second newest or third/fourth newest. Which means that if even if you had interrupted executions of the pipeline for any reason and any lingering pods of old server groups, they would all be nicely cleaned up by scaling to 0 after successful pipeline execution.

### Steps to Reproduce:

1. Create a pipeline with a "Deploy (Manifest)" stage and replicaset as the manifest.
2. Select red-black strategy. There will be no options to scale down previous server groups to zero. Nor that can be tuned with annotations (at least I could not find any in the docs).

**Comment by dbyron0** [comment]
My first reflex when I read this is, why not use a deployment instead of a replicaset?  Wouldn't that scale down all the old replicasets?

I suppose adding logic to V2 to give it parity with V1 in this area makes sense in the spirit of easing migration for people.  It feels not so great to re-implement something kubernetes already has a first-class way of going though.

**Comment by emptywee** [comment]
@dbyron0  well, true, but imagine us having 400+ apps deployed and all scripts and automation created around it besides Spinnaker itself. All those things would need to be immediately re-written to support deployments on top of replicasets.

It doesn't look like a big change to modify the scale manifest stage to dynamically pick all disabled server groups, but it would be a great help for us (and others who are in our position) to migrate to V2.

**Comment by dbyron0** [comment]
I have no doubt the struggle is real, and that this logic would ease it.

I am curious about the immediately re-written part though.  Is there some other barrier to using the V2 provider along with V1 now, and migrating more gradually?

**Comment by emptywee** [comment]
@dbyron0 I meant the automation/scripting part that has been developed outside of Spinnaker's territory. It has been developed taking into account that opinionated way of deployments that the Kubernetes V1 provider imposed on us, those scripts and automation expect to see replicasets of applications and groups of applications (microservices), let alone audit and other reporting tools. Perhaps, some Grafana dashboards will also need to be re-designed for deployments. Canary configs as well. It's just what comes into my mind if we suddenly start using deployments.

Perhaps, we are not alone with those kind of challenges on the path to Kubernetes V2.

If Spinnaker team decides that it is not worth adding this feature, I'd like to know that and invest time into searching for other options sooner than later :)

**Comment by dbyron0** [comment]
I had a feeling I was going to make a mess with my comment.  Apologies for that.  And if it wasn't obvious, my comments aren't official in any way.  Just another spinnaker user.

**Comment by maggieneterval** [comment]
@emptywee thanks again for opening this issue! The Kubernetes SIG leads talked about this at the issue triage meeting today and would echo @dbyron0's recommendation to use Deployments instead of ReplicaSets with the V2 provider if you'd like older versions to be scaled down to 0 replicas automatically.

We appreciate that there will be some toil to replace ReplicaSet-based assumptions in any custom tooling you've built around Spinnaker, but we want to avoid re-implementing any functionality in Spinnaker that's available natively in Kubernetes. The red/black (or blue/green) functionality available in V2 is meant to enable the types of rollouts that are _not_ currently available as built-in Deployment strategies: 1) previous versions are disabled but not scaled down, in order to enable a quick rollback in case there are issues with the new version 2) new version is deployed and scaled up, but not yet accepting traffic ("dark" deploy). If all you need is the built-in "recreate" Deployment strategy, we'd recommend sticking with Deployments.

Definitely keep us posted on how the migration progresses and if you run into any other snags that might affect other users -- would love to include them in the upcoming blog post announcing the V1 deprecation!

**Comment by emptywee** [comment]
@maggieneterval that's all I needed to know. We've decided to go with the Deployment kind in V2.
