### ISSUE TITLE
Google Groups Authorization doesn't work for groups of groups

### ISSUE THREAD

**Issue by kunickiaj** [spinnaker/spinnaker#5366]
### Issue Summary:
It appears that a user's profile is checked directly for group memberships. This means that transitive memberships are not reflected.

### Environment:
Spinnaker deployed with halyard on GKE.
Fiat configured with G Suite for Authorization.

### Feature Area:
Authorization

### Description:
It is a common authorization pattern to have groups that contain other groups creating a hierarchy. This does not currently work with Spinnaker. Only members directly added to a group are authorized.

### Steps to Reproduce:
Create two google groups, e.g. parent-group and child-group. Add a user to child-group. Add child-group as a member of parent-group.

Authorize parent-group in Spinnaker for an application. The user in child-group will not have access.

**Comment by kunickiaj** [comment]
(I was not able to choose any labels when creating/editing the issue)

**Comment by plumpy** [comment]
It looks like this is another casualty of the confusing design decision where Fiat is expected to return all possible roles for a user upon request, rather than a more typical "does user X have permission Y" API.

So we have to use the Google Groups API that [lists all groups a user belongs to](https://developers.google.com/admin-sdk/directory/v1/reference/groups/list) (which cannot be done transitively) rather than the [does group X contain user Y API](https://developers.google.com/admin-sdk/directory/v1/reference/members/hasMember) (which can).

Short of rearchitecting of fiat, I don't think this something we can realistically fix, unfortunately.

Sorry for the bad news.

**Comment by psalaberria002** [comment]
Could we look up the groups recursively?

Check direct parent groups, and for each group check its parent groups by putting the resulting groups into a set. Did I miss something?
