### ISSUE TITLE
Spinnaker upgrade 1.16.6 -> 1.17.6: firewalls (ingresses) are not displayed in UI

### ISSUE THREAD

**Issue by sesto** [spinnaker/spinnaker#5480]
### Issue Summary:
After upgrading Spinnaker 1.16.6 -> 1.17.6 the firewalls are not shown in UI.

### Cloud Provider(s):
Kubernetes cloud provider v1

### Environment:
Spinnaker is running in GKE

### Description:
After upgrading Spinnaker 1.16.6 -> 1.17.6 the firewalls (actually k8s ingresses) are not shown in UI anymore. In the browser console, we can see the following javascript errors:

![image](https://user-images.githubusercontent.com/3634876/75021569-ed383c00-5494-11ea-84ed-8231d9f0d6ee.png)

### Steps to Reproduce:
In Spinnaker 1.16.6 with kubernetes cloud provider v1, create a firewall (ingress). Check that it is shown in the UI after creation

![image](https://user-images.githubusercontent.com/3634876/75021986-97b05f00-5495-11ea-96ba-5bf92a4d6c9d.png)

Upgrade Spinnaker to 1.17.6. See that the firewall is not shown anymore
![image](https://user-images.githubusercontent.com/3634876/75022137-d514ec80-5495-11ea-8214-19fabb5e3a13.png)

Open the console in a browser and observe the aforementioned javascript errors

**Comment by maggieneterval** [comment]
Hi @sesto, thanks so much for taking the time to open this issue. I think we've already resolved the UI issues with the Firewalls tab, but we failed to cherry-pick the fixes back into each supported release. I'll take care of that now. Definitely let us know if you're still experiencing this issue after upgrading to either 1.17.7, 1.18.5, or 1.19.0.

Separately, since you're using the V1 provider, I wanted to highlight that we are removing support for the V1 provider in release 1.21. Please see our [RFC](https://github.com/spinnaker/governance/blob/master/rfc/eol_kubernetes_v1.md) for more details, and feel free to join the [#kubernetes-v2-migration Slack channel](https://join.spinnaker.io/) if you'd like to connect with other Spinnaker users planning a migration from the V1 to the V2 provider.

Thank you!
