### ISSUE TITLE
ECS: Unstable deployment when there are more than one container in task definition

### ISSUE THREAD

**Issue by atyutyunnik** [spinnaker/spinnaker#5544]
### Issue Summary:
ECS: Unstable deployment (alternating between successful and hanging) when there are more than one container in task definition. AWS ECS clouddriver checks only the very first container for networking interface/bindings and those may be present in other containers.
...

### Cloud Provider(s):
AWS ECS

### Feature Area:
Clouddriver, ECS

### Description:
This code assumes that network interface/bindings are returned in the very first container:
if (task.**getContainers().get(0)**.getNetworkBindings().size() >= 1) {
...
but the order of containers may vary from deployment to deployment. As a result, some deployments -- where containers with network interface/bindings are not present in the zeroth container but in other -- will never finish and will eventually time out

### Steps to Reproduce:
Have two containers: one with network interface/binding, another as a sidecar. Deployments will be unstable, as I said, sometimes succeeding and sometimes hanging until timing out on  "Wait For Up Instances" step. LoadBalancer will show Unknown, despite task successfully running

### Additional Details:
Attached is a patch
[issue_fix_proposal.patch.txt](https://github.com/spinnaker/spinnaker/files/4296455/issue_fix_proposal.patch.txt)

**Comment by atyutyunnik** [comment]
by the way, I have tested the patch in my environment and appears to fix the issue

**Comment by allisaurus** [comment]
Thanks @atyutyunnik ! Are you able to submit it as a pull request so we can review / merge through that channel?

**Comment by atyutyunnik** [comment]
@allisaurus, do I have sufficient permission for this project? I can pull with my ssh key alright, but a push is denied.

**Comment by allisaurus** [comment]
If you've [forked](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) clouddriver, you can [create a pull request from your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) to the upstream repo (spinnaker/clouddriver). 

This is the best way to request and review changes because we can collaborate on them together and in the open. However, if you're not in a position to do this let me know and we can work out another way to get it in. Thanks either way for submitting this!

**Comment by atyutyunnik** [comment]
truly sorry for my earlier mess with the initial PR#4407

**Comment by allisaurus** [comment]
Closing as this fix is available in [1.19.1](https://www.spinnaker.io/community/releases/versions/1-19-1-changelog) 🎉 

Work to patch to 1.18.x : https://github.com/spinnaker/clouddriver/pull/4411
