### ISSUE TITLE
Deck not able to update the data on json file

### ISSUE THREAD

**Issue by rampatnaik** [spinnaker/spinnaker#5567]
### Issue Summary:
Deck not able to update the data on json file

### Cloud Provider(s):
Kubernetes

### Environment:
1.17.6 / GCP

### Feature Area:
deck & gce , UI

### Description:
In UI i have changes the product Arttifacts -> match against -> kind Base64
but on Json history  : it shows Kind = ""

### Additional Details:

I need to select 2 time base64 to update on UI to reflect  the value on json

**Comment by rampatnaik** [comment]
![image](https://user-images.githubusercontent.com/7654375/76592382-340bd580-6519-11ea-8435-5605ea1dc917.png)

**Comment by rampatnaik** [comment]
"expectedArtifacts": [
    {
      "defaultArtifact": {},
      "id": "dfc2953e-bacf-4464-8b40-111e1d8d1aec",
      "matchArtifact": {
        "kind": "",
        "name": "",
        "type": "embedded/base64"
      },
      "useDefaultArtifact": false

**Comment by rampatnaik** [comment]
after  reedit the kind i can see the value 
  "expectedArtifacts": [
    {
      "defaultArtifact": {},
      "id": "dfc2953e-bacf-4464-8b40-111e1d8d1aec",
      "matchArtifact": {
        "kind": "base64",
        "name": "",
        "type": "embedded/base64"
      },
      "useDefaultArtifact": false

**Comment by maggieneterval** [comment]
Hi @rampatnaik, thanks for taking the time to open this issue!

My (perhaps incorrect) understanding is that `kind` was a deprecated artifact property, and that only `type` was now required (here's the [code](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/domain/IArtifact.ts#L12) that made me think that).

I'm not able to reproduce the issue of `kind` only being set after selecting "Base64" from the Match Artifact dropdown twice, but I'm curious if you noticed any issues that arose as a result of only `type` being set rather than `kind`. If so, it would be very helpful if you could open separate issues for those!

As a separate note on artifacts, we are currently in the process of deprecating the legacy artifacts UI in favor of a new UI, which is currently behind the [`artifactsRewrite`](https://www.spinnaker.io/guides/user/pipeline/triggers-with-artifactsrewrite/) feature flag. You can read more about that effort [here](https://github.com/spinnaker/governance/blob/master/rfc/legacy_artifacts_ui_removal.md).

Thanks again!
