### ISSUE TITLE
Clouddriver adds unique suffix to job names and cannot be switched off

### ISSUE THREAD

**Issue by ronanbarrett** [spinnaker/spinnaker#5599]
### Issue Summary:
There is an assumption that jobs created by Spinnaker should always have a unique name. This is not as expected and it is not documented. Kubernetes already has a feature to support unique naming of jobs "generateName" which people can use to get unique suffixes added to job name. As it is now it is impossible to use a static job name which is desirable when you want to reuse the same job name combined with the Spinnaker annotation strategy.spinnaker.io/recreate: 'true'. 

### Cloud Provider(s):
GCP/k8s

### Environment:
1.17.3 (also in master branch)

### Feature Area:
clouddriver-kubernetes-v2

### Description:
It is clear from https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubernetesRunJobOperation.java and specifically https://github.com/spinnaker/clouddriver/blob/334375e84269bfc15156ef504de5766b725f58b6/clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/job/KubernetesRunJobOperation.java#L66 that there is an assumption that job names should be uniquely suffixed by Spinnaker. This is unexpected and not documented as if I define a Job manifest with a name I expect that exact name to be used. If I wanted a unique name I would define a "generateName" on the manifest instead of "name". The current Spinnaker behaviour is unexpected as it deviates from the manifest I provide.

The negative side effect of Spinnaker's behaviour is that an extra stage is required to delete the jobs just created.

### Steps to Reproduce:
1. Define a k8s job manifest
2. Create a pipeline to deploy the manifest
3. Observe the name has a unique suffix added to the name provided

When creating the job using kubectl it will not have the suffix added.

### Additional Details:

---

**Comment by ghostsquad** [comment]
I've noticed the same thing for configmaps. The documentation talks about this a little bit, but like much of the other documentation for spinnaker, it's severely lacking.

https://www.spinnaker.io/reference/artifacts/in-kubernetes-v2/

basically, I don't want spinnaker to "bind" artifacts together. I'm already versioning them, and binding them, and providing them to spinnaker as a b64 artifact.

I don't see any mechanism to turn this off. Additionally, this is actually a pretty big bug if you are using configMaps for environment variables, since kubernetes doesn't require you to mount the configmap as a volume in order to use it for env vars:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/pod-configmap-envFrom.yaml

yet, the spinnaker documentation doesn't notice that the configmap is used this way, so when it adds a `-v000` suffix, the pod spec is broken, as it's not referencing the now new configmap name.

**Comment by ezimanyi** [comment]
@ronanbarrett : Thanks for opening this!  The request seems reasonable, though my only concern is breaking people who are relying on the existing behavior (as they'd then need to change all of their job manifests to use `generateName` instead of `name`).  I've added this to the agenda for the [Kubernetes SIG ](https://github.com/spinnaker/governance/tree/master/sig-kubernetes) tomorrow.  If you are able to make it you're definitely welcome to join the discussion, but I will see if there are any objections there to moving forward with this (with the caveat that existing users would need to change their jobs as noted above).

**Comment by ghostsquad** [comment]
@ezimanyi I think what @ronanbarrett and I are talking about here is to allow greater control over the behavior of _spinnaker_ itself, unrelated to how the manifests look. The "binding" and "versioning" behavior should just have some flag option to disable on a per stage or per manifest basis.

**Comment by ezimanyi** [comment]
@ghostsquad : I think your issue might be a bit different than the issue here.  This issue is very specifically about how we add an explicit to all jobs deployed with the Kubernetes V2 job stage (which is not something we do in this way for any other deploy).

It looks like you might be trying to use the [versioning](https://www.spinnaker.io/reference/providers/kubernetes-v2/#resource-management-policies) feature or turn it off for some other resource types.  If you are finding bugs with that, can you please open a new issue to keep this one focused on the issue with adding a suffix to the run job stage?  Thanks!

**Comment by ezimanyi** [comment]
To update on the question around whether clouddriver should be adding a suffix to all jobs, we discussed this at the Kubernetes SIG today.  I proposed the tentative plan of:
* Jobs that have a `name` are applied using the `recreate` policy (ie, `delete` followed by `apply`) and re-use the same name each time
* Jobs that have a `generateName` are created as-is, and Kubernetes handles adding a suffix to the name.

This *will* mean that users who currently have jobs configured with a `name` and want to keep having a unique suffix added will need to change their jobs to instead provide a `generateName`.  Nobody in the SIG today objected to that change, but I'll bring it up again at a future SIG again just to be sure, but in the meantime think we can go ahead and implement this.

**Comment by ghostsquad** [comment]
@ezimanyi will do

**Comment by kmurthyms** [comment]
We are facing an issue due to this random suffix ,in cleanup of jobs as we were using "strategy.spinnaker.io/recreate" to clear of the jobs. Any workarounds to overcome this issue ?

**Comment by ezimanyi** [comment]
As of Spinnaker 1.20.3 there is a flag you can enable to stop having Spinnaker append a suffix to jobs; this will become the default behavior in Spinnaker 1.22.  There are more details [here](https://github.com/spinnaker/spinnaker.github.io/blob/dda2245634d1581ae8c4de37b0af59d9ae9e9f24/community/releases/next-release-preview/index.md#breaking-change-suffix-no-longer-added-to-jobs-created-by-kubernetes-run-job-stage).
