### ISSUE TITLE
Support for Spinnaker to assume a resource will exist.

### ISSUE THREAD

**Issue by dpolicastro** [spinnaker/spinnaker#5604]
### Issue Summary:
Many stages of the pipeline requires a resource to be specified to receive the action, for example a service (Load Balancer) in `Deploy (Manifest)` stage when using Red/Black... Or a deployment in the stage `Undo Rollout`. 
But when you are deploying the resources for the first time, this causes the pipeline stages to fail if this resources doesn't exist. 

For example, I will deploy a **service** and a **replicaSet** object in the same manifest. They are baked in the Bake stage and deployed in the next one.

![image](https://user-images.githubusercontent.com/29067941/77181203-c1b36c00-6aa9-11ea-826a-463ec3fecc03.png)

> **But if my pipeline is configured like the image below, since the resource doesn't exist yet, it will fail.**

![image](https://user-images.githubusercontent.com/29067941/77181488-28d12080-6aaa-11ea-816c-081b2702b7f5.png)

![image](https://user-images.githubusercontent.com/29067941/77183017-777fba00-6aac-11ea-969f-570d30614c11.png)

I missed something? How people are addressing this?

### Cloud Provider(s):
AWS/K8s

### Environment:
Spinnaker 1.19.1

**Comment by maggieneterval** [comment]
Hi @dpolicastro!

Using Spinnaker's rollout strategies does require that the Service already exist, because Spinnaker needs to read the label selectors from this Service in order to add them to the associated ReplicaSet.

That said, it is indeed a very common use case to deploy multiple resources for the same application in one multi-manifest, which is why work is underway to add[ filter-by-label functionality](https://github.com/spinnaker/spinnaker/issues/3695) to the Deploy (Manifest) stage. Once that feature is released, you could use the same manifest in multiple deploy stages, but filter by label to ensure they are deployed in a certain order. So in your case you could have one deploy stage filtering only for the Service, and a subsequent deploy stage for the ReplicaSet.

I've noticed that you've opened several Kubernetes-related issues recently; we would absolutely love to have you attend our next [Kubernetes SIG meeting](https://github.com/spinnaker/governance/blob/master/sig-kubernetes/README.md). I think you'd find it really valuable as most of the discussion is generated by other operators who discuss best practices around deploying to Kubernetes with Spinnaker. Hope to see you at a meeting!

**Comment by shubhamc183** [comment]
@dpolicastro any workaround for this? As https://github.com/spinnaker/spinnaker/issues/3695 is still in WIP.

**Comment by agoyal-sfdc** [comment]
> @dpolicastro any workaround for this? As #3695 is still in WIP.

@shubhamc183 we're currently using a workaround mentioned here https://github.com/spinnaker/spinnaker/issues/5182
