### ISSUE TITLE
Spinnaker installation : ERROR Could not load "versions.yml" from config bucket:   www.googleapis.com.

### ISSUE THREAD

**Issue by bilalsbl** [spinnaker/spinnaker#5636]
Hi,
before installing spinnaker, i am required to list the available versions by running below command

hal version list

output:
_+ Get current deployment
  Success
+ Get Spinnaker version
  Success
- Get released versions
  Failure
Validation in Global:
! ERROR Could not load "versions.yml" from config bucket:
  www.googleapis.com.

- Failed to load available Spinnaker versions._

please help me fix this problem. 

environment:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

document being referred to setup spinnaker
   https://www.spinnaker.io/setup/

hal -v 
1.33.0-20200325200017

**Comment by plumpy** [comment]
Thanks for filing this issue. It looks like this might be a request for help rather than a bug. In that case, you're probably better off looking for answers [from our Slack community](https://join.spinnaker.io/), since there is a larger pool of users there. Use the search functionality to find users who have a similar experience, or post a message in `#general` or another related channel.
