### ISSUE TITLE
Is the skipExpressionEvaluation during deploy broken

### ISSUE THREAD

**Issue by raghvendra-v** [spinnaker/spinnaker#5701]
### Issue Summary:
My helm (umbrella) package contains lot of bash scripts and config xmls. Despite checking `Skip SpEL expression evaluation` option in the deploy stage. It is trying to evaluate ${`expressions`} in scripts and xmls

### Cloud Provider(s):
kubernetes ( Oracle Container Services  v1.11.3)

### Environment:
Spinnaker 1.19.0 & 1.19.5

### Feature Area:
helm2 deploy manifest

### Description:
Despite checking `Skip SpEL expression evaluation`  during deploy manifest stage spinnaker tries to evaluate shell expression and fails. the artifact was produced during previous bake using helm2.
![pipeline-logs](https://user-images.githubusercontent.com/20955618/79888967-00c33d00-841b-11ea-869d-ad990a7f36da.png)

the pipeline status
![spinnaker-deploy-SpEL](https://user-images.githubusercontent.com/20955618/79889019-0fa9ef80-841b-11ea-8bd7-34bc3aab0d23.png)

Full logs are available [here](https://raw.githubusercontent.com/raghvendra-v/fantastic-spoon/master/01E6EN41RWF0X2DEV5YW42T0Y3.json)
### Steps to Reproduce:
just bake helm image `stable/elastic-stack 2.0.0` and skip SpEL during deploy phase.

### Additional Details:
I have tested on spinnaker 1.19.5 and downgraded to 1.19.0. Both show this issue.

---

**Comment by maggieneterval** [comment]
Hi @raghvendra-v! Thanks for opening this issue.

I've just tested baking and deploying a Helm manifest with `${}`-wrapped expressions and confirmed that the pipeline fails when "Skip SpEL expression evaluation" is unchecked, and the pipeline passes when "Skip SpEL expression evaluation" is checked.

Your pipeline seems to be failing at the "Monitor Deploy" task, which is not a task that should be affected by the "Skip SpEL expression evaluation" functionality. Could you please send the full execution details of this pipeline and the Orca and Clouddriver logs from the time of this exception (with any sensitive information removed)? The link you provided in the issue seems to no longer be working.

Thank you!

**Comment by szarya** [comment]
I've encountered a similar problem when deploying a helm chart that includes an nginx configuration. It happened on Amazon EKS, so it's not provider specific. It feels like certain features are implicitly re-enabling SpEL evaluation. 
Specifically I was able to reproduce when either:
1. Using spinnaker to override the namespace.
2. Deploying a versioned replica set as well as a suspect ConfigMap in the same chart.
I ended up side-stepping the issue by splitting the chart into two, and deploying the ConfigMap in a separate step.

**Comment by maggieneterval** [comment]
Thanks for the additional context, @szarya! If you're able to share some minimal pipeline JSON (with any sensitive data removed, of course) that causes this issue for either of the two cases you mentioned, that would be super helpful!

**Comment by kskewes** [comment]
This might be related to https://github.com/spinnaker/spinnaker/issues/5626

**Comment by maggieneterval** [comment]
Thanks for pointing that out, @kskewes! For those not following the conversation on that issue, [this comment](https://github.com/spinnaker/spinnaker/issues/5626#issuecomment-613729817) provides a great explanation of the root cause of these types of SpEL issues, and the work planned to hopefully mitigate them.

In the meantime, if there are any cases you think are a regression from one supported Spinnaker version to another, please share a (sanitized) version of your pipeline JSON / manifests and I'd be happy to investigate!

**Comment by chirangaalwis** [comment]
Facing the same issue with Spinnaker Helm chart version `1.22.0`. Even when the `Skip SpEL expression evaluation` is enabled.
