### ISSUE TITLE
Pipeline stage for "helm upgrade" but reuse previous values

### ISSUE THREAD

**Issue by max-rocket-internet** [spinnaker/spinnaker#5704]
### Issue Summary:

Allow for upgrading a Helm release and reuse values. This is a feature of Helm:

```
--reuse-values  when upgrading, reuse the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' is specified, this is ignored
```

### Cloud Provider(s):

Kubernetes and Helm render engine

### Environment:

Kubernetes

### Feature Area:

Kubernetes/Helm

### Description:

We have quite large and complicated chart values. Not simply a few key/value pairs. It would be good if Spinnaker could do this:

```
helm upgrade my-app-release path/to/my/chart --reuse-values --set deployment.image.tag=<my new app version>
```

This would mean we can just leave our large values files out of Spinnaker, and the encrypted values files also, and just use Spinnaker to change the deployment container image.

**Comment by maggieneterval** [comment]
Hi @max-rocket-internet! Thanks for taking the time to open this feature request.

Going to close this for now since we do not have any plans to support `--reuse-values`. Spinnaker's Kubernetes provider generally tries to encourage patterns where deployments don't have any dependencies on past deployments. That said, for situations where you need to simply patch the container image, I'd recommend checking out the Patch (Manifest) stage.
