### ISSUE TITLE
Halyard not starting

### ISSUE THREAD

**Issue by girisha-g** [spinnaker/spinnaker#5705]
### Issue Summary:
! ERROR Failed to connect to localhost/127.0.0.1:8064
? Is your daemon running?

### Description:
Halyard stopped working suddenly

**Comment by maggieneterval** [comment]
Hi @girisha-g, thanks for taking the time to open this issue! For operational troubleshooting, I'd recommend posting in [Spinnaker Slack](https://join.spinnaker.io/); the #dev, #general, or #operations channels would be a great place to start. Closing this issue for now since we try to reserve GitHub issues for bug reports or feature requests. Thanks!

**Comment by ezimanyi** [comment]
I broke this...don't tell anyone!  Fix coming shortly.

**Comment by ezimanyi** [comment]
The fix has now been released in Halyard 1.35.2---sorry for the inconvenience!
