### ISSUE TITLE
VerticalPodAutoscaler (VPA) cannot be deleted by deleteManifest stage

### ISSUE THREAD

**Issue by karlkfi** [spinnaker/spinnaker#5735]
### Issue Summary:
VerticalPodAutoscaler (VPA) cannot be deleted by deleteManifest stage.

### Cloud Provider(s):
Kubernetes v2

### Environment:
GKE

### Feature Area:
Kubernetes

### Description:
The KubernetesKind definitions do not include VerticalPodAutoscaler and thus, it cannot be deleted.

https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesKind.java

### Steps to Reproduce:
```
  "stages": [
    {
      "account": "{{.Env.CLUSTER}}:{{.Env.NAMESPACE}}",
      "app": "{{.Env.APP}}",
      "cloudProvider": "kubernetes",
      "kinds": [
        "VerticalPodAutoscaler"
      ],
      "labelSelectors": {
        "selectors": [
          {
            "key": "app.kubernetes.io/name",
            "kind": "EQUALS",
            "values": [
              "{{.Env.APP}}"
            ]
          }
        ]
      },
      "location": "{{.Env.NAMESPACE}}",
      "mode": "label",
      "name": "Delete (All)",
      "options": {
        "cascading": true
      },
      "refId": "0",
      "stageEnabled": {
        "expression": "parameters['DELETE'] == 'true'",
        "type": "expression"
      },
      "type": "deleteManifest"
    }
  ]
```

Confusingly, the VPA is in a different api group than HPA: `apiVersion: autoscaling.k8s.io/v1beta2`

**Comment by maggieneterval** [comment]
Hey @karlkfi, thanks for opening this issue, and sorry for the slow followup. I think there are two separate issues here:

1. As you mentioned, VerticalPodAutoscaler is not a kind for which Spinnaker includes a built-in `KubernetesHandler`, so it is not a member of the Spinnaker-Kubernetes kind map associated with each account, whose entries are what Deck surfaces as selectable Kinds options in the Delete (Manifest) stage.
2. If you were to directly edit the stage JSON to include VerticalPodAutoscaler, you would run into a different problem, with Clouddriver throwing an error similar to that described in [this issue](https://github.com/spinnaker/spinnaker/issues/4237).

Luckily, you can resolve both (1) and  (2) by updating your Kubernetes account configuration (in your halconfig if you are using Halyard) to include the following:
```
  customResources:
    - kubernetesKind: VerticalPodAutoscaler.autoscaling.k8s.io
       versioned: false
```

I've just tested to ensure this works, and you should be able to both select VerticalPodAutoscaler as a kind in the UI, and have Clouddriver successfully delete it:

![jYVkEPJVf8S](https://user-images.githubusercontent.com/15936279/83266476-e1919b00-a190-11ea-8f3b-17797079b3f5.png)

As discussed in the issue I linked previously, perhaps a more robust solution would involve refactoring Clouddriver such that it can dynamically create handlers for custom resources when appropriate rather than requiring explicit registration. I think we would also accept a contribution to add a built-in handler for VerticalPodAutoscaler to Clouddriver, though if you're interested in that, we should probably discuss at the Kubernetes SIG since we've been having a broader conversation around what extension points Spinnaker should expose in terms of CRD handling, and what should live in core code vs. plugins, and as far as I know there is not currently an explicit policy of which resource types should have built-in handlers.

Please let me know if the workaround of registering this resource in your config does not at least unblock you from deleting VPAs with Spinnaker. Thanks!

**Comment by maggieneterval** [comment]
Haven't heard back on this issue in a bit, so I'm hoping that registering VPAs in your config as I documented in my previous comment has unblocked you from using the Delete (Manifest) stage with VPAs. I am going to close this issue for now, but agree that the user experience for working with CRDs in Spinnaker is not ideal, and we need to put thought into a more flexible longer-term solution.

**Comment by dbyron-sf** [comment]
I believe https://github.com/spinnaker/clouddriver/pull/5334 fixed this even if VerticalPodAutoscaler isn't a registered kind.
