### ISSUE TITLE
[ECS] Deck doesn't show instance status correctly

### ISSUE THREAD

**Issue by awsiv** [spinnaker/spinnaker#5741]
### Issue Summary:
Deck doesn't show instance status correctly

### Cloud Provider(s):
ecs

### Environment:
debian local install
spinnaker 1.20.0
ECS/fargate with service discovery enabled

### Feature Area:
spinnaker/deck

### Description:
When deploying ECS cluster with Service Discovery enabled, UP status is reported incorrectly in deck.

Starting and Down are reported correctly
Starting:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/1265825/81214030-875d4a00-8fd7-11ea-8944-055b0419d786.png">

UP (cluster/instance is green):
<img width="375" alt="image" src="https://user-images.githubusercontent.com/1265825/81214073-9643fc80-8fd7-11ea-8f33-a080b2e02b40.png">

### Steps to Reproduce:
Enable service discovery for ECS service

**Comment by pkandasamy91** [comment]
@awsiv thanks for reporting this issue. This issue arises from https://github.com/spinnaker/clouddriver/blob/master/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/services/ContainerInformationService.java#L153-L154, in which the platformHealthState is set to unknown. 

We can make a change to update the behaviour to another status such as `RUNNING` but, we will need to investigate further to understand what(if any) the repercussions might be if we update the state to be something different. For instance, if Orca and/or any other Spinnaker services are expecting unknown in order to mark a deployment/task as successfully running.
