### ISSUE TITLE
Feature Request: Surface Identifiers of Kubernetes Resources created by Run Job/Deployment stages

### ISSUE THREAD

**Issue by clanesf** [spinnaker/spinnaker#5793]
### Issue Summary:
When executing a Run Job or Deploying a manifest, we have run into a scenario where resources are created but the individual pods fail to start for whatever reason and then we must go and hunt through the Infrastructure/Cluster tab or pipeline execution (source) to determine what jobs/pods were created by Spinnaker when the pipeline fails.

It would be a huge help if the Spinnaker UI would surface the pod name/ job name for Run jobs and resources in general for Deployments as the Orchestrator gets these back from the API somewhere in the stage UI. 

We have a pretty decent amount of users using our Spinnaker installation, and it would be helpful if they were able to tell that the problem is not with Spinnaker but rather with their clusters when a run job or deployment fails, especially if it's stuck in a Pending stage or whatever.

The AWS provider already does a good job of doing this for EC2 instances by providing a quick link to the Infrastructure tab with that particular instance's version, it would be great if the Kubernetes provider had feature parity in this way. 

### Cloud Provider(s):
Kubernetes

### Feature Area:
Stage UI

**Comment by maggieneterval** [comment]
Hey @clanesf, thanks for the feature request!

I think that this [RFC](https://github.com/spinnaker/governance/pull/94/files) to enhance the Kubernetes provider UI does partially cover jobs, but we can definitely leave this issue open as well for community discussion, especially since that RFC is not currently being implemented by anyone.

Adding the contributions-welcome label for now, but will update here if anyone on my team picks up work on that RFC!

**Comment by maggieneterval** [comment]
Looks great, @evansb! 🎉 We'd definitely accept a contribution for this!
