### ISSUE TITLE
Deck no longer loads the infrastructure views for the ECS provider

### ISSUE THREAD

**Issue by pkandasamy91** [spinnaker/spinnaker#5800]
### Issue Summary:
Using the master branch, Deck no longer loads the infrastructure view (Clusters, Load Balancers and Firewalls) after updating to commit 02bb70123b88640e70f931cd4b5c94b442e05639. 

### Cloud Provider(s):
ECS (potentially other providers as well)

### Description:
After pulling down the latest commits in deck (master branch), the infrastructure views have stopped loading the cluster filters as well as the actual clusters, load balancers and firewalls. After further investigation, From reverting several commits, it appears that commit 02bb70123b88640e70f931cd4b5c94b442e05639 has caused the views to stop loading correctly.

### Steps to Reproduce:
Set up server groups, load balancers and firewalls for use with the ECS provider, and try to load the infrastructure view (you will not see any values populates, and the cluster filters will not load).

**Comment by caseyhebebrand** [comment]
There was a subsequent PR to address a ui-router rendering problem. It belongs with @spinnaker/core 0.0.477, so make sure you are running with the latest version. 

If you can provide any additional context, such as any errors that are logged or explicit steps to get to this state, that would be helpful.

**Comment by pkandasamy91** [comment]
Fix has been merged: https://github.com/spinnaker/deck/pull/8316

**Comment by pkandasamy91** [comment]
The main view is fixed, but it now looks like the detail views are not loading because appIsReady is false. Not sure what's changed.

**Comment by caseyhebebrand** [comment]
@pkandasamy91 So this is a direct conversion from Angular's ng-if statement. Here is the angular code: 
`<div ui-view="detail" class="detail-content" ng-if="$ctrl.ready"></div>`

Here is React code: 
```js
{appIsReady && (
     <div>
          <UIView name="detail" className="detail-content" />
      </div>
 )}
```
My two suggestions: 
1. If we remove this conditional, what happens? Is there an error? I can also check this with my cloud providers. If not we may consider removing the conditional. Maybe it made more sense with angular. 
2. In the `useEffect`, add `[app]` as the second parameter to see if that has any impact to the details section.

**Comment by caseyhebebrand** [comment]
I just checked on my side and I do not see any errors when we remove that conditional. I am fine removing it, pending your finding for #1. Most of the apps I am trying will load fairly quickly so I would like to see what happens with yours as an edge case.

**Comment by pkandasamy91** [comment]
The Cluster view loads, but the Load Balancer, Firewalls and Cluster details views all hang on the Loading bar. The issue looks to be related to the app not loading when the page is rendered. Issue appears to be caused by this commit: https://github.com/spinnaker/deck/commit/72af6cc495cf9f82634f62631bba1f7b6e148eb7

**Comment by maggieneterval** [comment]
Hey @pkandasamy91, [spinnaker/deck@72af6cc](https://github.com/spinnaker/deck/commit/72af6cc495cf9f82634f62631bba1f7b6e148eb7) was all me, so sorry in advance if this is causing issues for you!

I don't have an ECS account to test with, so any additional details would be very helpful -- are you seeing any failed network requests or console errors?

**Comment by pkandasamy91** [comment]
Hey @maggieneterval no worries! I'm seeing 2 errors, one caused by a 404 when deck tries to fetch the plugin manifest (not sure if this would be the cause). 

Seeing the following errors in the console:
`Failed to load /plugins/deck/plugin-manifest.json from gate
data: {…}
error: "Not Found"
message: "No message available"
status: 404
timestamp: 1591029904932`

and 

`TypeError: "this.loadBalancerTransformer.normalizeLoadBalancer(...).then is not a function"
    normalizeLoadBalancer webpack:///./app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts?:41
    loadLoadBalancers webpack:///./app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts?:24
    loadLoadBalancers webpack:///./app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts?:24
    Angular 7
 Possibly unhandled rejection: {}`

**Comment by pkandasamy91** [comment]
Hey @maggieneterval no worries! I'm seeing 2 errors, one of which is an error when deck tries to call normalizeLoadBalancer. 

```
TypeError: "this.loadBalancerTransformer.normalizeLoadBalancer(...).then is not a function"
normalizeLoadBalancer webpack:///./app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts?:41
loadLoadBalancers webpack:///./app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts?:24
loadLoadBalancers webpack:///./app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts?:24

Possibly unhandled rejection: {}
```

**Comment by maggieneterval** [comment]
@pkandasamy91 thanks for sharing the error message you're seeing!

It appears that the ECS load balancer transformer's `normalizeLoadBalancer` method has a return value of type `IEcsLoadBalancer`, but core code expects it to return `IPromise<IEcsLoadBalancer>`, which is why you are seeing the error message `...).then is not a function`. Perhaps @allisaurus has more context as I believe she recently [updated some related code](https://github.com/spinnaker/deck/pull/8186).

**Comment by pkandasamy91** [comment]
@maggieneterval Any thoughts as to why this stopped working after that commit?

**Comment by maggieneterval** [comment]
I'm totally at a loss as for why you started seeing that error after [this commit](https://github.com/spinnaker/deck/commit/72af6cc495cf9f82634f62631bba1f7b6e148eb7), as it shouldn't have affected the codepath involved, which as far as I can tell is:

1. [LoadBalancerReader.loadLoadBalancers](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts#L23)
2. [LoadBalancerReader.normalizeLoadBalancer](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts#L53)
3. [Provider-specific LoadBalancerTransformer.normalizeLoadBalancer, which is expected to return a promise.](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts#L54)

Are you able to update the ECS [LoadbalancerTransformer.normalizeLoadBalancer](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/ecs/src/loadBalancer/loadBalancer.transformer.ts#L4) to return a promise instead and see if you're still getting this error?

Thanks and sorry in advance if this is not in fact the problem here!

**Comment by allisaurus** [comment]
@pkandasamy91  @maggieneterval I put up a PR to fix the normalizeLoadBalancer error:
https://github.com/spinnaker/deck/pull/8323

The infra pages still look a little off (see note in PR re: filter panel), but at least they're showing up now? 😩

**Comment by pkandasamy91** [comment]
Pulled down the latest of every microservice, and it looks to be working! Thanks @maggieneterval @allisaurus!
