### ISSUE TITLE
"Force Cache Refresh" take 12mins to finish (spinnaker version 1.20.2)

### ISSUE THREAD

**Issue by vuxuanlai** [spinnaker/spinnaker#5802]
### Issue Summary:
Spinnaker version: 1.20.2
Sometimes,  "Force Cache Refresh" got 12mins to finish process.
![Screenshot from 2020-06-01 10-28-26](https://user-images.githubusercontent.com/1458400/83373877-12bdd580-a3f4-11ea-8661-fc51e71601ca.png)

Could someone plz help me to resolve?

**Comment by plumpy** [comment]
Thanks for filing this issue. It looks like this might be a request for help rather than a bug. In that case, you're probably better off looking for answers [from our Slack community](https://join.spinnaker.io/), since there is a larger pool of users there. Use the search functionality to find users who have a similar experience, or post a message in `#general` or another related channel.

**Comment by herozabbix** [comment]
Hello, have you solved it? I also met the same problem, I hope to get your help
