### ISSUE TITLE
Users don't have access to ServiceAccounts if the first group assigned doesn't match.

### ISSUE THREAD

**Issue by rrijkse** [spinnaker/spinnaker#5809]
### Issue Summary:

When managed service accounts are added as a memberOf to a group, regular users with access to only the first group in the group membership list can access the service account.

### Cloud Provider(s):

All (I have AWS, ECS, K8s enabled)

### Environment:

I am running Spinnaker on AWS within EKS to deploy to EKS, ECS and EC2 using authentication/authorization to GSuite.

### Feature Area:

Pipelines, Permissions

### Description:

It seems that even though the managed service account is created and is assigned to the correct groups, only the first group in the "roles" part is evaluated when determining what service accounts regular users have access to.

Regular users should have access to service accounts if they are both in one group, it shouldn't matter what order the groups are in.

### Steps to Reproduce:

With Managed Service Accounts enabled:

Create a new pipeline
Setup a new "Automated Trigger" (I tested with the docker registry trigger to an ECR repo, but I don't think this issue is related to the type of trigger)
Assign two permissions like Group1 and Group2.

Have a user with only access to Group2 try to edit the pipeline. That user will not be able to save the pipeline, getting the error: "You do not have access to the service account configured in this pipeline's Docker Registry trigger."

If you remove the Group1 from the pipeline permissions (with another user that is a member of the Group1) and then try to edit the pipeline everything works.

### Additional Details:

Full fiat/authorize curls are here: https://gist.github.com/rrijkse/70b6e849bfbbfa5cb336cd2bea9efeaa

user shows the user is part of groups 2,3,4 and the service account for the pipeline is part of group 1,2 but yet the service account doesn't show on the user's permissions list. For clarity I've left the service account user ID's the same, but all the other information has been obscured. I have the full curls stored and if you need them to troubleshoot I can provide them (just don't want to post all that info publicly).

**Comment by evansb** [comment]
Your steps to reproduce are not reproducing the bug.

> It seems that even though the managed service account is created and is assigned to the correct groups, only the first group in the "roles" part is evaluated when determining what service accounts regular users have access to.
This would have been a bug because the expected behavior is that the user must have ALL the roles, see: https://www.spinnaker.io/setup/security/authorization/service-accounts/#service-account-roles

> Have a user with only access to Group2 try to edit the pipeline. That user will not be able to save the pipeline, getting the error: "You do not have access to the service account configured in this pipeline's Docker Registry trigger."
> If you remove the Group1 from the pipeline permissions (with another user that is a member of the Group1) and then try to edit the pipeline everything works.

These are expected behavior. It would have reflected the bug description if : Service account has Group1 and Group2, then a user with *only* Group1 can edit the pipeline. If you can reproduce this please update your issue description.

Glancing at the code, it might worth inspecting the value of `roles` in the Pipeline JSON to see if the roles were assigned incorrectly (UI bug?), but the roles checking itself seems to be correct. https://github.com/spinnaker/orca/blob/1c26964656d16e529ce361ce75a0b748da387382/orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SaveServiceAccountTask.java#L130

**Comment by rrijkse** [comment]
Thanks @evansb I understand why this was setup this way but the behaviour but it is pretty confusing overall. Since it basically makes it impossible for two separate user groups to work together on one pipeline/application.
