### ISSUE TITLE
spin CLI with LDAP auth?

### ISSUE THREAD

**Issue by razvan-ig** [spinnaker/spinnaker#5821]
Hi - following the instructions from https://www.spinnaker.io/setup/spin, with the latest spin binary and Spinnaker 1.19.10 on Kubernetes, Gate listening on http://spin-gate:80, `hal config security authn ldap enable`, service type LoadBalancer; any way we try to execute spin  (--gate-endpoint or in ~/.spin/config) we just get

```
Could not reach Gate, please ensure it is running. Failing.
invalid character '<' looking for beginning of value
```

Same error no matter where we run spin from, including the Hal pod in the same namespace.

**Comment by ajordens** [comment]
I would suggest reaching out on Slack for users that may have similarly configured `spin` in the way you're looking to do it, it's possible that support for LDAP isn't available out-of-the-box.

**Comment by angelcervilla** [comment]
hi @razvan-ig 
Did you populate correctly the config file for _spin_ ? When I saw that is because I didn't something right.
We also use ldap to authenticate, and this is how it looks like mine:
`gate:
  endpoint: https://spin-gate
auth:
  enabled: true
  basic:
    username: <some text>
    password: <some text>`

**Comment by razvan-ig** [comment]
> hi @razvan-ig
> Did you populate correctly the config file for _spin_ ? When I saw that is because I didn't do something right in the config file.
Hi @angelcervilla, thank you for the hint, double checked but it doesn't look like the config is the problem. Also `curl` using the same URL and credentials works and we can submit pipelines etc, just `spin` fails with the above error
As @ajordens hinted, it may be that spin doesn't handle LDAP correctly in the current release (1.14.0)? The docs at https://www.spinnaker.io/setup/spin/#configure-spin don't mention LDAP either.

**Comment by angelcervilla** [comment]
hi @razvan-ig 
that's weird, because I used _spin_ 1.14.0 on my deployment and worked all fine, and we have authN configured too with LDAP. When I got that error is because:

- the config file was not correctly formatted, or
- the provided credentials were not correct 

You don't mention it, but I assume here that AuthN configuration is correct: that when you go to Spinnaker UI, you get redirected to gate, and you get a login/password form, and credentials works fine there too. Is that correct?

**Comment by razvan-ig** [comment]
figured it out, thank you again for the hints: the usernames I tried had some special chars in the passwords which confused `spin` even if quoted; seems we'll need to generate alphanumeric strings for the svc accounts.

**Comment by angelcervilla** [comment]
Cool, great to see that it worked. Funny, because I also have special chars in the password, and it worked, but I guess it depends of what special chars you use.
Also, I'd like that the error handling in _spin_ works better, right now when it fails it does it with the error you reported, and it can mean anything, so not very informative. @ajordens is there any chance to improve this part?
