### ISSUE TITLE
"manualJudgment" is misspelled

### ISSUE THREAD

**Issue by ghostsquad** [spinnaker/spinnaker#5846]
### Issue Summary:

```
No StageDefinitionBuilder implementation for manualJudgement found (knownTypes: ...,manualJudgment,...)
```

### Cloud Provider(s):

AWS/K8s

### Environment:

version `1.19.11`

### Additional Details:

This is just a bit surprising...

**Comment by maggieneterval** [comment]
@ghostsquad thanks for sending me down a very interesting journey on the history of each spelling! From [Merriam Webster online dictionary](https://www.merriam-webster.com/dictionary/judgment):

> Judgment can also be spelled "judgement," and usage experts have long disagreed over which spelling is the preferred one. Henry Fowler asserted, "The OED [Oxford English Dictionary] prefers the older and more reasonable spelling. 'Judgement' is therefore here recommended." William Safire held an opposite opinion, writing, "My judgment is that Fowler is not to be followed." "Judgement" is in fact the older spelling, but it dropped from favor and for centuries "judgment" was the only spelling to appear in dictionaries. That changed when the OED (Fowler's source) was published showing "judgement" as an equal variant. Today, "judgment" is more popular in the U.S., whereas both spellings make a good showing in Britain.

Going to close this issue since it seems both spellings are valid. If anyone feels strongly about changing the spelling in a backwards-compatible way, please feel free to re-open.

**Comment by ghostsquad** [comment]
Oh very interesting
