### ISSUE TITLE
RFC: CircleCI integration

### ISSUE THREAD

**Issue by roopakv** [spinnaker/spinnaker#5862]
### Issue Summary:

I think it would be cool to add CircleCI as one of the supported platforms. I am happy to add this support to Igor, however, I would like some comments from the official team before I start sending PRs

### Cloud Provider(s):
all

### Environment:
all

### Feature Area:
CI systems

**Comment by jensvdh** [comment]
Hey @roopakv that sounds great! Would you be willing to discuss this in the upcoming CI SIG meeting with us?

You can find more information on [spinnaker slack](http://join.spinnaker.io/) in the #sig-ci channel

**Comment by gal-yardeni** [comment]
@roopakv This is a great idea! 
Few comments:
1. If you were to submit an actual RFC, you will need to provide more details and examples here :)
2. Since you can actually just go ahead and start implementing it, there's no need for an RFC in this case.
3. The best and recommended way to add a CI provider to Igor is by **adding a plugin**. 
Here's an example of a drone CI provider plugin, which you can follow the concepts: https://github.com/Odusanya18/droneci-spinnaker-stage. you can follow with the people who contribute to it via #sig-ci or #plugins channels.
Please feel free to drop by our SIG meeting tomorrow at 10:00 am PST if you wish to talk about it more!

**Comment by roopakv** [comment]
@gal-yardeni where / how do i join the sig meeting?

**Comment by gal-yardeni** [comment]
@roopakv here's a link: https://meet.google.com/yec-pgcf-gxx for the meeting tomorrow at 10:00 am PST. We have a meeting once a month. Here's a link to the agenda: https://docs.google.com/document/d/1vV5lzBydtPQVwIADxdb7eKqq5yoBhA4pEJrxksLuXdE/edit , you can add items as you wish!
For ad hok issues, you can use #sig-ci slack channel.

**Comment by emccallum** [comment]
Hi @roopakv , we'll be discussing plugins in the next CI SIG meeting tomorrow at 10:00 AM PST. The details are the same as Gal shared above; hope to see you there!

**Comment by roopakv** [comment]
@emccallum yes! for sure i'm trying to move some meetings around and then I'll be there

**Comment by emccallum** [comment]
Hi @roopakv thanks for joining the SIG last week! Since we were able to discuss this issue and talk about next steps, I'll close this out for now. Please feel free to open a new issue if you encounter one while getting started on this plugin.
