### ISSUE TITLE
run_dev.sh expects deck directory under build workspace

### ISSUE THREAD

**Issue by lachie83** [spinnaker/spinnaker#588]
Following the README to get Spinnaker up and running.

``` 
/usr/local/spinnaker/build# ./spinnaker/dev/run_dev.sh
This script needs to be run from the root of your build directory. 
```

dev_runner.py main is looking for a deck directory to exist under the build directory.

```
/usr/local/spinnaker/build# ./spinnaker/dev/run_dev.sh 
This script needs to be run from the root of your build directory.
/usr/local/spinnaker/build# less ../spinnaker/dev/run_dev.sh 
/usr/local/spinnaker/build# less spinnaker/dev/dev_runner.py 
/usr/local/spinnaker/build# mkdir deck
/usr/local/spinnaker/build# less ../spinnaker/dev/run_dev.sh 
/usr/local/spinnaker/build#  ../spinnaker/dev/run_dev.sh 
/usr/local/spinnaker/spinnaker/config/spinnaker-local.yml seems ok.
Rewriting deck settings in "/usr/local/spinnaker/build/deck/settings.js".
Starting external dependencies...
REDIS_HOST=localhost LOG_DIR="/usr/local/spinnaker/build/logs" "/usr/local/spinnaker/spinnaker/runtime/start_redis.sh"
Checking for Redis on localhost:6379.
Redis is already up on localhost:6379.
```

**Comment by ewiseblatt** [comment]
The instructions look as intended, but run_dev itself did have a problem fixed earlier today.

Using those instructions you should have a directory build/ that contains all the git clones and spinnaker will be next to it (spinnaker could be inside it as well, but the current script puts it next)
   spinnaker/
   build/
      deck/
      clouddriver/
      ...


You need to be in build/ so the scripts can find ./deck

There is currently a bug (I plan to fix later today) where you need to have a $HOME/.spinnaker/spinnaker-local.yml file, and it should not have the environment variable references assumed by the spinnaker/conf/default-spinnaker-local.yml because you dont have a spinnaker installation defining them. Instead copy the file and edit out the environment variable references to fill in values for the time being.

I just submitted a PR correcting the docs reflecting the current usage constraint.
Sorry for the inconvienence.

BTW, if you are not planning on doing development, you may prefer to use the binary debian package installation documented on http://spinnaker.io

**Comment by ewiseblatt** [comment]
@lachie83 I also fixed run_dev so you dont need to manually configure spinnaker-local to run it the first time.

**Comment by lachie83** [comment]
Perfect. Thanks @ewiseblatt
