### ISSUE TITLE
Remove liveManifestCalls in favor of one sensible cache refresh strategy

### ISSUE THREAD

**Issue by ezimanyi** [spinnaker/spinnaker#5906]
## Overview

The `liveManifestCalls` flag was added to address speed up deployments so that they no longer had to wait for one (or more) caching cycles before they completed.  Unfortunately, this leave the cache in an inconsistent state, which makes some later tasks (ex: dynamic target selection) fail.

Let's come up with one simpler strategy that does not depend on a flag.  Namely, let's always do a live query when determining the status of a just-deployed resource, and only block on a cache update if we know we'll need the cache to be up to date.

## Details

* Currently, with liveManifestCalls disabled, Orca is responsible for waiting a “cache refresh” cycle after each manifest operation task.
* Only tasks that rely on dynamic target selection (max-version-history, rollout strategies) require the cache to be in a consistent state before executing. These features are broken with liveManifestCalls enabled because they try to execute with the cache in an inconsistent state.
* We should refactor these types of tasks to make live calls instead of relying on the cache, regardless of the liveManifestCalls flag, which we should remove.

**Comment by aRobinson-R7** [comment]
We have recently seen pipelines ~fail~ continue to run indefinitely due to Clouddriver restarts (OOMKilled in this case), and the pipelines never progess.
Would this be addressed by using the `--live-manifest-calls` flag?

**Comment by ezimanyi** [comment]
@aRobinson-R7 : I don't think that this will help with OOM issues as that flag won't change the memory footprint either way.  It can take some tuning to pick the right RAM/CPU parameters for clouddriver but it seems like you might need to allocate more memory.  For help with tuning these parameters I'd suggest asking in the `#kubernetes` channel on Spinnaker Slack.

**Comment by maggieneterval** [comment]
The `liveManifestCalls` flag will no longer be necessary as of Spinnaker 1.23, currently scheduled for release in mid-October, because live calls will now always be made where appropriate during pipeline execution. In addition to the PRs linked [here](https://github.com/spinnaker/spinnaker/issues/5607#issuecomment-692717738) which laid the groundwork for the flag to be removed, the following PRs resolved this issue:

- https://github.com/spinnaker/clouddriver/pull/4903
- https://github.com/spinnaker/clouddriver/pull/4904
- https://github.com/spinnaker/orca/pull/3912
- https://github.com/spinnaker/halyard/pull/1795

No configuration changes are required to take advantage of this change, although you can safely remove the `liveManifestCalls` flag from your Kubernetes account configuration since it is no longer read by Clouddriver.
