### ISSUE TITLE
Comprehensive support for containers

### ISSUE THREAD

**Issue by tomaslin** [spinnaker/spinnaker#592]
This is an issue to start the discussion on how we expect containers to look like in Spinnaker across different providers such as ECS, Kubernetes, etc.

**Comment by ringods** [comment]
I'm personally interested in the ECS path.

**Comment by ringods** [comment]
@tomaslin Here is my take on how I would see Spinnaker integrated with Amazon ECS.

My current AWS setup includes 3 VPC's: `management`, `development` and `production`. I have VPC peering connections from management to the other 2, with proper routing tables and firewall rules. This way, development can't reach production by accident.

Within development and production, I have respective launch configurations booting up ecs-agent enabled machines which lead to a region specific ECS cluster. In each VPC, I also have a fault tolerant PostgreSQL RDS setup. That's my base infrastructure, all managed using Terraform + Atlas. I like the revision controlled infrastructure setup, so I wouldn't want to change too much to this.

I'm now ready to launch Docker containers using ECS task definitions, tasks and services. That's what I would use Spinnaker for.

My thinking on integration with ECS: map an ECS cluster to a Spinnaker server group: a set of instances within a specific region. Allow me to configure my existing ECS clusters, resizing supported via the backing launch configuration.

Deploying a Docker image should then not talk to a Docker daemon directly, but should map onto the ECS task definitions, tasks and service concepts ECS already provides.

As you can see, I'm going very technology specific. I do not want to abstract too much of the features each of the technologies provides: Swarm, ECS and Kubernetes each have their own powers and weaknesses. Make sure we offer all of the powers for each of the technologies.

**Comment by tomaslin** [comment]
Making a note here that we should support registry push as a triggering event in Spinnaker

**Comment by thoughtarray** [comment]
We would love to use Spinnaker at our organization as well.  Unfortunately, we must use dedicated instances (healthcare industry).  Because of that, server groups of small-to-medium-sized instances per app isn't possible.  If Spinnaker supported ECS (or made it easy to do non-AWS clusters), we could possibly use it.

**Comment by tomaslin** [comment]
I'm going to close this issue as container support in Spinnaker will be outlined in roadmap to be published soon.

**Comment by ringods** [comment]
@tomaslin ok, but can you publish the link to this roadmap here? I'm not following up the Spinnaker evolution at the moment.

**Comment by timbunce** [comment]
@tomaslin, I'd like to second @ringods request for a link to the roadmap, even if just a draft at the moment.

**Comment by duftler** [comment]
http://www.spinnaker.io/docs/roadmap

**Comment by cgmartin** [comment]
Not seeing anything specific to ECS in the roadmap currently, but interesting about Docker Registry triggers and Kubernetes integrations. Thanks for sharing it, @duftler

**Comment by nafiux** [comment]
@duftler It seems that the roadmap doesn't exists anymore, Do you have the link of the new one? I'm also interested into see topics related to AWS ECS. Thanks!

**Comment by duftler** [comment]
@nafiux An updated roadmap will be published shortly (@lwander can say more on this).

I think @BrunoCarrier will have more information on the AWS ECS support.

**Comment by nafiux** [comment]
Thanks @BrunoCarrier, I'm new in Spinnaker (I'm using Jenkins for CI/CD), I'm trying to understand how I can do blue/green or Canary deployments with Spinnaker and AWS ECS, I'm using Linkerd (service-mesh) to expose the services outside, behind a load balancer that point to each ECS Node in which Linkerd is running. I'm still trying to define things like:

- Should I have an AWS ECS cluster per environment? Or should I deploy everything (dev, stage & prod) in the same cluster?
- How to expose a small percentage of new versions to start testing them (Canary).

It may be things more related to AWS ECS rather than Spinnaker, just sharing with you where I'm.

**Comment by BrunoCarrier** [comment]
@nafiux For Canaries, see https://www.spinnaker.io/guides/user/canary/stage/.  I am not sure if the canary solution supports ECS though.  

The larger your ECS cluster, the easier you can scale up / down, reserve instances, etc.  However, the larger the blast radius.  I would not recommend having the same cluster for prod and non-prod

blue/green deployments are called black/red in Spinnaker, and you can do them out of the box with the ECS cloud provider.  Under the hood, ECS services are scaled up and down to achieve the blue/green deployment
