### ISSUE TITLE
Inquiry About the Microservice Architecture Employed by `spinnaker`

### ISSUE THREAD

**Issue by research-sudo** [spinnaker/spinnaker#5925]
I am a researcher investigating the open source projects that are designed by the microservice architectural style (https://martinfowler.com/microservices/). My preliminary investigation shows that the **_spinnaker_** project (https://github.com/spinnaker/spinnaker) is designed by the microservice architectural style.

Can you please **_confirm_** if my interpretation that this project is designed by following the microservice architectural style is correct? Note that if the projects (e.g., frameworks or tools) support the development of microservices-based systems but themselves are not designed by following the microservice architectural style, please also clarify it?
If my interpretation is correct, what **_features_** or **_characteristics_** of the architecture of this open source project show that the microservice architectural style has been used?
**Optional Question**: Do you know any other open-source projects that are designed by following the microservice architectural style?
I would be greatly appreciative if you can kindly answer the three questions above.

**Comment by maggieneterval** [comment]
Hi @research-sudo, thanks for reaching out! Your research sounds super interesting. I'd recommend checking out Spinnaker's [architecture documentation](https://spinnaker.io/reference/architecture/). If you have additional questions or would like to further discuss your research with Spinnaker developers, it sounds this conversation could be a good fit for Spinnaker's [Platform SIG](https://github.com/spinnaker/governance/tree/master/sig-platform). Would you be interested in attending a meeting? Please feel free to suggest an item directly on the [agenda](https://docs.google.com/document/d/1zGIgEwO9lZfYaI0N6necuH-x0SjmL3hmbbeMWZgqnEw/edit#heading=h.ilrqo6qoiejr).

I'm going to close this issue for now since we try to only keep GitHub issues open for outstanding bug reports and feature requests. Wishing you all the best with your research!
