### ISSUE TITLE
Delete deployment is missing in GUI

### ISSUE THREAD

**Issue by sramek5** [spinnaker/spinnaker#5962]
### Issue Summary:
It would be very nice to have a possibility to delete deployment in Spinnaker GUI.

### Cloud Provider(s):
OpenStack
Kubernetes: v1.18.6
Spinnaker: 1.21.0

### Description:
In `Deployment Actions` button is just a few commands:
![image](https://user-images.githubusercontent.com/53052347/89639066-364a4400-d8ad-11ea-8246-ea605f9e78c6.png)

I tried to `Destroy` or `Disable` Server Group:
![image](https://user-images.githubusercontent.com/53052347/89639078-39453480-d8ad-11ea-94a3-c5cf3b568d40.png)

In this case I got error:
```
Exception: Unable to locate replicaSet ai-kafka-slack-59c5f6c996 in dev2-ict-arch/narwhal-robots/deployment ai-kafka-slack
```
### Additional Details:
The ReplicaSet mentioned in error is exists and it is in ready state:
```
NAME                                  READY   STATUS             RESTARTS   AGE
pod/ai-kafka-slack-59c5f6c996-c6c9l   1/1     Running            0          3h40m

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ai-kafka-slack   1/1     1            1           3h40m

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/ai-kafka-slack-59c5f6c996   1         1         1       3h40m
```
### Expected Bahavior:
I would like to delete all Manifests sources in deployment using Spinnaker GUI.
Right now it requires manual intervention to delete deployment (replicasets, pods) using `kubectl`, but because it is not deployed using Helm, there still could be some residual kubernetes objects (crds, secrets, etc).

Possible bug or am I missing anything?
Thanks for feedback.

**Comment by babinin** [comment]
Hi!
it would be very useful to have 'edit' action back
(Spinnaker 1.21.3)

**Comment by maggieneterval** [comment]
Hey @sramek5 and @babinin! I appreciate you reporting this issue. I've submitted a fix that will go out with the next release (1.22), which is scheduled for within the next couple of weeks.

Spinnaker's Kubernetes SIG has actually discussed disabling all of these ad-hoc actions by default for the Kubernetes provider, since many operators do not want their dev teams making any out-of-band changes to resources. Definitely curious to hear your perspective on this and what workflows these ad-hoc actions fit into on your teams, if you care to share! (Will close this issue since the bug is resolved, but please feel free to continue to comment with any thoughts.)
