### ISSUE TITLE
It failed to create load balancer

### ISSUE THREAD

**Issue by neil-yechenwei** [spinnaker/spinnaker#5980]
### Issue Summary:
After tested, I found spinnaker would fail to create load balancer. 

### Cloud Provider(s):
Azure

### Environment:
All release versions and latest master branch

### Feature Area:
Clouddriver

### Description:
After tested, I found spinnaker would fail to create load balancer. 

### Steps to Reproduce:
1. Create firewall
2. Create loadbalancer

**Comment by neil-yechenwei** [comment]
After investigated, seems it failed to create load balancer after applied the PR "https://github.com/spinnaker/clouddriver/pull/4809". @robzienert , could you have a look? If it's a bug, please fix it asap. Thanks.

**Comment by maggieneterval** [comment]
Hi @neil-yechenwei! The PR you referenced (spinnaker/clouddriver#4809) that removed the Azure provider from Spinnaker was intentional, since Azure no longer meets Spinnaker's [cloud provider requirements](https://github.com/spinnaker/governance/issues/new?assignees=ajordens%2C+ethanfrogers%2C+ezimanyi%2C+plumpy%2C+robzienert&labels=committee%2Ftechnical-oversight&template=new-cloud-provider.md&title=PROPOSAL%3A+New+Cloud+Provider+for+%3Ccloud+provider+name%3E). @robzienert has outlined the action needed for Azure to meet these requirements in [this issue](https://github.com/spinnaker/governance/issues/123). 

If you or anyone you know would like to move forward with creating a Spinnaker Special Interest Group (SIG) for the Azure Cloud Provider, please reply to Rob directly on that [issue](https://github.com/spinnaker/governance/issues/123). Thanks!

**Comment by maggieneterval** [comment]
I noticed shortly after responding to this issue that Oracle now has a SIG and there is an [open PR to re-add the provider to Clouddriver](https://github.com/spinnaker/clouddriver/pull/4808)! 🎉
