### ISSUE TITLE
Spinnaker 1.22.x error with Kustomize

### ISSUE THREAD

**Issue by oo00spy00oo** [spinnaker/spinnaker#6022]
### Issue Summary:

I did not see any account in my Spinnaker when Kustomize is choosen.

https://i.imgur.com/Z1frMHE.png

### Cloud Provider(s):

GCP, AWS

### Environment:

Spinnaker 1.22.x

**Comment by ezimanyi** [comment]
@oo00spy00oo : Thanks for reporting this issue!  A couple of questions to help with debugging:
* Was this working on an earlier version of Spinnaker and broke in 1.22 or are you setting up kustomize support for the first time in 1.22?
* Do you have any artifact accounts of type `gitrepo` configured in your `clouddriver` config?

Thanks!

**Comment by oo00spy00oo** [comment]
> @oo00spy00oo : Thanks for reporting this issue! A couple of questions to help with debugging:
> 
> * Was this working on an earlier version of Spinnaker and broke in 1.22 or are you setting up kustomize support for the first time in 1.22?
> * Do you have any artifact accounts of type `gitrepo` configured in your `clouddriver` config?
> 
> Thanks!

Thanks for your response!
1. Kustomize wasn't working before version 1.22.
2. I've configured artifact accounts already (`gitrepo`)

**Comment by ezimanyi** [comment]
@oo00spy00oo : I just tested this out and I was able to get accounts to show in that drop-down, so the issue seems to be working in general, but hopefully we can figure out why it's not working in your case.

I would suggest checking the following:
(1) Check the accounts returned from `GET http://<your gate endpoint>/artifacts/credentials` (maybe that will be `https://` depending if you have SSL).    You should see an entry like this in the results:
```
   {
      "types" : [
         "git/repo"
      ],
      "name" : "my-gitrepo"
   },
```
(2) If you don't see the entry in gate, the next place to check would be clouddriver, `GET http://localhost:7002/artifacts/credentials`.  Again you should see the above entry for your gitrepo account.

The drop-down is populated by having `deck` make that request to `gate`, which then makes the request to `clouddriver`.  So possibly if you're not seeing the account for some reason `clouddriver` is not returning it from that query.

This is the config I needed in my clouddriver account for the drop-down to populate:
```
artifacts:
  gitrepo:
    enabled: true
    accounts:
    - name: my-gitrepo
      username: my-username
      password: my-password
```

**Comment by ezimanyi** [comment]
Closing this, please feel free to re-open comment if you are still having issues!
