### ISSUE TITLE
eks 1.16.3 fluentd install Exception ( Monitor Deploy )

### ISSUE THREAD

**Issue by eternam2** [spinnaker/spinnaker#6034]
Exception ( Monitor Deploy )
Failed to evaluate [containers.input.conf] EL1012E: Cannot index into a null value
Failed to evaluate [outputS3.conf] EL1012E: Cannot index into a null value

fleuntd aws eks distribution install 
Help me get the above error

**Comment by plumpy** [comment]
Thanks for filing this issue. It looks like this might be a request for help rather than a bug. In that case, you're probably better off looking for answers [from our Slack community](https://join.spinnaker.io/), since there is a larger pool of users there. Use the search functionality to find users who have a similar experience, or post a message in `#general` or another related channel.
