### ISSUE TITLE
create applications but project can't find this applications

### ISSUE THREAD

**Issue by SamPeng87** [spinnaker/spinnaker#6082]
### Issue Summary:
if I create application with contains dashes,it will show warn for me:
 Dashes should only be used in application names when using the Kubernetes v2 provider
but I am use Kubernetes v2 provider provider.

when I create project,want select application for this project,I can't searched this applications.

### Cloud Provider(s):
Kubernetes v2 provider

**Comment by ajordens** [comment]
This is probably a question best answered via Slack, feel free to [join us there](http://join.spinnaker.io/).

**Comment by maggieneterval** [comment]
Hi @SamPeng87, thanks so much for raising this issue!

> if I create application with contains dashes,it will show warn for me:
Dashes should only be used in application names when using the Kubernetes v2 provider
but I am use Kubernetes v2 provider provider.

I've opened a PR to [remove](https://github.com/spinnaker/deck/pull/8662) the dashes warning altogether, because all Kubernetes accounts are now V2 accounts since the removal of the V1  Kubernetes provider in 1.21.

> when I create project,want select application for this project,I can't searched this applications.

You may need to refresh the page after adding a new application before seeing it show up in the Projects applications dropdown, but I just tested this and it should be working as expected. Please feel free to open a new issue with more detailed steps to reproduce  if you are still experiencing this issue and believe it to be a bug. Thanks!
