### ISSUE TITLE
On demand refresh on ServerGroup cache results in temporary invalid data

### ISSUE THREAD

**Issue by aufarg** [spinnaker/spinnaker#6122]
### Issue Summary:
Hitting on demand cache refresh endpoint `/cache/aws/ServerGroup` in Clouddriver will eventually trigger a temporary invalid data for short period of time.

### Cloud Provider(s):
AWS

### Environment:
Clouddrive with Redis Cache

### Feature Area:
Clouddriver, ServerGroup cache (might also happen in other cache)

### Description:
Hitting on demand cache refresh endpoint `/cache/aws/ServerGroup` in Clouddriver will eventually trigger a temporary invalid data for short period of time. Specifically, the value of `instances` key seems to not contain instances that should have been there. The issue happens usually around 5-10s after the request has been completed. It stays for about the same duration and it goes back to normal afterwards.

The issue is first discovered when running Deploy stage with `rollingpush` strategy. On demand cache refresh on ServerGroup cache is part of the stage and it fails quite consistently later on the stage to disable the instances. After that, I discovered that the issue happens even if we trigger the refresh endpoint independently from the Deploy stage.

### Steps to Reproduce:
1. Run a loop to keep retrieving the ServerGroup details:
```
while true; do
  curl -H 'X-SPINNAKER-USER: <username>' \
       'http://<clouddriver endpoint>/applications/<application>/clusters/<account>/<cluster>/aws/serverGroups/<server group>?region=<region>' | jq '[.instances[].id]'
  sleep 1
done
```
  Or if you just want to check if the result is different:
```
while true; do
  curl -H 'X-SPINNAKER-USER: <username>' \
       'http://<clouddriver endpoint>/applications/<application>/clusters/<account>/<cluster>/aws/serverGroups/<server group>?region=<region>' | shasum
  sleep 1
done
```
2. Run the force refresh:
```
curl -H 'content-type:application/json' \
     'http://<clouddriver endpoint>/cache/aws/ServerGroup' \
     -d '{"asgName":<asg name>,"serverGroupName":<server group name>,"region":<region>,"account":<account>}'
```

### Additional Details:
This happens on Spinnaker 1.21 and 1.22. I suspect the data becomes invalid on the next scheduled cache refresh, though I have no conclusive evidence yet.

**Comment by aufarg** [comment]
I'm 90% sure that the change in data to become invalid and its subsequent restoration is caused by the caching agent scheduler. I added the following configuration:
```
redis:
  poll:
    intervalSeconds: 60
    errorIntervalSeconds: 60
```
and it results in the increase of the time it took between the on demand cache refresh to invalid data and the time it took between invalid data to restored data.

**Comment by kowshikRoy** [comment]
This issue causes problem while trying out the `Rolling Push` strategy

<img width="550" alt="Screen Shot 2020-10-19 at 12 51 42 PM" src="https://user-images.githubusercontent.com/10576292/96411243-f5a26b80-1209-11eb-8bb9-3e6159faae51.png">

We have looked into the code and found that it

Orca `RollingPushStage` creates `DetermineTerminationCandidatesTask` that collects server group information from clouddriver and instance information about the current server group.
[DetermineTerminationCandidatesTask.groovy](https://github.com/spinnaker/orca/blob/b89b61fd2845e9f3ab398dce7729e7e44d53cf0e/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/DetermineTerminationCandidatesTask.groovy#L50)

But we noticed that `knownInstanceIds` is equal to `knownInstanceIds: [null]`. And then while executing  `DisableInstancesTask` task, it throws because of `null` value for instance id.

We investigated further and found that, `ModifyAsgLaunchConfigurationStage` stage does a force cache refresh. So, after this cache refresh, when `DetermineTerminationCandidatesTask` is executed and fetches the ASG information, cache doesn't have the full information yet. 

To test the hypothesis, we used postman client to hit the endpoint `http://<clouddriver-url>/serverGroups/<clusterName>/<region>/<asg name>`  right after cache refresh and in some other time. In the first case, it didn't have instance detail information and later had.

So, we forked `orca-clouddriver` module and add `if(knownInstanceIds.any{it == null}) return TaskResult.RUNNING` after [this line](https://github.com/spinnaker/orca/blob/b89b61fd2845e9f3ab398dce7729e7e44d53cf0e/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/DetermineTerminationCandidatesTask.groovy#L50).

And it passed the stage without error.

**Comment by aufarg** [comment]
It seems the issue is because for on demand, `ClusterCachingAgent` does not set the `authoritativeTypes` on the result as seen [here](https://github.com/spinnaker/clouddriver/blob/660ee2c6bb8cdfd96bd36c174e55ebec40bf6d1c/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy#L251-L253). This causes the `putCacheResult` [here](https://github.com/spinnaker/clouddriver/blob/a09a97d435f1dc02d76b98df59dc10f950ccca79/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsOnDemandCacheUpdater.java#L136-L138) to replace instances cache.

I made a draft PR (https://github.com/spinnaker/clouddriver/pull/5033) to that fixes the issue.
