### ISSUE TITLE
spinnaker ldap login BUG!!!

### ISSUE THREAD

**Issue by herozabbix** [spinnaker/spinnaker#6165]
### Issue Summary:
1. spinnaker connect ldap command:
```
hal config security authn ldap edit --user-search-base 'ou=xxx,dc=xxx,dc=xxx' --url 'ldap://xxx:389' --user-search-filter 'cn={0}' --manager-dn 'cn=xxx,dc=xxx,dc=xxx' --manager-password 'xxx'
```

2. login spinnaker first connect is bad
    The first connection fails but the second one succeeds
![image](https://user-images.githubusercontent.com/56722758/98510923-efe6f580-229e-11eb-85d3-956a367dbf3d.png)

### Cloud Provider(s):
> kubernetes

### spinnaker version
1.22.1

**Comment by plumpy** [comment]
Thanks for filing this issue. It looks like this might be a request for help rather than a bug. In that case, you're probably better off looking for answers [from our Slack community](https://join.spinnaker.io/), since there is a larger pool of users there. Use the search functionality to find users who have a similar experience, or post a message in `#general` or another related channel.
