### ISSUE TITLE
Timeout on /auth/roles/sync with large amount of roles

### ISSUE THREAD

**Issue by aufarg** [spinnaker/spinnaker#6328]
### Issue Summary:
Hitting /auth/roles/sync with large amount of roles will result in timeout and roles are not synced. Hitting /roles/sync directly to Fiat with curl works fine

### Cloud Provider(s):
NA

### Environment:
Spinnaker version: 1.22.4

### Feature Area:
Fiat role sync, LDAP, Gate

### Description:
Whenever we try to manually sync roles through Gate it's always returns timeout response. It seems Gate abort the connection to Fiat because /roles/sync actually runs for quite a long time.

Some ideas to fix this:
- Make /roles/sync to be asynchronous and returns a handler.
- Have a separate configurable timeout for /auth/roles/sync endpoint.

**Comment by JamieChe** [comment]
We are facing the same issue. We have 3K+ ldap users visited Spinnaker and the role sync up time is 50~80 seconds. 
When creating an application , we will see  a timeout error in UI even though the application has been created successfully, because role sync is required after application creating and the runtime okhttp timeout exception couldn't be caught. 
The okhttp timeout can be increased  https://kb.armory.io/s/article/Timeouts-Using-okHTTP-Java-Services , but I don't think it is good to have the timeout unlimited if we have more and more users.  

When checking in Fiat redis, we found there is no TTL for all fiat keys. We are wondering whether we can set TTL or similar mechanism to Fiat user info like roles and permissions. So when some users not visiting Spinnaker for specific time, they can be removed from Fiat redis db, then the role sync time would be reduced
