### ISSUE TITLE
Automatic artifact binding must have an opt-out

### ISSUE THREAD

**Issue by jcavanagh** [spinnaker/spinnaker#6388]
Hi folks!

I wanted to start a discussion about https://github.com/spinnaker/clouddriver/pull/4874.  We had to revert this internally, as it had broken many pipelines that deal with multiple tags of the same Docker image. Unexpected builds were being deployed.

Previously, having a tag present in the manifest was sufficient to not auto-bind.  This was very useful, and resulted in unsurprising behavior when baking manifests with certain versions.  The user took an action to build a bake stage with a version, and that was the version deployed.  

As of this change, there is no way to opt out of automatic binding to manifests in Spinnaker.  If there is a matching artifact in the pipeline context at all, it gets bound.  All user-initiated manifest bakes, variable replacement, and etc are transparently and non-obviously undone.  This is very dangerous behavior, and poor UX.  If multiple tags of the same image are present, the actual image deployed is not guaranteed unless one of them is specifically bound as "required".

Too much behavior is now dependent on **how a pipeline was triggered** (and what artifacts happen to be present, relevant to the current stage or not), rather than the structure of the pipeline itself. 

I think automatic binding is nice for simple pipelines and simple use cases, but there are many use cases that become difficult or impossible to implement with this feature as-is.   

1. Custom rollbacks
	It is not possible to bake a manifest with a rollback version, if the to-be-deployed image is present in the pipeline.  `Undo Rollout (Manifest)` does work for many cases, but there are also many cases where it does not suffice, or does not map well to the situation.

2. Construction of ephemeral validation environments with mixed versions
	If two tags for the same image are present in context, the user is required to specify for every `Deploy (Manifest)` which artifact they wish to overwrite, even if that job has already been done in a Bake or similar stage.  The user is also required to trigger the pipeline with either zero or all the utilized artifacts, even if that information is not really needed.  
	
3. Deployment of different artifacts to different environments
	It may be the case that different environments require a particular variant of a build, yet are logically part of the same deployment operation.  This is also difficult to implement for similar reasons to the above use cases.

In addition to the usage restrictions that this behavior imposes, I think that having invisible behavior like this is not good UX, and this gotcha has tripped up a large percentage of our internal users, even before auto-binding was forced.    

I believe that the new iteration of forced auto-binding behavior is too surprising and too constraining - the mere presence of a Docker image (or similar) in the pipeline is granted too much power, and commonly undoes explicitly-taken user actions.

I would suggest that artifact binding be changed to explicitly opt-in only.  This would result in the overall least surprising behavior.  If that is not possible, then the replacement behavior should be configurable on a per-stage basis.

**Comment by german-muzquiz** [comment]
@jcavanagh I'm working on a change to opt-out of artifact binding based on a per-stage configuration parameter (linked PR). The idea is to have a new checkbox in `Deploy (Manifest)` stage to enable or disable required and optional artifact binding, so if you have manifests already having a docker tag, you could disable artifact binding in the stage configuration to deploy the tag already included in the manifest.

The default value would be to bind like today to not break (again) existing pipelines relying on this behavior. Keep in mind that this setting is not exactly the same as the old behavior of binding/not-binding depending on the manifest having a docker tag, but instead is meant to make it very obvious in the UI what behavior you'll get instead of relying on inspecting manifests to know what will happen. It also allows to not bind configmaps, secrets, etc. coming from triggers, parent pipelines or previous executions, since those artifacts are generally harder to track and troubleshoot when the wrong one gets bound automatically.
