### ISSUE TITLE
Is spinnaker dead?

### ISSUE THREAD

**Issue by jwillmer** [spinnaker/spinnaker#6761]
I'm looking into the software and notice that the last release is from 2017. The referenced [quick start deployment](https://github.com/armory/minnaker) has no changes since two years and is broken - I tried. So can this project be declared dead?

**Comment by jasonmcintosh** [comment]
NO it's not dead :). The slack is VERY active, we've had two recent releases.  The quick start was an armory specific thing we introduced to try to make it easier to get up and testing spinnaker (we have other solutions for that now to make it MUCH easier).  Armory isn't spinnaker itself - but we have a released based upon the spinnaker with some enhancements and extensions (deep terraform integration, opa integration, etc.).  

See: https://spinnaker.io/docs/releases/versions/ for recent releases.  Armory has released an [OSS operator ](https://github.com/armory/spinnaker-operator) to also try to make it easier (though there's some work on that for newer K8s clusters due to some API changes).  Halyard still works well.  For more questions, do please feel free to join the OSS slack!

**Comment by jasonmcintosh** [comment]
(note our extensions/release is proprietary ... not OSS )
