### ISSUE TITLE
Halyard daemon v1.56.0 fails to start

### ISSUE THREAD

**Issue by ashleykleynhans** [spinnaker/spinnaker#6847]
### Issue Summary:

Halyard daemon v1.56.0 fails to start

### Cloud Provider(s):

* AWS
* GCP
* ECS

### Environment:

* Ubuntu 22.04 LTS

### Feature Area:

Halyard

### Description:

Halyard daemon crash loops and does not stay up.

```
Jun 21 20:40:32 spinnaker halyard[1852347]: 2023-06-21 20:40:32.500  INFO 1852347 --- [           main] com.netflix.spinnaker.halyard.Main       : The following 3 profiles are active: "composite", "test", "local"
Jun 21 20:40:33 spinnaker halyard[1852347]: 2023-06-21 20:40:33.138  INFO 1852347 --- [           main] o.s.c.a.ConfigurationClassParser         : Properties location [file:/opt/spinnaker/hal.properties] not resol>
Jun 21 20:40:35 spinnaker halyard[1852347]: 2023-06-21 20:40:35.852  INFO 1852347 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=1d39966d-27ae-37e0-a424-0ff596b3f016
Jun 21 20:40:35 spinnaker halyard[1852347]: 2023-06-21 20:40:35.919  INFO 1852347 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'secretEngineRegistry' of type [com.netflix.spinnaker.kork.se>
Jun 21 20:40:35 spinnaker halyard[1852347]: 2023-06-21 20:40:35.919  INFO 1852347 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'secretManager' of type [com.netflix.spinnaker.kork.secrets.S>
Jun 21 20:40:35 spinnaker halyard[1852347]: 2023-06-21 20:40:35.920  INFO 1852347 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'secretPropertyProcessor' of type [com.netflix.spinnaker.kork>
Jun 21 20:40:37 spinnaker halyard[1852347]: 2023-06-21 20:40:37.316  INFO 1852347 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8064 (http)
Jun 21 20:40:37 spinnaker halyard[1852347]: 2023-06-21 20:40:37.341  INFO 1852347 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
Jun 21 20:40:37 spinnaker halyard[1852347]: 2023-06-21 20:40:37.341  INFO 1852347 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.69]
Jun 21 20:40:37 spinnaker halyard[1852347]: 2023-06-21 20:40:37.697  INFO 1852347 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
Jun 21 20:40:37 spinnaker halyard[1852347]: 2023-06-21 20:40:37.698  INFO 1852347 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 5177 ms
Jun 21 20:40:40 spinnaker halyard[1852347]: 2023-06-21 20:40:40.324  INFO 1852347 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : Autowired annotation should only be used on methods with parameter>
Jun 21 20:40:40 spinnaker halyard[1852347]: 2023-06-21 20:40:40.749  WARN 1852347 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling r>
Jun 21 20:40:40 spinnaker halyard[1852347]: 2023-06-21 20:40:40.759  INFO 1852347 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
Jun 21 20:40:40 spinnaker halyard[1852347]: 2023-06-21 20:40:40.798  INFO 1852347 --- [           main] ConditionEvaluationReportLoggingListener :
Jun 21 20:40:40 spinnaker halyard[1852347]: Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
Jun 21 20:40:40 spinnaker halyard[1852347]: 2023-06-21 20:40:40.859 ERROR 1852347 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :
Jun 21 20:40:40 spinnaker halyard[1852347]: ***************************
Jun 21 20:40:40 spinnaker halyard[1852347]: APPLICATION FAILED TO START
Jun 21 20:40:40 spinnaker halyard[1852347]: ***************************
Jun 21 20:40:40 spinnaker halyard[1852347]: Description:
Jun 21 20:40:40 spinnaker halyard[1852347]: Parameter 2 of constructor in com.netflix.spinnaker.config.OkHttp3ClientConfiguration required a bean of type 'okhttp3.logging.HttpLoggingInterceptor$Level' that could n>
Jun 21 20:40:40 spinnaker halyard[1852347]: Action:
Jun 21 20:40:40 spinnaker halyard[1852347]: Consider defining a bean of type 'okhttp3.logging.HttpLoggingInterceptor$Level' in your configuration.
Jun 21 20:40:40 spinnaker systemd[1]: halyard.service: Main process exited, code=exited, status=1/FAILURE
Jun 21 20:40:40 spinnaker systemd[1]: halyard.service: Failed with result 'exit-code'.
Jun 21 20:40:40 spinnaker systemd[1]: halyard.service: Consumed 49.102s CPU time.
```

### Steps to Reproduce:

1. Upgrade Halyard from v1.55.0 to v1.56.0.
2. Observe that the Halyard daemon keeps crash looping and does not stay up.

### Additional Details:

Downgraded Halyard to v1.55.0 and everything is functioning as expected again.

**Comment by jasonmcintosh** [comment]
I KINDA suspect something similar to https://github.com/spinnaker/kork/pull/1037

**Comment by dbyron-sf** [comment]
Pretty sure https://github.com/spinnaker/halyard/pull/2068 fixes this.

**Comment by dbyron-sf** [comment]
I've released halyard 1.61.0 with https://github.com/spinnaker/halyard/pull/2068.  @ashleykleynhans any chance you can try it out?

**Comment by ashleykleynhans** [comment]
I can confirm that the issue is resolved, thanks @dbyron-sf !

**Comment by Kyslik** [comment]
When releasing new version; can you please include PRs/Issues that were fixed by it? 🙏🏻  Description of https://github.com/spinnaker/halyard/releases/tag/v1.61.0 explains nothing about the release and what was fixed.

On another note; is there any incentive on securing the halyard; currently it has about 13 high severity vulnerabilities and 1 critical one (https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-3369852).

**Comment by Kyslik** [comment]
@dbyron-sf When releasing new version; can you please include PRs/Issues that were fixed by it? 🙏🏻  Description of https://github.com/spinnaker/halyard/releases/tag/v1.61.0 explains nothing about the release and what was fixed.

On another note; is there any incentive on securing the halyard; currently it has about 13 high severity vulnerabilities and 1 critical one (https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-3369852).

**Comment by dbyron-sf** [comment]
I agree that would be nice.  With (I hope) the monorepo coming soon, it's tough to justify investing time in the release tooling.

As for the security vulnerabilities, we are actively working on moving towards [spring boot 2.6.15](https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.6.15/spring-boot-dependencies-2.6.15.pom) which uses spring-framework 5.3.27 which looks like it addresses that issue.

**Comment by jeph10** [comment]
https://github.com/spinnaker/spinnaker/issues/6857

Still getting similar issue, my halyard version current version is 1.44.1 with spinnaker version 1.29.6, I did upgrade to halyard v1.70.0 and spinnaker v2025.2.3 then downgraded to halyard v1.61.1 ( suggested working version) but still have similar issues. 

Before the upgrade I was have this issue 
“exec plugin is configured to use API version client.authentication.k8s.io/v1beta1, plugin returned version client.authentication.k8s.io/v1alpha1”

My step 
- install latest kubectl version
- install Latest aws-iam-authenticator 
- install halyard new release version 1.70
After this step I got halyard connectivity issue but when rollback to 1.44.1 the issue is resolve. Is there a solution to fix this two problems
