### ISSUE TITLE
Improvement: show only zones that have server groups in the Destroy Server Group stage

### ISSUE THREAD

**Issue by JorritSalverda** [spinnaker/spinnaker#714]
The Destroy Server Group stage shows all zones available on GCE, so you can actually check zones you do not deploy to. This can lead to errors in the destroy stage.

Either greying out the zones you don't deploy to or silently letting the destroy pass if a zone doesn't have a server group would be fine.

**Comment by cfieber** [comment]
@duftler can you address this one?

**Comment by duftler** [comment]
Yes, we'll have a look.

**Comment by ttomsu** [comment]
All zones are shown for server group operation stages because it's possible that an upstream stage can create resources in zones that a server group (presently, meaning during stage configuration time) does not presently reside within. 

When I try to destroy a server group in a zone where it doesn't exist, I get the following exception. Do you see a similar error?

![bjzp6kpkfrh](https://cloud.githubusercontent.com/assets/13141550/12795307/60865210-ca87-11e5-886a-04ee360f4b64.png)

**Comment by ttomsu** [comment]
One thing to note is that changing zones (adding or removing them by checking/unchecking) causes the "Cluster" field to get cleared. Without a cluster value, you'll just get a "No reason provided" exception

![0m5b3wczp39](https://cloud.githubusercontent.com/assets/13141550/12797167/903f35e0-ca90-11e5-8e4d-61ba409407ee.png)

**Comment by ttomsu** [comment]
Since I haven't heard back, I'm going to close this issue. Please reopen if you're still having problems and we can go from there.
