### ISSUE TITLE
Could I set up spinnaker on cluster (multinode)?

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#732]
The example in spinnaker's documentation is that setting up a spinnaker on a single node. But as we know, spinnaker is composed of the 9 micro services (Clouddriver, Deck,Echo,Front50,Gate,Igor, Orca,Rosco,Rush ), so I want to ask could we deploy those services on multinode?  And could we scale each service to serve more jobs?

**Comment by ajordens** [comment]
This is essentially how we run Spinnaker here at Netflix and effectively what you would need to do in order to run Spinnaker reliably in production (_at the very least you should separate persistence_).

We have each service deployed within it's own cluster and scaled independently of each other.

Furthermore, we also upgrade services individually and on their own schedules ... all of this is done using Spinnaker itself.

Happy to answer any questions you might have around our particular setup.

**Comment by feihujiang** [comment]
Thanks for quick reply. :)

**Comment by feihujiang** [comment]
Sorry to reopen this issue, I had a question, when we have each service deployed within it's own cluster, how could services discover other depended services? Providing a load balance for each service, then config the load balance as the endpoint of depended services?

**Comment by tomaslin** [comment]
Yes, we also set up route53 mappings in our vpc so that the load balancer name is well known and follow a pattern ( ie, orca-main.xxx.netflix.net )

**Comment by feihujiang** [comment]
We know eureka is a REST based service that is primarily used in the AWS cloud for locating services for the purpose of load balancing, and spinnaker imports eureka.  What's the function of eureka spinnaker uses? What's the relationship between service discovery/load balances and eureka in spinnaker?  Will spinnaker provide service discovery through eureka?

**Comment by tomaslin** [comment]
Services will decide if they want to register with discovery or not. The gate service is able to resolve instances via either eureka or ELBs. We've been using ELBs. 

Eureka does provide a health check and indicator of health, Spinnaker uses this.
