### ISSUE TITLE
There is no 'Clone' pipeline stage.

### ISSUE THREAD

**Issue by duftler** [spinnaker/spinnaker#734]
The current 'Deploy' pipeline stage is a 'Create', not a 'Clone'.

**Comment by lwander** [comment]
@duftler If I understand correctly, the Clone stage wouldn't need to come after findImage or jenkinsTrigger since it would specify a static server group to clone, right? If that's the case, I think this is the perfect starting point for getting Kubernetes pipelines working, since we don't have to worry about the findImage semantics between server groups with multiple images.

**Comment by tomaslin** [comment]
I would like to see this more as a 'Copy from X if available' rather than a strict clone. The original intent of having all that cluster config in a pipeline is to capture the scenario where your cluster didn't strictly need to exist for your pipeline to run.

**Comment by ajordens** [comment]
++

**Comment by lwander** [comment]
Would you still have the ability to edit the cloned server group in the pipeline stage?

**Comment by anotherchrisberry** [comment]
@duftler is this complete?

**Comment by duftler** [comment]
Yes. Note that the server group targeted for cloning _does_ need to exist, and the stage will fail if it cannot be resolved (just like other pipeline stages that attempt to resolve target server groups).
