### ISSUE TITLE
Who's using spinnaker?

### ISSUE THREAD

**Issue by feihujiang** [spinnaker/spinnaker#746]
Spinnaker is used to replace Asgard, and we know Asgard is used by lots of [companies](https://github.com/Netflix/asgard/wiki/Who%27s-using-Asgard%3F), such as Netflix :), IBM, Samsung, etc. Do these companies have plan to use spinnaker? Who's using spinnaker now? Do teams at Netflix use Spinnaker? If they do, the Spinnaker teams using is different from the open source version?

**Comment by feihujiang** [comment]
Ping @tomaslin @ajordens :)

**Comment by tomaslin** [comment]
Cannot speak as to IBM or Samsung. Google has a few fairly known companies that are actively using Spinnaker that we can't name. 

Within Netflix, Spinnaker is widely adopted. You can see the adoption in slide 41 of this presentation http://www.slideshare.net/JoshEvans2/beyond-devops-how-netflix-bridges-the-gap/41-Automate_proven_practices ( although today we're are at about 96% - i.e, 96% of new ASGs created at Netflix are done via Spinnaker ).

We have one Spinnaker that manages all of Netflix instead of many Spinnakers used by different teams. ( Technically 2, since we have a separate one for PCI compliance reasons ). 

The Spinnaker we run is almost the same as the open source version. Each microservice is ran as it's own cluster and we make sure there is at least 2. Clouddriver is also split up so that reading and writing happens with different clusters of different sizes, since we have a bigger footprint. 

One difference is that we have projects that wrap the open source libraries to interface with components of the Netflix platform enabled in the Base AMI, so talking to Discovery, Cassandra, etc happens there. A few components like Clouddriver have some code that does specific things that apply to Netflix, but not much ( it is different by one class ). Our gate also has a few endpoints that are not in open source. 

There are also a few components we run that are not yet open source, one is the Canary Analysis integration that really only works when you're using Atlas and integrates with the Automated Canary Analysis tool managed and written by our Real TIme Analytics team. The other one is a quick patch service that we'll likely open source soon. And one more service that talk to our internal monitoring services.

**Comment by feihujiang** [comment]
@tomaslin Thank you for your detailed reply.

**Comment by feihujiang** [comment]
:+1:
