### ISSUE TITLE
Spinnaker not picking configuration from $HOME/.spinnaker directory.

### ISSUE THREAD

**Issue by murarisumit** [spinnaker/spinnaker#793]
```

# This file is intended to override the default configuration in the spinnaker.yml file.
# In order for Spinnaker to discover it, it must be copied to a file named
# "spinnaker-local.yml" and placed in the $HOME/.spinnaker directory.
```
As mentioned in config comments, to override the default configuration in **spinnaker.yml** file we need to have file in `$HOME/.spinnaker` directory with name `spinnaker-local.yml`.

But that doesn't seem to work. I tried to update  below section in file.

```
primaryCredentials:
      name: aws__accnt_name
```

It only works when spinnaker-local.yml file is in `/opt/spinnaker/config/` directory not in `$HOME/.spinnaker`

Is it the intended behaviour or I'm missing something here ?

I can contribute in docs, if required

**Comment by tomaslin** [comment]
@ewiseblatt can you comment on this issue? The services have spring.config.location set to $HOME/.spinnaker but the install scripts seem to override this

**Comment by ewiseblatt** [comment]
I have not verified your claim yet, though am virtually certain that the issue is elsewhere because I've seen that work before.

Could you answer a couple questions first, then I'll look into it when I get in if these dont resolve the issue.

When you say "does not work", what do you mean?
What is $HOME? It should be /home/spinnaker.
Try to curl localhost:7002/env and look at the spring.config.location. It should show /home/spinnaker/.spinnaker in the path.

I assume you used the same spinnaker-local.yml file in both places, and not a hand-edit that might have typo'd.

- eric

**Comment by murarisumit** [comment]
I copied the default-spinnaker-local.yml and renamed it to spinnaker-local.yml, I checked it up again, there wasn't a typo, but

I'm using `ami-13685579` AMI and sshed into server using `ubuntu@IP`, so my `$HOME `after login is : `/home/ubuntu/`.  Do I've to modify the $HOME variable because I wasn't able to login using `spinnaker` user. 

But I pasted the file in `/home/spinnaker/.spinnaker` directory, but `$HOME` variable value after login into server was `/home/ubuntu`. 

What should I do in-order to make it work

**Comment by ewiseblatt** [comment]
Sorry, I wasnt clear before.

When I said $HOME was /home/spinnaker, I assumed that you were running
spinnaker as spinnaker.
When you install spinnaker using the debian package, it creates a spinnaker
user with /home/spinnaker. When you run spinnaker as a service (or upstart
it on boot) it runs as that user, not as your logged in user.

If you are manually running the job (/opt/clouddriver/bin/clouddriver) then
I guess it would run as you.
Regardless, it should always read from $HOME where $HOME is for the user
owning the process.

Try this:

sudo cp <file> /home/spinnaker/.spinnaker/spinnaker-local.yml
chown spinnaker:spinnaker /home/spinnaker/.spinnaker/spinnaker-local.yml
chgrp 600 /home/spinnaker/.spinnaker/spinnaker-local.yml

sudo service spinnaker restart


You can check the log

tail /var/log/spinnaker/clouddriver/clouddriver.log


Eventually it will show it is listening.
Shortly there after, you should be able to do this

curl localhost:7002/credentials


And see your AWS changes.

You can also see the runtime configuration bindings

curl localhost:7002/env


then you should see spinnaker components running as the spinnaker user.

Let me know if this helps (or not).

- eric

**Comment by ewiseblatt** [comment]
You'll need to sudo for the chown and chgrp commands.

**Comment by duftler** [comment]
I think that 'chgrp' was supposed to be 'chmod', right?

**Comment by ewiseblatt** [comment]
yea, my bad. chmod.

**Comment by ewiseblatt** [comment]
Sumit, what happened with this? Are you resolved?

**Comment by murarisumit** [comment]
Hi @ewiseblatt, sorry I wasn't able to respond on time.

I did that, gave proper permission to `/home/spinnaker/.spinnaker/spinnaker-local.yml`.
`-rw------- 1 spinnaker spinnaker 5643 Mar 14 05:27 spinnaker-local.yml`

`sudo service spinnaker restart` didn't worked, I did `sudo restart spinnaker` [spinnaker doc]
Cloudriver was listening on 7002.

But `curl localhost:7002/credentials` returned `[]` and `curl localhost:7002/env` had `"spring.config.location":"${user.home}/.spinnaker/"` .

So spinnaker is just not reading file from `/home/spinnaker/.spinnaker/spinnaker-local.yml` location, because it's not showing the Jenkins instance in pipeline stage config, which it was previously showing when `spinnaker-local.yml` file was read from `/opt/spinnaker/config/`

I think there something real stupid is missing here !

**Comment by ewiseblatt** [comment]
It looks like you are right. The bin/ scripts are overriding the
spring.config.location and pointing only to /opt/spinnaker/config. I think
that's wrong but maybe it's intentional and the docs are wrong. I'll look
into it.

**Comment by ewiseblatt** [comment]
Do we need to support $HOME/.spinnaker in production builds? I was going to
add it in because I thought it made sense, but now there are so many files
sharded all over the filesystem that if nobody noticed this wasnt hooked up
until now, maybe we should leave it as is (and update the docs).

Were you just following the docs, or did you have a need to put
spinnaker-local in /home/spinnaker?

**Comment by murarisumit** [comment]
No, I don't have any need to put it in /home/spinnaker, was just following the docs.

But I think better convention would be, to have  spinnaker-local file in /home/spinnaker and not in config directory, because usually overriding files are in home directory than in application directory.

**Comment by ewiseblatt** [comment]
Not yet sure whether to add /home/spinnaker to the startup script spring config, or remove it from the docs.  In the meantime, $HOME/.spinnaker isnt in the search path for apt package installs, but it is still the recommended location for developer build deployments. This bug is only applicable to apt package installs, not to running developer builds.

**Comment by ewiseblatt** [comment]
I updated the documentation. It now explicitly distinguishes /opt/spinnaker/config (and /etc/spinnaker/default) is only for package installs whereas $HOME/.spinnaker (and ./spinnaker/config out of the source tree) is for developer builds running from source.

We can revisit supporting $HOME/.spinnaker in package installations if this is needed in the future. Currently it is not.
