### ISSUE TITLE
my-google-account is missing

### ISSUE THREAD

**Issue by radkin** [spinnaker/spinnaker#796]
We're using GCE and when we "click to deploy" everything works fine. If we "InstallSpinnaker.sh" everything appears to work fine except for that fact that there is no "my-google-account" listed. Even creating a snapshot of the functional "click to deploy" VM does not allow us to use the disk on another machine. It appears as if you need to have a service account and we have created one, but when we add the information to spinnaker-local.yml it fails to populate the "accounts" field. We did try restarting spinnaker and refreshing cache, but that has no effect either.

There are no logs showing what we have done wrong, no documentation suggesting what the format should be nor do we have any idea where the .json secret needs to be. Reverse engineering the "click to deploy" VM has not helped either as the configuration files in /opt/spinnaker/config appear to have google cloud enabled "false" , etc.

This comment in the "Getting Started" guide suggests we don't have to configure anything

Google Cloud Platform Setup-> Obtain service account credentials. 
"This step is only required to manage your GCP project from Spinnaker running outside that project (e.g. Spinnaker is running on AWS or in a different GCP project)."

Please help us figure out how to enable the GCE account.

**Comment by lwander** [comment]
@ewiseblatt

On the VM that isn't showing your configured GCE account, could you post the results of 
```
$ curl localhost:7002/env
```
in a gist and link it here? That will show us what configuration the component of Spinnaker in charge of managing the cloud provider accounts is picking up.

**Comment by radkin** [comment]
Done, thank you.
https://gist.github.com/radkin/c03cbf599c20c9737caf.js

**Comment by lwander** [comment]
I'm not too familiar with the C2D solution, but if I had to guess you need to export the env var `SPINNAKER_GOOGLE_ENABLED = true`. Or, just set `providers.google.enabled: true` in one of the config files.

**Comment by tomaslin** [comment]
it also looks like you need to point providers.google.primaryCredentials.jsonPath: "" to your .json file that you created under Obtain service account credentials section in GCP config on http://spinnaker.io/documentation/getting_started.html

**Comment by lwander** [comment]
@tomaslin that shouldn't be needed as long as he is managing a GCP project from a VM inside that same project, since the provider can pull them from the host VM: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/security/GoogleNamedAccountCredentials.java#L114

**Comment by ewiseblatt** [comment]
Dang, I lost my reply message somehow when my trackpad interpreted my palm
as a gesture and cannot find a draft.

Your deployment looks ok. We use InstallSpinnaker.sh as the basis for
creating the click to deploy image. Except for version drift (and I cannot
think of a recent change that is related) they are the same.

You shouldnt need json credentials (service accounts) since you are
managing the same project that you deployed spinnaker into. GCE
automaticaly gives you permission into your own account.

If you are installing spinnaker using InstallSpinnaker.sh make sure that
your VM has the compute-rw scopes. See the Developer's Console info page
for your instance. At the bottom it will list the scopes. It should say
"Read Write" for "Compute". Scopes are determined when you create the VM so
if it isnt there, you will need to create a new VM. If you use the console,
just add that scope in. I dont think it is there by default. Under the
"boot disk" panel is "Identity and API Access". Click the bottom radio
where you configure each API. Turn "Compute" to "Read Write". I'm not sure
what happens if you dont, but it definitely will not work (I'd assume you
would still see the account though). You you created the instance with
gcloud, add "--scopes compute-rw" to the commandline.

The log file you want is /var/log/spinnaker/clouddriver/clouddriver.log. It
should have entries for gce, but not sure what a failure would look like
but would expect to see something if in fact that is the case.

Try to curl localhost:7002/credentials. You should see your
my-google-account in there based on the config you showed. When you say you
dont see it, I will assume that it is in deck (the UI) that you arent
seeing it. Let's verify clouddriver first. That's the interface between
spinnaker and the underlying cloud platforms.

If none of the above work, provide some more info and I'll try some more.
Might not get back to you until the morning though.

**Comment by radkin** [comment]
That worked like a charm. 
Specifically, the change in the VM instance 
Create an Instance->API Access->Compute->"read write"
Thanks. 

*note* The change did not take effect on a snapshot disk without a "sudo restart spinnaker
