### ISSUE TITLE
Run a Process ( in a container ) stage

### ISSUE THREAD

**Issue by tomaslin** [spinnaker/spinnaker#818]
The idea here is to have a stage in Spinnaker that would allow execution into a container.

This would be very similar to the functionality that Rush provides today, the user issues a command, a container is started and monitored until termination and a link to the underlying logs are archived.

The difference between this and Rush is that we would likely send out calls to clouddriver endpoints that would be able to start and return results from a container run ( so kubernetes, titus or whichever other container-based cloud provider is added later would know how to run this ). 

The idea of container processes can be extended for custom stages as well, since it would allow us to add and share stages such as script as a container.

**Comment by lwander** [comment]
Would this be used for scripting, heavy duty job based workloads, or both?

**Comment by tomaslin** [comment]
to us, the engine for heavy duty job based workloads and scripting is the same

**Comment by lwander** [comment]
It would be nice if this had a corresponding ad-hoc UI component, something similar to creating a server group, where you can see the containers running this job show up among your other server groups.

**Comment by tomaslin** [comment]
we distinguish between batch and service style jobs, so in theory this will not show up in the clusters screen

**Comment by lwander** [comment]
Kubernetes does too - but I could see some feedback on the job's status being useful.

If you farm out work to 1000 containers, it would be reassuring to see they are all scheduled (which they might not be, as you could have hit the limits of your cluster), that they are running for a similar amount of time (early insight into crashing containers is useful), and with the metrics endpoint recently added to clouddriver, it would be nice to click on a container running your service and see how hard it's actually working. 

Visually, it could make sense under "Server Groups" to have jobs show up similar to clusters, but with a strong visual distinction (color of the header bar, pattern, something).

Do you guys keep around the status of completed container executions?

**Comment by tomaslin** [comment]
Don't really intend for this issue to capture Batch processing, TBH. That can come later but right now there is really not the need for this for us.

**Comment by lwander** [comment]
Will the batch processing be using the same API as the script stage?

**Comment by tomaslin** [comment]
If anything, the script stage would use this API under the hood and not the other way around.

**Comment by tomaslin** [comment]
So what I have in mind right now:

Clouddriver exposes two endpoints:

containerProcess / start
containerProcess / status
containerProcess / cancel ( maybe )

under the hood, the cloudprovider value will route to the correct cloud provider, i.e, titan or k8

There will be an orca stage like the jenkins stage that will run this endpoint and poll for completion. 

There can also be other stages that will be built on top of this stage ( i.e, script could have a fixed list of images that it uses, custom stages could plug into well known input / output and polling semantics, etc )

**Comment by lwander** [comment]
It would be nice if the batch processing and script stages shared the same API since they will be doing effectively the same thing, except that the script stage has `n=1` containers. So instead, it could follow the clouddriver convention of something like 

`/{provider}/ops -d [ { "runProcess": { "application": ..., "replicas": "1000", "image": "myscript:latest", ...} } ]`

`/{provider}/ops -d [ { "cancelProcess": { "application": ..., ...} } ]`

Granted, not every provider can run that operation, but applications without those providers enabled never have to surface the fact that these operation exist within Deck, and those that do will let you select the container provider to use.

Also, I'm not sure that `/status` is needed, because we could just poll the cache for the relevant containers, which is probably where the batch processing stage will store its intermediate results.

**Comment by tomaslin** [comment]
Using the same endpoint makes sense to me for the deploy. I am not sure we can guarantee that the relevant containers are cached ( they are not in Titus )

**Comment by tomaslin** [comment]
@lwander also would challenge the notion that it's 1 container vs. one job since potential use case might be 16 containers to shard testing, for example

**Comment by tomaslin** [comment]
The interesting thing out of this discussion is that limiting this to the container part is probably unnecessary. You could probably have the same functionality just around a gcp, quip or cloud foundry stage.

**Comment by lwander** [comment]
Yes, that would be awesome to have this for every provider.

So why not make this an early start at the batch processing resource? It sounds like there are no differences between the script stage and the batch processing ad-hoc stage/pipeline stage.

**Comment by tomaslin** [comment]
you keep talking about this batch processing resource. I'm not aware of what this is or where it is being discussed

**Comment by lwander** [comment]
@tomaslin and I talked about this offline, and the conclusion was:

Both batch processing and scripts are identical. It will be up to the provider if they want to cache containers running as a part of a job rather than a service, as long as they can provide job status to an endpoint like `/processStatus/....` for the purpose of this script stage.

**Comment by tomaslin** [comment]
this is done
