### ISSUE TITLE
deck-ui: Top level "Projects" view for the console

### ISSUE THREAD

**Issue by vjames-bmc** [spinnaker/spinnaker#822]
This is a feature request.
Currently there is no easy way to find a project. You have to search for it by name.
It would be very useful if there is a "Projects" view in the console.

- A "Projects" link at the top (like Applications)
- Clicking the link will list all the Projects in the system
- A button to create new projects

**Comment by anotherchrisberry** [comment]
Our original plan was to get rid of the "Applications" tab altogether and rely on the search (aka "Infrastructure") tab. But it's probably the case that a lot of folks use that "Applications" view (unfortunately, we have no metrics on internal use at Netflix) and it makes as much sense to have a listing of all projects.

We've also discussed the possibility of having a top-level list view of other components: load balancers, images, server groups, etc.

I'll talk to our UX designer about this and see what his thoughts are.

**Comment by vjames-bmc** [comment]
I was thinking of something like this mockup. Or, it could be a tabular view like the "Applications" view.

![projectsview](https://cloud.githubusercontent.com/assets/16142228/13997129/c71b9382-f0ed-11e5-8cbb-19747848ce23.png)

**Comment by vjames-bmc** [comment]
@anotherchrisberry Did you get a chance to discuss with your UX designer?

**Comment by anotherchrisberry** [comment]
Sorry for the late reply. We discussed this on Friday, but did not get into the specifics of the Projects view. We've had a number of folks asking for a tabular, searchable view of, well, everything we index - projects, load balancers, security groups, clusters, images, etc.

Asgard did a pretty nice job of this - almost every type of object had a table view that allowed sorting and filtering. It would be nice to offer something similar. Due to the scale of the AWS footprint at Netflix, and the fact that Spinnaker indexes every account and region, I think we'd need to paginate the results, but that's okay.

We didn't agree on _where_ those tables should go - is it a top-level menu item, like Applications is now? Or does it drop in under Infrastructure? We are meeting again tomorrow, and I plan to discuss it then. Hopefully we can get some designs together this week of how we'd like it to look. I'll keep you posted via this issue.

**Comment by anotherchrisberry** [comment]
@vjames-bmc confirmed with our designer that we'll get some mockups either later this week or early next week. I'll share them here and we can discuss more then.

**Comment by vjames-bmc** [comment]
I took a shot at creating a list view for projects. Please see attached screenshot. Let me know once you hear back from UX. Hopefully, it won't be anything that is drastically different :) For now, I put "Projects" as a top level link. We can easily move it under the Infrastructure menu if needed.
![projectlist](https://cloud.githubusercontent.com/assets/16142228/14442521/0876ae2e-ffef-11e5-8497-7e585f6590f6.png)

**Comment by anotherchrisberry** [comment]
This is completed - thanks again!
