### ISSUE TITLE
new code is NOT baked into image for the sample "hello-spinnaker" project

### ISSUE THREAD

**Issue by ddup2** [spinnaker/spinnaker#847]
*Title*

new code is NOT baked into image for the sample "hello-spinnaker" project.

*Cloud Provider*

AWS

*Environment*

```I am running Spinnaker using the Amazon images to deploy into AWS. ```

*Feature Area*

Bake

*Description*

expected: new debian package hello-karyon-rxnetty=1-2 is baked into image and deployed
actually: hello-karyon-rxnetty=1-1 is always baked into image, no matter "force bake" is selected or not

*Steps to Reproduce*

Following the example in http://www.spinnaker.io/docs/hello-spinnaker, and bump the "release" number to trigger a new build, we can see hello-karyon-rxnetty_1-2_all.deb is generated in S3 bucket, and can be installed manually in another machine, however, in the deployed instance hello-karyon-rxnetty=1-1 is installed, and the rebake log shows as below:

==> amazon-ebs: Provisioning with shell script: /opt/rosco/config/packer/install_packages.sh
    amazon-ebs: repository="http://mus-spinnaker.s3-website-us-west-2.amazonaws.com trusty main"
    amazon-ebs: package_type=deb
    amazon-ebs: packages=hello-karyon-rxnetty=1-1
    amazon-ebs: upgrade=

**Comment by lwander** [comment]
I believe that the contents after the '-' are treated as a timestamp, and are ignored when determining if the version of the package were changed. @duftler can confirm

**Comment by ddup2** [comment]
in the last section of the 3rd sample, e.g. http://www.spinnaker.io/docs/from-source-to-prod, it's said bumping the release number should work, moreover, if run apt-get update && apt-get install  hello-karyon-rxnetty in any other machine (even including the deployed instance) ,  hello-karyon-rxnetty_1-2_all.deb will be installed. 

# Change the number on the “release” line.
git commit -a -m "Bump release number"

**Comment by ddup2** [comment]
I bumped the jumped
==> amazon-ebs: Pausing 30s before the next provisioner...
==> amazon-ebs: Provisioning with shell script: /opt/rosco/config/packer/install_packages.sh
    amazon-ebs: repository="http://mus-spinnaker.s3-website-us-west-2.amazonaws.com trusty main"
    amazon-ebs: package_type=deb
    amazon-ebs: packages=hello-karyon-rxnetty=1-1
    amazon-ebs: upgrade=

**Comment by duftler** [comment]
You should not have to check 'force rebake'. Checking that option would (should) cause what would otherwise be considered a duplicate bake to be repeated regardless. Since you are bumping the version number, the requested bake should not be treated as a duplicate.

The first thing to check is that the triggered pipeline execution has a "BUILD #25" label (with whatever jenkins job number was the last one executed) next to it. Clicking on that should take you to the jenkins job page.

That job page should have a "Build Artifacts" section, and that sections should list the "2-1" version of the deb.

If that's all correct, the next thing to check is the context of the pipeline execution to see what artifact is being resolved via the pipeline trigger. You can easily get to the pipeline context via the Source link: 
![image](https://cloud.githubusercontent.com/assets/8437718/14530665/f8c471ec-0227-11e6-85c3-9325d05804b2.png)

Search throughout the returned json for 'karyon' and see what you can find out; That's where the clues should be.

You should also come across a `bakePackageName` attribute in the Bake stage context. That should include the version (and arch) details. It will give you an idea what is being sent from the orchestration engine (orca) to the bakery (rosco). In the same scope as `bakePackageName`, you should see: `package": "hello-karyon-rxnetty",`. Please ensure that the value associated with that `package` attr does not contain a version (that is, it should contain just `hello-karyon-rxnetty` as you see it here).

Once we have these additional details, we can dig further.

**Comment by ddup2** [comment]
here is what I found in the source link, bakePackage is hello-karyon-rxnetty_1-1_all, while the artifacts contains latest hello-karyon-rxnetty_2-2_all.deb.

"context": {
"storeType": "ebs",
"package": "hello-karyon-rxnetty",
"baseLabel": "release",
"type": "bake",
"extendedAttributes": {},
"amiSuffix": "20160415043235",
"vmType": "hvm",
"baseOs": "trusty",
"name": "Bake in us-west-2",
"cloudProviderType": "aws",
"region": "us-west-2",
"user": "[anonymous]",
"previouslyBaked": true,
"job": "Hello%20Build",
"buildNumber": "22",
"bakePackageName": "hello-karyon-rxnetty_1-1_all",
"commitHash": "6042fe9e760112875288da046b077eb649c1a584",
"status": {
"id": "14c67490-015f-11e6-b375-022f2a6cef93",
"state": "COMPLETED",
"result": "SUCCESS",
"resourceId": "14c67490-015f-11e6-b375-022f2a6cef93"
},



"artifacts": [
{
"fileName": "hello-karyon-rxnetty_1-1_all.deb",
"displayPath": "hello-karyon-rxnetty_1-1_all.deb",
"relativePath": "build/distributions/hello-karyon-rxnetty_1-1_all.deb"
},
{
"fileName": "hello-karyon-rxnetty_1-2_all.deb",
"displayPath": "hello-karyon-rxnetty_1-2_all.deb",
"relativePath": "build/distributions/hello-karyon-rxnetty_1-2_all.deb"
},
{
"fileName": "hello-karyon-rxnetty_1-3_all.deb",
"displayPath": "hello-karyon-rxnetty_1-3_all.deb",
"relativePath": "build/distributions/hello-karyon-rxnetty_1-3_all.deb"
},
{
"fileName": "hello-karyon-rxnetty_1-4_all.deb",
"displayPath": "hello-karyon-rxnetty_1-4_all.deb",
"relativePath": "build/distributions/hello-karyon-rxnetty_1-4_all.deb"
},
{
"fileName": "hello-karyon-rxnetty_2-1_all.deb",
"displayPath": "hello-karyon-rxnetty_2-1_all.deb",
"relativePath": "build/distributions/hello-karyon-rxnetty_2-1_all.deb"
},
{
"fileName": "hello-karyon-rxnetty_2-2_all.deb",
"displayPath": "hello-karyon-rxnetty_2-2_all.deb",
"relativePath": "build/distributions/hello-karyon-rxnetty_2-2_all.deb"
}

**Comment by ddup2** [comment]
@duftler any update? this is the basic function of the whole magic flow, I would really get it working so that I can make use of full power of spinnaker, thanks!

**Comment by ajordens** [comment]
Is your Jenkins build configured to clean it's workspace?

It seems strange to me to have that many artifacts being captured ... 

As per @duftler's comment above:

    The first thing to check is that the triggered pipeline execution has a "BUILD #25" label (with whatever jenkins job number was the last one executed) next to it. Clicking on that should take you to the jenkins job page.

    That job page should have a "Build Artifacts" section, and that sections should list the "2-1" version of the deb.

What does the Jenkins job report as captured artifacts? If the workspace is being cleared, I would only expect to see a single `.deb` in build/distributions.

**Comment by ddup2** [comment]
@ajordens you're right, the "Build Artifacts" in my previous Jenkins settings show multiple *.deb package,  following your suggestions, I can't find "clean workspace" in the jenkins configuration, so I installed a Jenkins plugin https://wiki.jenkins-ci.org/display/JENKINS/Workspace+Cleanup+Plugin and configure the build job to cleanup workspace before every build, now everything seems working.

If it's a MUST to install this plugin and configure the project as needed, does it make sense to include this in the sample official guide? thanks!

**Comment by duftler** [comment]
Experimented a bit more with this, and I think the shortest path to getting the prior builds cleaned up is to also execute the gradle `clean` target. I've tested this to verify the behavior and updated the docs to reflect this change:
![image](https://cloud.githubusercontent.com/assets/8437718/14607035/e0805582-054d-11e6-8c4d-384ddd733d30.png)

**Comment by ddup2** [comment]
awesome, thanks @duftler  for the prompt response!

**Comment by duftler** [comment]
Thanks for raising the issue.
